import { supabase } from './supabase';

type Role='admin'|'client';
type Reaction='ok'|'like'|'question'|'heart'|'smile';
type Identity={id?:string|null;full_name:string;role?:string|null;avatar_url?:string|null;avatar_position_x?:number|null;avatar_position_y?:number|null;avatar_zoom?:number|null};
type Message={id:string;company_id:string;target_id:string;author_user_id?:string|null;body:string;client_visible:boolean;source_actor?:'admin'|'client'|'system'|null;created_at:string};
type FileToken={name:string;path:string;mime:string;size:number};
type Context={id:string;company_id:string;project_id?:string|null;protocol?:string|null};

let installed=false,busy=false,timer=0,activeId='';
let channel:ReturnType<NonNullable<typeof supabase>['channel']>|null=null;
let pending:FileToken[]=[];
const mediaCache=new Map<string,string>();
const emojiList=['🙂','😊','👍','🙏','✨','✅','💡','📌','📎','❤️','👏','🤝'];
const reactionList:Array<{code:Reaction;symbol:string;label:string}>=[
  {code:'ok',symbol:'✓',label:'Entendido'},{code:'like',symbol:'👍',label:'Gostei'},
  {code:'question',symbol:'?',label:'Tenho uma dúvida'},{code:'heart',symbol:'♥',label:'Amei'},
  {code:'smile',symbol:'☺',label:'Legal'},
];
const tokenRx=/\[\[arquivo\|([^|]+)\|([^|]+)\|([^|]+)\|(\d+)\]\]/g;

function role():Role|null{if(location.pathname.startsWith('/admin/projetos'))return'admin';if(location.pathname.startsWith('/cliente/entregaveis'))return'client';return null;}
function initials(v:string){return v.split(/\s+/).filter(Boolean).slice(0,2).map(p=>p[0]?.toUpperCase()||'').join('')||'C';}
function when(v:string){const d=new Date(v);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(d).replace('.','');}
function safe(v:string){return v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9._-]+/g,'-').replace(/-+/g,'-').slice(0,90)||'arquivo';}
function setValue(el:HTMLTextAreaElement,v:string){const setter=Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value')?.set;setter?.call(el,v);el.dispatchEvent(new Event('input',{bubbles:true}));el.focus();}
async function media(raw?:string|null){if(!raw||!supabase||!raw.startsWith('private:'))return raw||'';const cached=mediaCache.get(raw);if(cached)return cached;const{data,error}=await supabase.storage.from('cali-workspace-private').createSignedUrl(raw.slice(8),3600);if(error||!data?.signedUrl)return'';mediaCache.set(raw,data.signedUrl);return data.signedUrl;}
async function hydrate(v:Identity):Promise<Identity>{return{...v,avatar_url:await media(v.avatar_url)};}
function avatar(v:Identity){const el=document.createElement('span');el.className='workspace-chat-avatar';if(v.avatar_url){const x=Number(v.avatar_position_x??50),y=Number(v.avatar_position_y??50),z=Math.max(1,Number(v.avatar_zoom??1));el.style.backgroundImage=`url("${v.avatar_url.replace(/"/g,'\\"')}")`;el.style.backgroundPosition=`${x}% ${y}%`;el.style.backgroundSize=`${z*100}%`;el.style.backgroundRepeat='no-repeat';}else el.textContent=initials(v.full_name);el.title=v.full_name;return el;}
function parseBody(body:string){const files:FileToken[]=[];const clean=body.replace(tokenRx,(_m,n,p,t,s)=>{try{files.push({name:decodeURIComponent(n),path:decodeURIComponent(p),mime:decodeURIComponent(t),size:Number(s||0)});}catch{files.push({name:n,path:p,mime:t,size:Number(s||0)});}return'';}).trim();return{clean,files};}
function linkify(el:HTMLElement,text:string){text.split(/(https?:\/\/[^\s]+)/g).forEach(part=>{if(/^https?:\/\//i.test(part)){const a=document.createElement('a');a.href=part;a.target='_blank';a.rel='noopener noreferrer';a.textContent=part;el.append(a);}else if(part)el.append(document.createTextNode(part));});}
async function openFile(f:FileToken){if(!supabase)return;const{data,error}=await supabase.storage.from('cali-workspace-private').createSignedUrl(f.path,300);if(error||!data?.signedUrl){alert('Não foi possível abrir este anexo agora.');return;}window.open(data.signedUrl,'_blank','noopener,noreferrer');}

async function identitySet(r:Role,companyId:string){const map=new Map<string,Identity>();let admin:Identity={full_name:'Patrícia Lima'},client:Identity={full_name:'Cliente'};if(!supabase)return{map,admin,client};const{data:s}=await supabase.auth.getSession();const uid=s.session?.user?.id||'';const self=uid?await supabase.from('profiles').select('id,full_name,role,avatar_url,avatar_position_x,avatar_position_y,avatar_zoom').eq('id',uid).maybeSingle():{data:null};const me=self.data?await hydrate(self.data as Identity):null;if(me?.id)map.set(String(me.id),me);
  if(r==='admin'||me?.role==='admin'){if(me)admin=me;const q=await supabase.from('profiles').select('id,full_name,role,avatar_url,avatar_position_x,avatar_position_y,avatar_zoom').eq('company_id',companyId).eq('role','client').eq('active',true);for(const row of(q.data||[])as Identity[]){const p=await hydrate(row);if(p.id)map.set(String(p.id),p);if(client.full_name==='Cliente')client=p;}}
  if(r==='client'&&me?.role==='client'){client=me;const contact=await supabase.rpc('get_client_account_contact');const row=Array.isArray(contact.data)?contact.data[0]:contact.data;if(row)admin=await hydrate(row as Identity);}return{map,admin,client};}
function who(m:Message,ids:Awaited<ReturnType<typeof identitySet>>){if(m.author_user_id&&ids.map.has(m.author_user_id))return ids.map.get(m.author_user_id)!;if(m.source_actor==='client')return ids.client;if(m.source_actor==='system')return{full_name:'CALI Workspace'};return ids.admin;}
function visibleChannel(r:Role){if(r==='client')return true;const b=document.querySelector<HTMLElement>('.deliverable-workspace-modal-v2 .conversation-channels-v2 button.active');return!b||/cliente/i.test(b.textContent||'');}

async function toggleReaction(message:Message,code:Reaction){if(!supabase)return;const{data:s}=await supabase.auth.getSession();const uid=s.session?.user?.id;if(!uid)return;const existing=await supabase.from('comment_reactions').select('id').eq('comment_id',message.id).eq('user_id',uid).eq('reaction',code).maybeSingle();const result=existing.data?.id?await supabase.from('comment_reactions').delete().eq('id',existing.data.id):await supabase.from('comment_reactions').insert({company_id:message.company_id,comment_id:message.id,user_id:uid,reaction:code});if(result.error)alert(result.error.message);schedule();}
function reactionBar(message:Message,rows:any[],uid:string){const bar=document.createElement('div');bar.className='workspace-chat-reactions';reactionList.forEach(item=>{const matching=rows.filter(r=>r.comment_id===message.id&&r.reaction===item.code),mine=matching.some(r=>r.user_id===uid);const b=document.createElement('button');b.type='button';b.className=mine?'active':'';b.title=item.label;b.setAttribute('aria-label',item.label);b.setAttribute('aria-pressed',String(mine));const s=document.createElement('span');s.textContent=item.symbol;b.append(s);if(matching.length){const c=document.createElement('small');c.textContent=String(matching.length);b.append(c);}b.onclick=e=>{e.preventDefault();e.stopPropagation();void toggleReaction(message,item.code);};bar.append(b);});return bar;}

async function render(context:Context,r:Role){if(!supabase)return;const list=document.querySelector<HTMLElement>('.deliverable-workspace-modal-v2 .conversation-list-v2');if(!list)return;const visible=visibleChannel(r);const[comments,ids,session]=await Promise.all([supabase.from('comments').select('id,company_id,target_id,author_user_id,body,client_visible,source_actor,created_at').eq('target_type','deliverable').eq('target_id',context.id).eq('client_visible',visible).order('created_at'),identitySet(r,context.company_id),supabase.auth.getSession()]);if(comments.error)return;const messages=(comments.data||[])as Message[];const commentIds=messages.map(m=>m.id);let reactionRows:any[]=[];if(commentIds.length){const rr=await supabase.from('comment_reactions').select('id,comment_id,user_id,reaction').in('comment_id',commentIds);reactionRows=rr.data||[];}const uid=session.data.session?.user?.id||'';const signature=`${visible}:${messages.map(m=>`${m.id}:${m.body}:${m.created_at}`).join('|')}:${reactionRows.map(x=>`${x.comment_id}:${x.user_id}:${x.reaction}`).join('|')}`;if(list.dataset.workspaceChatSignature===signature&&list.querySelector('.workspace-chat-line,.workspace-chat-empty'))return;list.dataset.workspaceChatSignature=signature;list.classList.add('workspace-chat-list');list.replaceChildren();if(!messages.length){const empty=document.createElement('div');empty.className='workspace-chat-empty';empty.textContent=visible?'A conversa começa aqui.':'Nenhuma nota interna neste entregável.';list.append(empty);return;}
  messages.forEach(m=>{const id=who(m,ids),actor=m.source_actor||'admin',mine=actor===r,line=document.createElement('div');line.className=`workspace-chat-line role-${actor} ${mine?'mine':'other'} ${visible?'':'internal'}`;line.dataset.commentId=m.id;const bubble=document.createElement('div');bubble.className='workspace-chat-bubble';const head=document.createElement('div');head.className='workspace-chat-head';const name=document.createElement('strong');name.textContent=visible?id.full_name:`${id.full_name} · nota interna`;const time=document.createElement('time');time.textContent=when(m.created_at);head.append(name,time);bubble.append(head);const parsed=parseBody(m.body);if(parsed.clean){const p=document.createElement('p');linkify(p,parsed.clean);bubble.append(p);}if(parsed.files.length){const files=document.createElement('div');files.className='workspace-chat-attachments';parsed.files.forEach(f=>{const b=document.createElement('button');b.type='button';b.className='workspace-chat-attachment';const icon=document.createElement('span');icon.textContent='📎';const copy=document.createElement('span'),strong=document.createElement('strong'),small=document.createElement('small');strong.textContent=f.name;small.textContent=f.size?`${Math.max(1,Math.round(f.size/1024))} KB`:'arquivo';copy.append(strong,small);b.append(icon,copy);b.onclick=()=>void openFile(f);files.append(b);});bubble.append(files);}if(visible&&actor!=='system')bubble.append(reactionBar(m,reactionRows,uid));if(mine)line.append(bubble,avatar(id));else line.append(avatar(id),bubble);list.append(line);});requestAnimationFrame(()=>{list.scrollTop=list.scrollHeight;});}

function tray(compose:HTMLElement){let t=compose.querySelector<HTMLElement>('.workspace-chat-pending');if(!t){t=document.createElement('div');t.className='workspace-chat-pending';compose.prepend(t);}t.replaceChildren();pending.forEach((f,i)=>{const chip=document.createElement('span');chip.className='workspace-chat-pending-chip';const text=document.createElement('span');text.textContent=`📎 ${f.name}`;const x=document.createElement('button');x.type='button';x.textContent='×';x.onclick=async()=>{pending.splice(i,1);if(supabase)await supabase.storage.from('cali-workspace-private').remove([f.path]);tray(compose);};chip.append(text,x);t!.append(chip);});t.style.display=pending.length?'flex':'none';}
async function upload(file:File,context:Context,compose:HTMLElement){if(!supabase)return;const allowed=new Set(['application/pdf','image/png','image/jpeg','image/webp','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','application/vnd.openxmlformats-officedocument.presentationml.presentation']);if(!allowed.has(file.type)){alert('Use PDF, imagem, Word, Excel ou PowerPoint.');return;}if(file.size>10*1024*1024){alert('Cada anexo pode ter até 10 MB.');return;}if(pending.length>=5){alert('Você pode enviar até 5 anexos por mensagem.');return;}const{data:s}=await supabase.auth.getSession();const uid=s.session?.user?.id;if(!uid)return;const path=`deliverable-chat/${context.company_id}/${context.id}/${uid}/${Date.now()}-${safe(file.name)}`;const{error}=await supabase.storage.from('cali-workspace-private').upload(path,file,{contentType:file.type,upsert:false});if(error){alert(`Não consegui anexar “${file.name}”.`);return;}pending.push({name:file.name,path,mime:file.type,size:file.size});tray(compose);}
async function send(context:Context,r:Role,textarea:HTMLTextAreaElement,button:HTMLButtonElement,compose:HTMLElement){if(!supabase)return;const text=textarea.value.trim();if(!text&&!pending.length)return;const tokens=pending.map(f=>`[[arquivo|${encodeURIComponent(f.name)}|${encodeURIComponent(f.path)}|${encodeURIComponent(f.mime)}|${f.size}]]`).join('\n');const body=[text,tokens].filter(Boolean).join('\n');button.disabled=true;try{if(r==='client'){const res=await supabase.rpc('client_submit_deliverable_comment',{p_deliverable_id:context.id,p_body:body});if(res.error)throw res.error;}else{const{data:s}=await supabase.auth.getSession();const res=await supabase.from('comments').insert({company_id:context.company_id,target_type:'deliverable',target_id:context.id,author_user_id:s.session?.user?.id||null,body,client_visible:visibleChannel(r),source_actor:'admin'});if(res.error)throw res.error;}pending=[];setValue(textarea,'');tray(compose);setTimeout(schedule,70);}catch(e){alert(e instanceof Error?e.message:'Não foi possível enviar a mensagem.');}finally{button.disabled=false;}}
function composer(context:Context,r:Role){const pane=document.querySelector<HTMLElement>('.deliverable-workspace-modal-v2 .conversation-pane-v2'),compose=pane?.querySelector<HTMLElement>('.conversation-composer-v2'),textarea=compose?.querySelector<HTMLTextAreaElement>('textarea'),sendButton=compose?.querySelector<HTMLButtonElement>('button.primary');if(!compose||!textarea||!sendButton)return;compose.classList.add('workspace-chat-compose');if(!compose.querySelector('.workspace-chat-tools')){const tools=document.createElement('div');tools.className='workspace-chat-tools';const attach=document.createElement('button');attach.type='button';attach.textContent='📎';attach.title='Anexar arquivo';const input=document.createElement('input');input.type='file';input.multiple=true;input.hidden=true;input.accept='.pdf,.png,.jpg,.jpeg,.webp,.docx,.xlsx,.pptx';attach.onclick=()=>input.click();input.onchange=async()=>{for(const f of Array.from(input.files||[]))await upload(f,context,compose);input.value='';};const link=document.createElement('button');link.type='button';link.textContent='🔗';link.title='Inserir link';link.onclick=()=>{const v=prompt('Cole o link que deseja compartilhar:');if(!v)return;const url=/^https?:\/\//i.test(v.trim())?v.trim():`https://${v.trim()}`;setValue(textarea,`${textarea.value}${textarea.value?' ':''}${url}`);};const emoji=document.createElement('button');emoji.type='button';emoji.textContent='😊';emoji.title='Emojis';const picker=document.createElement('div');picker.className='workspace-chat-emoji-picker';picker.hidden=true;emojiList.forEach(e=>{const b=document.createElement('button');b.type='button';b.textContent=e;b.onclick=()=>{setValue(textarea,`${textarea.value}${e}`);picker.hidden=true;};picker.append(b);});emoji.onclick=()=>picker.hidden=!picker.hidden;tools.append(attach,input,link,emoji,picker);compose.insertBefore(tools,textarea);tray(compose);if(r==='admin')compose.querySelectorAll<HTMLButtonElement>('.secondary').forEach(b=>{if(/anexar/i.test(b.textContent||''))b.style.display='none';});}
  if(!sendButton.dataset.workspaceChatBound){sendButton.dataset.workspaceChatBound='1';sendButton.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();void send(context,r,textarea,sendButton,compose);},true);textarea.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();void send(context,r,textarea,sendButton,compose);}},true);}}

async function subscribe(context:Context){if(!supabase||(activeId===context.id&&channel))return;if(channel)await supabase.removeChannel(channel);activeId=context.id;channel=supabase.channel(`deliverable-chat-v35-${context.id}-${Date.now()}`).on('postgres_changes',{event:'INSERT',schema:'cali_workspace',table:'comments',filter:`target_id=eq.${context.id}`},()=>{window.dispatchEvent(new CustomEvent('cali:workspace-chime'));setTimeout(schedule,70);}).on('postgres_changes',{event:'*',schema:'cali_workspace',table:'comment_reactions',filter:`company_id=eq.${context.company_id}`},()=>setTimeout(schedule,55)).subscribe();}
async function enhance(){if(busy||!supabase)return;const r=role();if(!r)return;const modal=document.querySelector<HTMLElement>('.deliverable-workspace-modal-v2');if(!modal)return;if(r==='client')modal.querySelector<HTMLElement>('.deliverable-workspace-header-v2 .status-chip-v3')?.remove();const protocol=modal.querySelector<HTMLElement>('.deliverable-title-v2 .section-kicker')?.textContent?.trim()||'';if(!protocol.startsWith('CALI-DEL-'))return;busy=true;try{const result=await supabase.from('deliverables').select('id,company_id,project_id,protocol').eq('protocol',protocol).maybeSingle();const context=result.data as Context|null;if(!context?.id||!context.company_id)return;await subscribe(context);const pane=modal.querySelector<HTMLElement>('.conversation-pane-v2');if(pane){pane.classList.add('workspace-chat-standard');await render(context,r);composer(context,r);}}finally{busy=false;}}
function schedule(){clearTimeout(timer);timer=window.setTimeout(()=>void enhance(),65);}
export function installDeliverableChatStandardRuntimeV35(){if(installed||typeof window==='undefined')return;installed=true;schedule();const observer=new MutationObserver(schedule);observer.observe(document.body,{childList:true,subtree:true});window.addEventListener('focus',schedule);window.addEventListener('popstate',schedule);}
