export type PortalSignal={level:'high'|'medium'|'info'|'attention';text:string};
export type ProposalProfileContext={serviceSlug:string;packageCode:string;packageLabel:string;answers:Record<string,any>;minimumMonths:number;monthlyHours:number};
export type PortalProposalProfile={solutionCopy:string;operating:string[];commercial:string[];outOfScope:string[];advantages:string[];bonus:[string,string];nextSteps:Array<[string,string]>};

const commonProjectCommercial=[
  'A proposta é válida pelo prazo indicado neste documento.',
  'O início está condicionado à assinatura do contrato e ao cumprimento da condição de pagamento acordada.',
  'Custos de deslocamento, hospedagem, licenças ou fornecedores só são incluídos quando descritos expressamente.',
  'Materiais, métodos e modelos CALI permanecem protegidos por direitos autorais e não podem ser reproduzidos fora do uso contratado.',
];
const projectNextSteps:Array<[string,string]>=[
  ['Aprovação','Confirmação do investimento, formato e escopo.'],['Contrato','Formalização das condições e responsabilidades.'],['Kickoff','Alinhamento final e organização dos insumos.'],['Início','Execução conforme o cronograma acordado.'],
];
const commonFallback:PortalProposalProfile={solutionCopy:'Solução conectada ao contexto e ao resultado esperado.',operating:['O formato, a duração e a cadência seguem o escopo aprovado.','A empresa disponibiliza os dados, pessoas e aprovações necessários ao trabalho.'],commercial:commonProjectCommercial,outOfScope:['Atividades não descritas expressamente no escopo aprovado.'],advantages:['Escopo conectado ao contexto e ao resultado esperado.','Condução direta por Patrícia Lima.','Limites e responsabilidades descritos com clareza.'],bonus:['Material de aplicação','Um recurso simples para apoiar a continuidade do trabalho após a entrega.'],nextSteps:projectNextSteps};

export function portalServiceSignals(serviceSlug:string,a:Record<string,any>):{alerts:PortalSignal[];notices:PortalSignal[]}{
 const alerts:PortalSignal[]=[],notices:PortalSignal[]=[];
 if(serviceSlug==='assessoria-estrategica'){
  const fronts=a.frentes||[];
  if(fronts.length>=5||a.frequencia==='semanal'||a.presencial==='mais')alerts.push({level:'high',text:'Complexidade e cadência indicam CALI FULL.'});
  if(a.rh_interno==='nao')alerts.push({level:'medium',text:'Empresa sem RH interno: esclarecer limites entre advisory e execução operacional.'});
  if((a.indicadores||[]).some((item:any)=>String(item).startsWith('Nenhum')))alerts.push({level:'medium',text:'Incluir implantação mínima de rotina de indicadores.'});
  if(a.modelo_interesse==='PARTNER'&&(fronts.length>=5||a.frequencia==='semanal'||['mensal','mais'].includes(a.presencial)))alerts.push({level:'high',text:'O lead escolheu PARTNER, mas complexidade, cadência ou presencialidade sugerem revisar o encaixe para FULL.'});
  if(a.rh_interno==='nao')notices.push({level:'info',text:'A assessoria oferece direção sênior e estruturação estratégica. Rotinas de DP, folha e operação contínua não fazem parte do escopo.'});
  if(a.presencial==='mais')notices.push({level:'attention',text:'Mais de uma visita mensal exige desenho específico de agenda, deslocamento e carga de horas.'});
 }
 if(serviceSlug==='mentoria-rh'){
  if(a.modalidade==='grupo'&&Number(a.participantes)>5)alerts.push({level:'high',text:'O programa em grupo é limitado a 5 participantes da mesma empresa.'});
  if(a.suporte==='proximo')alerts.push({level:'medium',text:'Prever carga adicional de suporte entre encontros.'});
  if(a.modalidade==='grupo'&&['avaliacao','nao_apresentada'].includes(a.status_iniciativa))alerts.push({level:'medium',text:'Iniciativa corporativa ainda não aprovada: a proposta deve apoiar a decisão e explicitar as premissas.'});
  if(a.frequencia==='semanal')alerts.push({level:'medium',text:'Cadência semanal: validar agenda e intensidade do ciclo.'});
  if(a.modalidade==='grupo')notices.push({level:'info',text:'O programa em grupo atende até 5 profissionais da mesma empresa e parte de um objetivo comum. Casos individuais continuam sendo tratados com confidencialidade.'});
  if(a.status_iniciativa==='nao_apresentada')notices.push({level:'attention',text:'Tudo bem estar no início: a proposta poderá ser estruturada para apoiar a apresentação interna e a tomada de decisão.'});
  if(a.suporte==='proximo')notices.push({level:'info',text:'Check-ins e discussão de casos entre encontros aumentam a carga dedicada e serão considerados no desenho do ciclo.'});
 }
 if(serviceSlug==='diagnostico-executivo'){
  if(Number(a.entrevistas)>10)alerts.push({level:'medium',text:'Mais de 10 entrevistas: revisar carga e cronograma.'});
  if(a.documentos==='desorganizada'||a.acesso_dados==='nao')alerts.push({level:'high',text:'Aplicar etapa e carga de organização documental antes da leitura.'});
  if(a.prazo_inicio==='imediato')alerts.push({level:'medium',text:'Confirmar disponibilidade mínima de quatro semanas.'});
  if(a.acesso_dados==='nao')notices.push({level:'attention',text:'Sem dados organizados, o cronograma precisa prever uma etapa inicial de coleta e estruturação das informações.'});
  if(a.prazo_inicio==='imediato')notices.push({level:'info',text:'Diagnósticos executivos exigem agenda de entrevistas e acesso a documentos; o início imediato depende da disponibilidade das pessoas-chave.'});
 }
 if(serviceSlug==='cultura-direcao'){
  if(Number(a.colaboradores)>200||Number(a.unidades)>3)alerts.push({level:'medium',text:'Revisar amostra, comunicação e logística por porte.'});
  if((a.contexto||[]).includes('ma'))alerts.push({level:'high',text:'Contexto de M&A exige trilha específica de integração cultural.'});
  if(a.patrocinio_lideranca==='baixo')alerts.push({level:'high',text:'Baixo patrocínio executivo: prever etapa de alinhamento antes da mobilização ampla.'});
  if(a.patrocinio_lideranca==='baixo')notices.push({level:'attention',text:'Projetos de cultura precisam de patrocínio visível da liderança. A proposta poderá incluir uma etapa inicial de alinhamento executivo.'});
  if((a.contexto||[]).includes('ma'))notices.push({level:'info',text:'Em fusões ou aquisições, o desenho considera identidades anteriores, integração e riscos de perda de pessoas-chave.'});
 }
 if(serviceSlug==='shadowing-lideranca'){
  if(a.presencial==='remoto')alerts.push({level:'medium',text:'O presencial é recomendado por ser a essência do Shadowing.'});
  if(Number(a.lideres)>1)alerts.push({level:'high',text:'O Shadowing é individual: organizar uma proposta ou ciclo próprio para cada liderança.'});
  if(a.ciencia_lideres==='nao')alerts.push({level:'high',text:'Planejar comunicação e consentimento antes da observação.'});
  if(a.ciencia_lideres==='nao')notices.push({level:'attention',text:'A observação precisa ser apresentada com transparência. O escopo pode incluir uma conversa de alinhamento antes do início.'});
  if(a.presencial==='remoto')notices.push({level:'info',text:'O formato remoto é possível quando existem rituais reais observáveis online; o presencial costuma gerar uma leitura mais completa.'});
 }
 if(serviceSlug==='treinamentos'){
  if(Number(a.participantes)>35)alerts.push({level:'medium',text:'Turma acima de 35 pessoas: avaliar divisão ou formato de palestra.'});
  if(a.formato==='presencial'&&!String(a.localidade||'').toLowerCase().includes('curitiba'))alerts.push({level:'medium',text:'Prever deslocamento e eventual hospedagem.'});
  if(a.data_desejada&&/próxima semana|semana que vem/i.test(a.data_desejada))alerts.push({level:'high',text:'Antecedência abaixo das quatro semanas recomendadas.'});
  if(a.gravacao==='sim')alerts.push({level:'medium',text:'Definir direito de uso, prazo, audiência e valor de licenciamento da gravação.'});
  if(Number(a.participantes)>35)notices.push({level:'attention',text:'Para mais de 35 pessoas, posso recomendar divisão em turmas ou formato de palestra para preservar a qualidade da experiência.'});
  if(a.gravacao==='sim')notices.push({level:'info',text:'Gravação e reutilização precisam constar no escopo, incluindo audiência, período e direitos de uso.'});
 }
 if(serviceSlug==='marca-empregadora'){
  if(a.reviews==='negativas')alerts.push({level:'high',text:'Prever frente de reputação e resposta a passivos de percepção.'});
  if(a.modelo_contratacao==='recorrente'&&(a.ativos||[]).includes('evp'))alerts.push({level:'medium',text:'Separar fase inicial de definição do EVP da sustentação mensal.'});
  if(!(a.equipe_interna||[]).includes('marketing')&&!(a.equipe_interna||[]).includes('comunicacao'))alerts.push({level:'medium',text:'Sem Marketing ou Comunicação: definir capacidade interna de produção e aprovação.'});
  if(a.reviews==='negativas')notices.push({level:'attention',text:'Quando há avaliações negativas, a primeira etapa costuma ser leitura de causa e reputação antes de campanhas de atração.'});
  if(a.modelo_contratacao==='recorrente'&&(a.ativos||[]).includes('evp'))notices.push({level:'info',text:'A definição do EVP é uma fase estruturante; a sustentação recorrente começa depois que essa base estiver validada.'});
 }
 if(serviceSlug==='solucao-personalizada'){
  if(a.prazo_inicio==='imediato')alerts.push({level:'medium',text:'Início imediato: validar agenda, disponibilidade dos decisores e insumos mínimos.'});
  if(a.formato_desejado==='presencial'&&!String(a.local_execucao||'').toLowerCase().includes('curitiba'))alerts.push({level:'medium',text:'Etapa presencial fora de Curitiba e Região Metropolitana: prever deslocamento e eventual hospedagem.'});
  if(a.etapa_decisao==='exploratoria')alerts.push({level:'medium',text:'Demanda ainda exploratória: a proposta deve explicitar premissas e possíveis caminhos antes de fechar o escopo.'});
  if(a.formato_desejado==='presencial')notices.push({level:'info',text:'Atuações presenciais são avaliadas conforme localidade, agenda, deslocamento e carga dedicada.'});
  if(a.etapa_decisao==='exploratoria')notices.push({level:'attention',text:'Tudo bem ainda não ter um escopo fechado. A leitura deste briefing serve justamente para organizar o melhor caminho.'});
 }
 return{alerts,notices};
}

export function portalProposalProfile(ctx:ProposalProfileContext):PortalProposalProfile{
 const a=ctx.answers||{},answer=(id:string)=>a[id]??'',base={...commonFallback,commercial:[...commonFallback.commercial],nextSteps:[...commonFallback.nextSteps]} as PortalProposalProfile;
 if(ctx.serviceSlug==='assessoria-estrategica')return{
  solutionCopy:ctx.packageCode==='FULL'?'RH estratégico sênior com maior cadência e até duas prioridades simultâneas, sem ampliar a estrutura fixa nem criar expectativa de dedicação integral.':'RH estratégico sênior, em formato fracionado, para organizar uma prioridade central por ciclo, qualificar decisões e criar uma rotina de leitura com a liderança.',
  operating:ctx.packageCode==='FULL'?[`Carga mensal contratada de ${ctx.monthlyHours||'14 a 18'} horas, incluindo encontros, análise, preparação e devolutivas.`,'Encontros quinzenais com founders, diretoria ou liderança de RH.','Até duas prioridades simultâneas, definidas e revistas com a liderança.','Uma visita presencial por mês, com finalidade e agenda previamente definidas, conforme região e condições acordadas.','As horas e entregas do período não são cumulativas.']:[`Carga mensal contratada de ${ctx.monthlyHours||'8 a 12'} horas, incluindo encontros, análise, preparação e devolutivas.`,'Encontro mensal virtual com founders, diretoria ou liderança de RH.','Uma prioridade central por ciclo; as demais necessidades ficam organizadas no roadmap.','Atuação 100% online; visitas presenciais são contratadas separadamente.','As horas e entregas do período não são cumulativas.'],
  commercial:[`Contrato mínimo de ${ctx.minimumMonths} meses, com renovação automática e vigência por prazo indeterminado após o período mínimo.`,'Cancelamento após o prazo mínimo mediante aviso prévio de 30 dias.','Reajuste a cada 12 meses, conforme índice e condições definidos em contrato.','Demandas fora da carga mensal, visitas adicionais e projetos extraordinários são orçados separadamente.','A priorização das frentes é revista com a liderança ao longo do ciclo.'],
  outOfScope:['Folha de pagamento, eSocial, encargos e rotinas contínuas de Departamento Pessoal.','Parecer jurídico trabalhista, defesa ou contencioso.','Operação de recrutamento, abertura de vagas ou busca de candidatos.','Execução sem participação do cliente, acesso aos dados e aprovações necessárias.'],
  advantages:ctx.packageCode==='FULL'?['Até duas prioridades avançam simultaneamente, com encontros quinzenais e decisões registradas a cada ciclo.','A visita mensal possui pauta e resultado definidos, evitando presença sem finalidade ou atuação operacional difusa.','Indicadores, responsáveis e próximos movimentos ficam conectados em um único roadmap de implantação.']:['Uma prioridade central recebe foco até ganhar estrutura, responsáveis e rotina de acompanhamento.','As decisões de pessoas são preparadas com leitura sênior, sem transformar a CALI em RH operacional da empresa.','O roadmap preserva as demais necessidades e define quando cada uma pode entrar sem sobrecarregar o ciclo.'],
  bonus:['Kit de governança de pessoas','Agenda executiva mensal e modelo simples de acompanhamento das prioridades de 90 dias, incluídos sem custo adicional.'],
  nextSteps:[['Aprovação','Confirmação do pacote, horas e mensalidade.'],['Contrato','Formalização das condições e da vigência.'],['Conversa estratégica','Priorização das frentes e dos indicadores.'],['Início do ciclo','Ativação da cadência com a liderança.']],
 };
 if(ctx.serviceSlug==='mentoria-rh'){
  const group=a.modalidade==='grupo',meetings=ctx.packageCode==='AMPLIADO'?5:3;
  return{solutionCopy:ctx.packageCode==='AMPLIADO'?'Um programa completo de cinco encontros para aprofundar competências relacionadas, praticar decisões e acompanhar a aplicação no contexto profissional.':'Um programa completo de três encontros para organizar um objetivo prioritário, trabalhar casos reais e transformar a reflexão em um plano de desenvolvimento aplicável.',operating:[group?`Programa corporativo para ${answer('participantes')||'até 5'} profissionais da mesma empresa.`:'Programa individual, com direcionamento conectado ao objetivo profissional.',`${meetings} encontros, em frequência ${String(answer('frequencia')||'acordada').toLowerCase()}, com ${answer('duracao_sessao')||'60 a 90 minutos'} por encontro.`,`Suporte entre encontros: ${String(answer('suporte')||'conforme o pacote').toLowerCase()}.`,'O investimento é pelo programa completo; não há cobrança ou venda por encontro avulso.',group?'O objetivo do grupo é comum, mas casos individuais são tratados com confidencialidade.':'Casos reais trazidos pela pessoa orientam a aplicação prática dos encontros.'],commercial:[...commonProjectCommercial,'Encontros não realizados não são cumulativos fora do período contratado.','Remarcações devem ser solicitadas com pelo menos 24 horas de antecedência; ausência ou cancelamento fora do prazo contabiliza o encontro.','O programa orienta e desenvolve; decisões e execução permanecem sob responsabilidade do participante e, quando aplicável, da empresa contratante.'],outOfScope:['Garantia de promoção, recolocação, aumento salarial ou resultado dependente de terceiros.','Atendimento clínico, terapêutico ou de saúde mental.','Execução de atividades, projetos ou decisões no lugar do participante.','Avaliação de desempenho formal ou compartilhamento de conteúdo individual sem autorização.'],advantages:['Programa fechado, com começo, desenvolvimento e consolidação — não uma sequência solta de encontros.','Casos reais do participante orientam a prática e tornam o aprendizado aplicável.','Contato direto com Patrícia e plano de desenvolvimento organizado ao final.'],bonus:['Caderno de aplicação CALI','Roteiro de reflexão, registro das decisões e plano de ação pessoal para sustentar o desenvolvimento entre os encontros.'],nextSteps:[['Aprovação','Confirmação do formato, pacote e investimento.'],['Contrato e pagamento','Formalização e reserva da agenda.'],['Leitura inicial','Alinhamento do objetivo e do desafio prioritário.'],['Primeiro encontro','Início do ciclo de desenvolvimento.']]};
 }
 if(ctx.serviceSlug==='diagnostico-executivo')return{solutionCopy:ctx.packageCode==='COMPLETO'?'Uma leitura organizacional mais ampla, apoiada por entrevistas, documentos e indicadores, que transforma sinais dispersos em prioridades e plano de 90 dias.':'Uma leitura executiva de raio curto para esclarecer uma decisão, organizar os riscos prioritários e orientar os primeiros movimentos de gestão de pessoas.',operating:[ctx.packageCode==='COMPLETO'?'Até 6 entrevistas com lideranças-chave; volumes maiores são faseados ou contratados separadamente.':'Até 3 entrevistas com lideranças-chave, concentradas na decisão prioritária.',ctx.packageCode==='COMPLETO'?'Leitura documental e dos indicadores disponíveis, com pesquisa quantitativa somente quando descrita no escopo.':'Leitura dos documentos e indicadores já disponíveis, sem saneamento integral das bases.','Entrevistas remotas ou presenciais, conforme o desenho aprovado.','A profundidade da leitura depende do acesso a documentos, indicadores e pessoas-chave.','Relatório, mapa de prioridades de 90 dias e devolutiva executiva estão incluídos.'],commercial:commonProjectCommercial,outOfScope:['Execução das ações priorizadas após a devolutiva, salvo contratação adicional.','Auditoria contábil, trabalhista, jurídica ou de segurança ocupacional.','Saneamento integral de bases e documentos não previsto no escopo.','Garantia de resultado quando a implementação depende da empresa.'],advantages:['Clareza antes de investir em várias iniciativas ao mesmo tempo.','Riscos, prioridades e plano de 90 dias reunidos em uma leitura executiva única.','Devolutiva conduzida diretamente por Patrícia, com espaço para decisão e dúvidas.'],bonus:['Check-in executivo de 30 dias','Uma conversa de 30 minutos para revisar o avanço das prioridades e ajustar o primeiro movimento do roadmap.'],nextSteps:projectNextSteps};
 if(ctx.serviceSlug==='cultura-direcao')return{solutionCopy:'Um projeto único que lê a cultura atual, traduz a direção desejada em comportamentos observáveis e organiza as prioridades de transformação para os próximos 90 dias.',operating:['O escopo-base contempla uma escuta quantitativa ou amostral, até 4 entrevistas, 1 grupo focal e 1 workshop com a liderança.','O patrocínio visível da alta liderança é condição para mobilização e legitimidade do processo.','Relatos individuais são tratados com confidencialidade e consolidados por padrões.','A entrega inclui leitura da cultura atual, comportamentos desejados, direcionadores e roadmap de 90 dias.','A empresa apoia comunicação, agenda, acesso às pessoas e validação das decisões.'],commercial:commonProjectCommercial,outOfScope:['Criação de peças, campanha interna, design ou produção contínua de comunicação.','Terapia organizacional, mediação jurídica ou investigação disciplinar.','Implementação integral do roadmap após a entrega, salvo contratação específica.','Garantia de mudança cultural sem participação ativa da liderança.'],advantages:['A cultura é lida antes de ser definida, reduzindo decisões baseadas em percepção isolada.','Comportamentos esperados ficam concretos para orientar liderança, rituais e escolhas.','O projeto termina com prioridades e responsáveis, não apenas com um relatório conceitual.'],bonus:['Guia de ritual cultural para lideranças','Modelo simples para conectar os comportamentos definidos às reuniões, decisões e conversas do dia a dia.'],nextSteps:projectNextSteps};
 if(ctx.serviceSlug==='shadowing-lideranca'){
  const format=String(answer('presencial')||'preferencialmente presencial').toLowerCase();
  return{solutionCopy:'Um ciclo individual de observação da liderança em situações reais, seguido de devolutiva franca e plano prático para transformar comportamento em ação.',operating:['O investimento contempla um ciclo individual para uma liderança; outras pessoas recebem ciclos próprios.',`Até ${answer('horas')||'4'} horas de observação, distribuídas em até duas situações reais acordadas.`,format.includes('presencial')?(format.includes('recomendad')?`Formato ${format}, pois preserva a observação direta que dá sentido ao serviço.`:`Formato ${format}, recomendado por preservar a observação direta que dá sentido ao serviço.`):`Formato ${format}, conforme viabilidade e objetivo definidos.`,'As pessoas observadas precisam conhecer o objetivo e consentir com a dinâmica.','A entrega inclui registro técnico, devolutiva individual, três comportamentos prioritários e plano de ação.'],commercial:commonProjectCommercial,outOfScope:['Vigilância oculta, investigação disciplinar ou uso do serviço como mecanismo punitivo.','Avaliação psicológica, diagnóstico clínico ou atendimento terapêutico.','Garantia de mudança comportamental sem adesão da liderança observada.','Gravação de reuniões ou pessoas sem autorização expressa.'],advantages:['A leitura parte do comportamento real, não apenas do relato ou de uma avaliação teórica.','Devolutiva confidencial e objetiva, conectada às situações observadas.','Plano individual com poucos comportamentos prioritários para aumentar a chance de aplicação.'],bonus:['Roteiro para conversas difíceis','Guia prático e personalizado para preparar uma conversa crítica relacionada ao objetivo trabalhado no ciclo.'],nextSteps:[['Aprovação','Confirmação das lideranças, horas e investimento.'],['Contrato','Formalização de confidencialidade e responsabilidades.'],['Alinhamento','Comunicação e consentimento das pessoas envolvidas.'],['Observação','Início do ciclo nas situações combinadas.']]};
 }
 if(ctx.serviceSlug==='treinamentos'){
  const classes=Number(a.turmas||0),meetings=Number(a.encontros||0),classLabel=classes?`${classes} ${classes===1?'turma':'turmas'}`:'Número de turmas acordado',meetingLabel=meetings?`${meetings} ${meetings===1?'encontro':'encontros'}`:'Número de encontros acordado';
  const solution=ctx.packageCode==='PALESTRA'?'Uma palestra estratégica desenhada para o contexto da empresa, com conteúdo objetivo, provocação responsável e conexão prática com o negócio.':ctx.packageCode==='WORKSHOP'?'Uma oficina aplicada, de até quatro horas, para trabalhar uma competência prioritária com exercício, discussão e ferramenta prática.':'Um programa compacto de até três encontros, com conteúdo aplicado, participação ativa e prática conectada aos desafios reais do público.';
  return{solutionCopy:solution,operating:[`${classLabel}, com até ${answer('participantes')||'o limite definido'} participantes por turma.`,`${meetingLabel}, com carga de ${String(answer('carga_horaria')||'duração definida').toLowerCase()} por encontro.`,`Formato ${String(answer('formato')||'definido em proposta').toLowerCase()}.`,'A empresa garante infraestrutura, acesso, pontualidade e comunicação com os participantes.','Gravação, reprodução ou reutilização do conteúdo depende de autorização e licenciamento expressos.','O preço considera carga horária, formato, localidade, número de turmas, participantes, personalização e materiais previstos.'],commercial:['A proposta é válida pelo prazo indicado neste documento.','O pagamento deve ser concluído conforme a condição acordada antes da realização.','Cancelamento até 15 dias antes do início permite reembolso de 50%; após esse prazo, não há reembolso.','Remarcações devem ser solicitadas com pelo menos 10 dias de antecedência; prazos menores podem gerar taxa.','Deslocamento, hospedagem, materiais físicos e licenciamento de gravação só estão incluídos quando descritos.','O conteúdo e os materiais CALI são protegidos por direitos autorais.'],outOfScope:['Gravação, distribuição ou reprodução do conteúdo sem autorização expressa.','Infraestrutura, plataforma, sala, equipamentos ou tradução não descritos.','Atendimento clínico ou aconselhamento individual de participantes.','Mudança de tema, público ou formato após aprovação sem revisão de escopo.'],advantages:['Conteúdo construído a partir da realidade da empresa, sem material genérico de prateleira.','Facilitação conduzida ao vivo por Patrícia, com experiência executiva em RH.','Formato escolhido pela mudança esperada — palestra, workshop ou treinamento — e não apenas pela duração.'],bonus:['Plano de aplicação pós-encontro','Uma página para o sponsor orientar a aplicação do conteúdo e acompanhar os primeiros compromissos do público.'],nextSteps:[['Aprovação','Confirmação do formato, data e investimento.'],['Contrato e pagamento','Formalização e reserva da agenda.'],['Reunião de briefing','Aprofundamento do contexto e do público.'],['Realização','Facilitação conforme o desenho aprovado.']]};
 }
 if(ctx.serviceSlug==='marca-empregadora')return{solutionCopy:ctx.packageCode==='RECORRENTE'?'Uma sustentação consultiva para revisar prioridades, orientar a ativação e acompanhar indicadores, sem assumir a produção criativa ou a operação dos canais.':'Um projeto estratégico para diagnosticar a percepção atual, definir ou refinar o EVP e organizar um plano de ativação viável para RH, Marketing e liderança.',operating:[ctx.packageCode==='RECORRENTE'?'Atuação recorrente com prioridades e calendário revistos em ciclos mensais.':'Projeto organizado nas fases de diagnóstico, estratégia e ativação.','RH, Marketing, Comunicação e liderança participam das validações previstas no escopo.','A empresa fornece pesquisas, guias de marca, acessos, dados e aprovações nos prazos combinados.','RH, Marketing, Comunicação ou parceiros executam as peças e campanhas a partir do direcionamento aprovado.','Os indicadores partem de uma linha de base e dependem da disponibilidade e qualidade dos dados.'],commercial:[...commonProjectCommercial,...(ctx.packageCode==='RECORRENTE'?['A mensalidade cobre as frentes e a capacidade previstas; demandas extraordinárias são orçadas separadamente.']:[])],outOfScope:['Design, produção gráfica ou audiovisual, redação contínua de peças e identidade visual.','Compra de mídia, impulsionamento, gestão de campanhas pagas ou contratação de fornecedores.','Gestão operacional de redes sociais, site de carreiras, vagas ou calendário de publicações.','Rebranding corporativo integral ou redesign da marca institucional.','Garantia de volume de candidatos, redução de turnover ou reputação sem execução conjunta da empresa.'],advantages:['A estratégia conecta percepção interna, atração e experiência — não apenas comunicação externa.','EVP, personas, canais, roadmap e indicadores ficam organizados para orientar a execução.','O escopo conversa com Marketing ou agência sem duplicar o trabalho criativo dessas áreas.'],bonus:['Matriz editável de ativação e KPIs','Modelo para organizar iniciativa, responsável, canal, prazo e indicador de cada movimento da marca empregadora.'],nextSteps:projectNextSteps};
 if(ctx.serviceSlug==='solucao-personalizada')return{solutionCopy:'Uma solução desenhada a partir do contexto real da empresa, combinando leitura estratégica, estruturação e desenvolvimento sem forçar a necessidade em um pacote pronto.',operating:['O formato, a duração e a cadência são definidos conforme a natureza e a complexidade da necessidade.','A empresa disponibiliza as pessoas, os dados, os acessos e as aprovações necessários ao trabalho.','Entregas, limites e responsabilidades são descritos expressamente na proposta e no contrato.','Mudanças relevantes de escopo, volume ou formato são avaliadas antes da execução.','Etapas presenciais, fornecedores, licenças e deslocamentos só estão incluídos quando descritos.'],commercial:commonProjectCommercial,outOfScope:['Folha de pagamento, ponto, benefícios, admissões, férias, desligamentos, eSocial ou outras rotinas de Departamento Pessoal.','Operação contínua de recrutamento, hunting em volume, abertura de vagas ou alocação de recrutadores.','Serviços jurídicos, contábeis, médicos, clínicos ou outras atividades técnicas reguladas.','Terceirização de rotinas administrativas ou execução transacional contínua do RH.'],advantages:['O desafio não é forçado em um pacote genérico: objetivo, entregas e limites são confirmados antes do início.','Checkpoints evitam que uma necessidade personalizada se transforme em escopo aberto.','Condução direta por Patrícia e conexão com as prioridades reais do negócio.'],bonus:['Check-in executivo de 30 dias','Uma conversa breve para revisar a aplicação da entrega principal e orientar o próximo movimento.'],nextSteps:[['Conversa de confirmação','Validação do desafio, do resultado esperado e das premissas principais.'],['Desenho do escopo','Definição das entregas, do formato, do cronograma e do investimento.'],['Contrato','Formalização das condições e responsabilidades.'],['Kickoff','Organização dos insumos, das agendas e do primeiro movimento.']]};
 return base;
}
