type Answers=Record<string,any>;
type Step=[string,string];
export type ProposalAlert={level:'high'|'medium'|'low'|'info'|'attention';text:string};
export type ProposalProfile={solutionCopy:string;operating:string[];commercial:string[];outOfScope:string[];advantages:string[];bonus:[string,string];nextSteps:Step[];contextIds:string[];priorityIds:string[];contextLabels:Record<string,string>};

const commonProjectCommercial=[
  'A proposta é válida pelo prazo indicado neste documento.',
  'O início está condicionado à assinatura do contrato e ao cumprimento da condição de pagamento acordada.',
  'Custos de deslocamento, hospedagem, licenças ou fornecedores só são incluídos quando descritos expressamente.',
  'Materiais, métodos e modelos CALI permanecem protegidos por direitos autorais e não podem ser reproduzidos fora do uso contratado.',
];
const projectNextSteps:Step[]=[
  ['Aprovação','Confirmação do investimento, formato e escopo.'],
  ['Contrato','Formalização das condições e responsabilidades.'],
  ['Kickoff','Alinhamento final e organização dos insumos.'],
  ['Início','Execução conforme o cronograma acordado.'],
];
const labels:Record<string,Record<string,string>>={
  frequencia:{mensal:'Mensal',quinzenal:'Quinzenal',semanal:'Semanal'},duracao_sessao:{'60':'60 minutos','90':'90 minutos'},
  suporte:{essencial:'Sem suporte por mensagem',mensagens:'Dúvidas pontuais por mensagem',proximo:'Check-ins e discussão de casos'},
  presencial:{presencial:'Presencial, recomendado',hibrido:'Híbrido',remoto:'Remoto',nao:'Sem necessidade fixa',eventual:'Eventual, quando necessário',mensal:'Uma visita por mês',mais:'Mais de uma visita por mês'},
  formato:{online:'Remoto (Google Meet)',presencial:'Presencial',hibrido:'Híbrido'},carga_horaria:{'1':'60 min','1.5':'90 min','2':'2 horas','3':'3 horas','4':'4 horas','8':'Dia inteiro',recomendar:'duração a recomendar'},
  tipo_contratacao:{palestra:'Palestra Estratégica',campanha:'Palestra para campanha ou data do calendário',palestra_tema:'Palestra sobre tema específico',workshop:'Workshop Aplicado',treinamento:'Treinamento Personalizado',programa_lideranca:'Programa / trilha de liderança',recomendar:'Formato a recomendar'},
  campanha_vinculada:{sim:'Sim',nao:'Não'},
  recorrencia_esperada:{unica:'Uma ação única','2a3':'Dois ou três encontros','4mais':'Quatro ou mais encontros',nao_sei:'Ainda não sei'},
  campanha_calendario:{janeiro_branco:'Janeiro Branco',kickoff:'Kickoff / início do ano',dia_mulher:'Dia da Mulher',abril_verde_sipat:'Abril Verde / SIPAT',dia_trabalho:'Dia do Trabalho',dia_maes:'Dia das Mães',orgulho_lgbtqia:'Mês do Orgulho LGBTQIA+',agosto_lilas:'Agosto Lilás',dia_pais:'Dia dos Pais',setembro_amarelo:'Setembro Amarelo',outubro_rosa:'Outubro Rosa',dia_criancas:'Dia das Crianças',novembro_azul:'Novembro Azul',consciencia_negra:'Consciência Negra',black_friday:'Black Friday / alta temporada',fechamento_ano:'Fechamento de ano / Natal',outro:'Outra campanha ou data'},
  publico:{empresa:'Toda a empresa',liderancas:'Lideranças',diretoria:'Diretoria ou C-level',rh:'Time de RH',operacional:'Equipe operacional',especialistas:'Especialistas ou técnicos',area:'Uma área específica',misto:'Público misto'},
  nivel_interacao:{expositivo:'Conteúdo expositivo, sem dinâmica',perguntas:'Conteúdo + perguntas ao final',interacao:'Interação ao longo da fala',dinamica:'Exercícios ou dinâmica prática',recomendar:'Interação a recomendar'},
  participantes:{},colaboradores:{},unidades:{},horas:{},modelo_interesse:{PARTNER:'CALI PARTNER',FULL:'CALI FULL',RECOMENDAR:'Quero que a CALI recomende'},
  rh_interno:{nao:'Não',operacional:'Sim, predominantemente operacional',estruturado:'Sim, já estruturado'},lideranca_rh:{nao:'Não',parcial:'Parcial ou acumulada por outra área',sim:'Sim'},
  estrutura_rh_status:{nao_existe:'Ainda não existe uma área formal de RH',em_criacao:'A área está sendo criada agora',pouco_estruturado:'Existe, mas ainda é pouco estruturada',parcial:'Existe e alguns subsistemas já funcionam',estruturado:'Existe e é estruturada, mas uma frente precisa ser construída ou revista'},
  responsavel_senioridade:{assistente:'Assistente / estágio',junior:'Júnior',pleno:'Pleno',senior:'Sênior',especialista:'Especialista',coordenacao:'Coordenação',gerencia:'Gerência',direcao:'Direção / CHRO',outro:'Outro'},
  escopo_build:{rh_completo:'RH como um todo',frente_especifica:'Uma frente específica',multiplas_frentes:'Várias frentes relacionadas',recomendar:'Quero que a CALI recomende'},
  capacidade_execucao:{menos2:'Menos de 2 horas por semana','2a4':'De 2 a 4 horas por semana','5a8':'De 5 a 8 horas por semana','9mais':'9 horas ou mais por semana'},
  cadencia_build:{semanal:'Semanal',quinzenal:'Quinzenal',mensal:'Mensal',recomendar:'A recomendar'},
  frentes:{planejamento:'Planejamento estratégico de pessoas',desenho:'Estrutura e desenho organizacional',governanca:'Governança, políticas e processos',people_analytics:'Indicadores, People Analytics e dashboards',desempenho:'Gestão de desempenho e metas',clima:'Clima e engajamento',cultura:'Cultura e valores',cargos:'Cargos, carreira e salários',sucessao:'Sucessão e gestão de talentos',liderancas:'Desenvolvimento de lideranças',atracao:'Atração, seleção e onboarding',marca:'Marca empregadora e experiência do colaborador',comunicacao:'Comunicação interna',saude:'Saúde, segurança e conformidade',diversidade:'Diversidade, equidade e inclusão'},
};
function answerText(answers:Answers,id:string){const v=answers[id];if(v===undefined||v===null||v==='')return'';if(Array.isArray(v))return v.map(x=>labels[id]?.[String(x)]||String(x)).join(', ');return labels[id]?.[String(v)]||String(v);}
const trainingRmcCities=['adrianopolis','agudos do sul','almirante tamandare','araucaria','balsa nova','bocaiuva do sul','campina grande do sul','campo do tenente','campo largo','campo magro','cerro azul','colombo','contenda','curitiba','doutor ulysses','fazenda rio grande','itaperucu','lapa','mandirituba','pien','pinhais','piraquara','quatro barras','quitandinha','rio branco do sul','rio negro','sao jose dos pinhais','tijucas do sul','tunas do parana'];
const normalizeTrainingLocation=(v:any)=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLowerCase().replace(/\s+/g,' ');
export function trainingNeedsTravel(answers:Answers={}){
  if(!['presencial','hibrido'].includes(String(answers.formato||'')))return false;
  if(Boolean(answers.deslocamento_necessario))return true;
  const state=String(answers.local_estado||'').trim().toUpperCase(),city=normalizeTrainingLocation(answers.local_cidade||'');
  if(state||city)return !(state==='PR'&&trainingRmcCities.includes(city));
  const legacy=normalizeTrainingLocation(answers.local_execucao||'');
  if(!legacy)return false;
  return !legacy.includes('curitiba');
}
function concreteAdvantages(profileAdvantages:string[]){return[
  'Mais de 15 anos de experiência em Recursos Humanos e atuação em mais de 110 empresas, aplicados à leitura de riscos, dependências e prioridades deste contexto.',
  'Condução direta por Patrícia Lima, com repertório de diretoria e CHRO, sem repasses ou camadas intermediárias.',
  profileAdvantages[0]||'Método conectado ao negócio, com decisões, responsáveis e próximos movimentos claramente organizados.',
];}

export function getProposalProfile(serviceSlug:string,packageCode:string,answers:Answers,minimumMonths=1,monthlyHours=0):ProposalProfile{
  if(serviceSlug==='assessoria-estrategica'){
    const full=packageCode==='FULL';const profileAdvantages=full?[
      'Até duas prioridades avançam simultaneamente, com encontros quinzenais e decisões registradas a cada ciclo.',
      'A visita mensal possui pauta e resultado definidos, evitando presença sem finalidade ou atuação operacional difusa.',
      'Indicadores, responsáveis e próximos movimentos ficam conectados em um único roadmap de implantação.',
    ]:[
      'Uma prioridade central recebe foco até ganhar estrutura, responsáveis e rotina de acompanhamento.',
      'As decisões de pessoas são preparadas com leitura sênior, sem transformar a CALI em RH operacional da empresa.',
      'O roadmap preserva as demais necessidades e define quando cada uma pode entrar sem sobrecarregar o ciclo.',
    ];
    return{solutionCopy:full?'RH estratégico sênior com maior cadência e até duas prioridades simultâneas, sem ampliar a estrutura fixa nem criar expectativa de dedicação integral.':'RH estratégico sênior, em formato fracionado, para organizar uma prioridade central por ciclo, qualificar decisões e criar uma rotina de leitura com a liderança.',operating:full?[
      `Carga mensal contratada de ${monthlyHours||'14 a 18'} horas, incluindo encontros, análise, preparação e devolutivas.`,
      'Encontros quinzenais com founders, diretoria ou liderança de RH.','Até duas prioridades simultâneas, definidas e revistas com a liderança.','Uma visita presencial por mês, com finalidade e agenda previamente definidas, conforme região e condições acordadas.','As horas e entregas do período não são cumulativas.',
    ]:[
      `Carga mensal contratada de ${monthlyHours||'8 a 12'} horas, incluindo encontros, análise, preparação e devolutivas.`,
      'Encontro mensal virtual com founders, diretoria ou liderança de RH.','Uma prioridade central por ciclo; as demais necessidades ficam organizadas no roadmap.','Atuação 100% online; visitas presenciais são contratadas separadamente.','As horas e entregas do período não são cumulativas.',
    ],commercial:[`Contrato mínimo de ${minimumMonths} meses, com renovação automática e vigência por prazo indeterminado após o período mínimo.`,'Cancelamento após o prazo mínimo mediante aviso prévio de 30 dias.','Reajuste a cada 12 meses, conforme índice e condições definidos em contrato.','Demandas fora da carga mensal, visitas adicionais e projetos extraordinários são orçados separadamente.','A priorização das frentes é revista com a liderança ao longo do ciclo.'],outOfScope:['Folha de pagamento, eSocial, encargos e rotinas contínuas de Departamento Pessoal.','Parecer jurídico trabalhista, defesa ou contencioso.','Operação de recrutamento, abertura de vagas ou busca de candidatos.','Execução sem participação do cliente, acesso aos dados e aprovações necessárias.'],advantages:concreteAdvantages(profileAdvantages),bonus:['Kit de governança de pessoas','Agenda executiva mensal e modelo simples de acompanhamento das prioridades de 90 dias, incluídos sem custo adicional.'],nextSteps:[['Aprovação','Confirmação do pacote, horas e mensalidade.'],['Contrato','Formalização das condições e da vigência.'],['Conversa estratégica','Priorização das frentes e dos indicadores.'],['Início do ciclo','Ativação da cadência com a liderança.']],contextIds:['momento_empresa','colaboradores','rh_interno','lideranca_rh','modelo_interesse','frequencia','presencial','prazo_inicio'],priorityIds:['principal_desafio','frentes'],contextLabels:{momento_empresa:'Momento da empresa',colaboradores:'Número de colaboradores',rh_interno:'Estrutura atual de RH',lideranca_rh:'Liderança sênior de RH',modelo_interesse:'Modelo de assessoria',frequencia:'Cadência esperada',presencial:'Atuação presencial',prazo_inicio:'Início desejado'}};
  }
  if(serviceSlug==='cali-build'){
    const complete=packageCode==='COMPLETO';
    const profileAdvantages=complete?[
      'Arquitetura, roadmap e critérios de qualidade ficam conectados em uma única sequência de implantação.',
      'A equipe interna aprende enquanto constrói, reduzindo dependência externa ao final do trabalho.',
      'Checkpoints executivos aceleram decisões e evitam que aprovações virem gargalos entre as frentes.',
    ]:[
      'Uma frente recebe foco até ganhar método, documentação, responsáveis e rotina de sustentação.',
      'A equipe interna desenvolve capacidade prática sem perder a segurança de uma revisão sênior.',
      'O roadmap impede que a urgência de várias demandas desorganize o primeiro ciclo.',
    ];
    return{
      solutionCopy:complete?'Estruturação assistida de uma agenda mais ampla de RH, organizada em ciclos conectados, com maior cadência de supervisão técnica e checkpoints executivos.':'Estruturação assistida de uma frente prioritária por ciclo: a CALI desenha o método, define critérios e revisa tecnicamente; o RH interno executa e implanta.',
      operating:complete?[
        'Carga mensal contratada de '+(monthlyHours||'14 a 18')+' horas, incluindo análise, preparação, checkpoints, revisão técnica e devolutivas.',
        'Várias frentes relacionadas podem avançar em sequência ou, quando viável, de forma coordenada dentro do ciclo.',
        'Checkpoints semanais ou quinzenais são definidos conforme fase e capacidade real de implantação.',
        'Checkpoint executivo com a liderança responsável ou diretoria nos marcos que exigem decisão, aprovação ou remoção de impedimentos.',
        'Atuação 100% online por padrão; presença física é adicional e só entra quando contratada.',
      ]:[
        'Carga mensal contratada de '+(monthlyHours||'8 a 12')+' horas, incluindo análise, preparação, checkpoints, revisão técnica e devolutivas.',
        'Uma frente prioritária por ciclo; as demais necessidades permanecem organizadas no roadmap.',
        'Checkpoints quinzenais ou mensais, ajustados ao ritmo de execução do responsável interno.',
        'A CALI revisa e corrige as entregas produzidas internamente antes dos principais marcos de implantação.',
        'Atuação 100% online por padrão; presença física é adicional e só entra quando contratada.',
      ],
      commercial:[
        'Contrato mínimo de '+minimumMonths+' meses, com implantação organizada em ciclos e revisão de prioridades a cada marco.',
        'A mensalidade remunera a capacidade técnica reservada no período; horas e entregas não são cumulativas.',
        'Após o período mínimo, novos ciclos podem ser prorrogados conforme o roadmap e o estágio de implantação.',
        'Visitas presenciais e deslocamentos são contratados separadamente. Passagens, hospedagem, alimentação e demais despesas são pagas antecipadamente pela contratante, sem reembolso posterior.',
        'Mudanças relevantes de escopo, número de frentes ou necessidade de execução pela CALI exigem reenquadramento comercial.',
      ],
      outOfScope:[
        'Executar a implantação no lugar do RH interno. Quando a CALI assume a execução, o enquadramento passa a ser CALI Full.',
        'Folha de pagamento, eSocial, admissões, férias, benefícios, ponto e demais rotinas contínuas de Departamento Pessoal.',
        'Parecer jurídico trabalhista, defesa, contencioso ou validação legal regulada.',
        'Operação contínua de recrutamento, abertura de vagas, hunting ou alocação de recrutadores.',
      ],
      advantages:concreteAdvantages(profileAdvantages),
      bonus:['Checklist de sustentação do ciclo','Material de fechamento para registrar responsáveis, indicadores, rotinas de manutenção e próximos marcos após a implantação.'],
      nextSteps:[['Aprovação','Confirmação do modelo, carga mensal, prazo mínimo e primeira frente ou sequência de frentes.'],['Contrato','Formalização das responsabilidades da CALI, do RH interno e da liderança responsável.'],['Kickoff','Organização dos insumos, responsáveis, critérios e agenda do primeiro ciclo.'],['Primeiro ciclo','Início da construção assistida com execução interna e checkpoints CALI.']],
      contextIds:['momento_empresa','colaboradores','estrutura_rh_status','pessoas_rh','escopo_build','capacidade_execucao','cadencia_build','prazo_inicio'],
      priorityIds:['objetivo_primeiro_ciclo','frentes'],
      contextLabels:{momento_empresa:'Momento da empresa',colaboradores:'Número de colaboradores',estrutura_rh_status:'Estrutura atual do RH',pessoas_rh:'Pessoas no RH',escopo_build:'Amplitude da estruturação',capacidade_execucao:'Capacidade interna semanal',cadencia_build:'Cadência dos checkpoints',prazo_inicio:'Início desejado'},
    };
  }
  if(serviceSlug==='mentoria-rh'){
    const group=answers.modalidade==='grupo',meetings=packageCode==='AMPLIADO'?5:3;const profileAdvantages=['Programa fechado, com começo, desenvolvimento e consolidação — não uma sequência solta de encontros.','Casos reais do participante orientam a prática e tornam o aprendizado aplicável.','Contato direto com Patrícia e plano de desenvolvimento organizado ao final.'];
    return{solutionCopy:packageCode==='AMPLIADO'?'Um programa completo de cinco encontros para aprofundar competências relacionadas, praticar decisões e acompanhar a aplicação no contexto profissional.':'Um programa completo de três encontros para organizar um objetivo prioritário, trabalhar casos reais e transformar a reflexão em um plano de desenvolvimento aplicável.',operating:[group?`Programa corporativo para ${answerText(answers,'participantes')||'até 5'} profissionais da mesma empresa.`:'Programa individual, com direcionamento conectado ao objetivo profissional.',`${meetings} encontros, em frequência ${String(answerText(answers,'frequencia')||'acordada').toLowerCase()}, com ${answerText(answers,'duracao_sessao')||'60 a 90 minutos'} por encontro.`,`Suporte entre encontros: ${String(answerText(answers,'suporte')||'conforme o pacote').toLowerCase()}.`,'O investimento é pelo programa completo; não há cobrança ou venda por encontro avulso.',group?'O objetivo do grupo é comum, mas casos individuais são tratados com confidencialidade.':'Casos reais trazidos pela pessoa orientam a aplicação prática dos encontros.'],commercial:[...commonProjectCommercial,'Encontros não realizados não são cumulativos fora do período contratado.','Remarcações devem ser solicitadas com pelo menos 24 horas de antecedência; ausência ou cancelamento fora do prazo contabiliza o encontro.','O programa orienta e desenvolve; decisões e execução permanecem sob responsabilidade do participante e, quando aplicável, da empresa contratante.'],outOfScope:['Garantia de promoção, recolocação, aumento salarial ou resultado dependente de terceiros.','Atendimento clínico, terapêutico ou de saúde mental.','Execução de atividades, projetos ou decisões no lugar do participante.','Avaliação de desempenho formal ou compartilhamento de conteúdo individual sem autorização.'],advantages:concreteAdvantages(profileAdvantages),bonus:['Caderno de aplicação CALI','Roteiro de reflexão, registro das decisões e plano de ação pessoal para sustentar o desenvolvimento entre os encontros.'],nextSteps:[['Aprovação','Confirmação do formato, pacote e investimento.'],['Contrato e pagamento','Formalização e reserva da agenda.'],['Leitura inicial','Alinhamento do objetivo e do desafio prioritário.'],['Primeiro encontro','Início do ciclo de desenvolvimento.']],contextIds:['modalidade','cargo_atual','tempo_rh','momento','participantes','frequencia','duracao_sessao','suporte'],priorityIds:['caso_real','objetivos','objetivo_grupo'],contextLabels:{modalidade:'Formato da contratação',cargo_atual:'Público participante',tempo_rh:'Experiência em RH',momento:'Momento profissional',participantes:'Número de participantes',frequencia:'Cadência dos encontros',duracao_sessao:'Duração por encontro',suporte:'Suporte entre encontros'}};
  }
  if(serviceSlug==='diagnostico-executivo'){
    const complete=packageCode==='COMPLETO',profileAdvantages=['Clareza antes de investir em várias iniciativas ao mesmo tempo.','Riscos, prioridades e plano de 90 dias reunidos em uma leitura executiva única.','Devolutiva conduzida diretamente por Patrícia, com espaço para decisão e dúvidas.'];
    return{solutionCopy:complete?'Uma leitura organizacional mais ampla, apoiada por entrevistas, documentos e indicadores, que transforma sinais dispersos em prioridades e plano de 90 dias.':'Uma leitura executiva de raio curto para esclarecer uma decisão, organizar os riscos prioritários e orientar os primeiros movimentos de gestão de pessoas.',operating:[complete?'Até 6 entrevistas com lideranças-chave; volumes maiores são faseados ou contratados separadamente.':'Até 3 entrevistas com lideranças-chave, concentradas na decisão prioritária.',complete?'Leitura documental e dos indicadores disponíveis, com pesquisa quantitativa somente quando descrita no escopo.':'Leitura dos documentos e indicadores já disponíveis, sem saneamento integral das bases.','Entrevistas remotas ou presenciais, conforme o desenho aprovado.','A profundidade da leitura depende do acesso a documentos, indicadores e pessoas-chave.','Relatório, mapa de prioridades de 90 dias e devolutiva executiva estão incluídos.'],commercial:commonProjectCommercial,outOfScope:['Execução das ações priorizadas após a devolutiva, salvo contratação adicional.','Auditoria contábil, trabalhista, jurídica ou de segurança ocupacional.','Saneamento integral de bases e documentos não previsto no escopo.','Garantia de resultado quando a implementação depende da empresa.'],advantages:concreteAdvantages(profileAdvantages),bonus:['Check-in executivo de 30 dias','Uma conversa de 30 minutos para revisar o avanço das prioridades e ajustar o primeiro movimento do roadmap.'],nextSteps:projectNextSteps,contextIds:['momento_empresa','colaboradores','unidades','pessoas_rh','documentos','indicadores_disponiveis','entrevistas','survey'],priorityIds:['situacao_critica','problemas','uso_resultado'],contextLabels:{momento_empresa:'Momento da empresa',colaboradores:'Número de colaboradores',unidades:'Unidades ou filiais',pessoas_rh:'Estrutura interna de RH',documentos:'Documentação disponível',indicadores_disponiveis:'Indicadores disponíveis',entrevistas:'Entrevistas previstas',survey:'Pesquisa quantitativa'}};
  }
  if(serviceSlug==='cultura-direcao'){
    const profileAdvantages=['A cultura é lida antes de ser definida, reduzindo decisões baseadas em percepção isolada.','Comportamentos esperados ficam concretos para orientar liderança, rituais e escolhas.','O projeto termina com prioridades e responsáveis, não apenas com um relatório conceitual.'];
    return{solutionCopy:'Um projeto único que lê a cultura atual, traduz a direção desejada em comportamentos observáveis e organiza as prioridades de transformação para os próximos 90 dias.',operating:['O escopo-base contempla uma escuta quantitativa ou amostral, até 4 entrevistas, 1 grupo focal e 1 workshop com a liderança.','O patrocínio visível da alta liderança é condição para mobilização e legitimidade do processo.','Relatos individuais são tratados com confidencialidade e consolidados por padrões.','A entrega inclui leitura da cultura atual, comportamentos desejados, direcionadores e roadmap de 90 dias.','A empresa apoia comunicação, agenda, acesso às pessoas e validação das decisões.'],commercial:commonProjectCommercial,outOfScope:['Criação de peças, campanha interna, design ou produção contínua de comunicação.','Terapia organizacional, mediação jurídica ou investigação disciplinar.','Implementação integral do roadmap após a entrega, salvo contratação específica.','Garantia de mudança cultural sem participação ativa da liderança.'],advantages:concreteAdvantages(profileAdvantages),bonus:['Guia de ritual cultural para lideranças','Modelo simples para conectar os comportamentos definidos às reuniões, decisões e conversas do dia a dia.'],nextSteps:projectNextSteps,contextIds:['momento_empresa','colaboradores','unidades','palavra_atual','palavra_desejada','pesquisa','entrevistas','patrocinio_lideranca'],priorityIds:['principal_gap','contexto','sensibilidades'],contextLabels:{momento_empresa:'Momento da empresa',colaboradores:'Número de colaboradores',unidades:'Unidades ou filiais',palavra_atual:'Cultura percebida hoje',palavra_desejada:'Cultura desejada',pesquisa:'Abrangência da pesquisa',entrevistas:'Entrevistas previstas',patrocinio_lideranca:'Patrocínio da liderança'}};
  }
  if(serviceSlug==='shadowing-lideranca'){
    const profileAdvantages=['A leitura parte do comportamento real, não apenas do relato ou de uma avaliação teórica.','Devolutiva confidencial e objetiva, conectada às situações observadas.','Plano individual com poucos comportamentos prioritários para aumentar a chance de aplicação.'];const format=String(answerText(answers,'presencial')||'preferencialmente presencial').toLowerCase();
    return{solutionCopy:'Um ciclo individual de observação da liderança em situações reais, seguido de devolutiva franca e plano prático para transformar comportamento em ação.',operating:['O investimento contempla um ciclo individual para uma liderança; outras pessoas recebem ciclos próprios.',`Até ${answerText(answers,'horas')||'4'} horas de observação, distribuídas em até duas situações reais acordadas.`,format.includes('presencial')?(format.includes('recomendad')?`Formato ${format}, pois preserva a observação direta que dá sentido ao serviço.`:`Formato ${format}, recomendado por preservar a observação direta que dá sentido ao serviço.`):`Formato ${format}, conforme viabilidade e objetivo definidos.`,'As pessoas observadas precisam conhecer o objetivo e consentir com a dinâmica.','A entrega inclui registro técnico, devolutiva individual, três comportamentos prioritários e plano de ação.'],commercial:commonProjectCommercial,outOfScope:['Vigilância oculta, investigação disciplinar ou uso do serviço como mecanismo punitivo.','Avaliação psicológica, diagnóstico clínico ou atendimento terapêutico.','Garantia de mudança comportamental sem adesão da liderança observada.','Gravação de reuniões ou pessoas sem autorização expressa.'],advantages:concreteAdvantages(profileAdvantages),bonus:['Roteiro para conversas difíceis','Guia prático e personalizado para preparar uma conversa crítica relacionada ao objetivo trabalhado no ciclo.'],nextSteps:[['Aprovação','Confirmação das lideranças, horas e investimento.'],['Contrato','Formalização de confidencialidade e responsabilidades.'],['Alinhamento','Comunicação e consentimento das pessoas envolvidas.'],['Observação','Início do ciclo nas situações combinadas.']],contextIds:['lideres','nivel','situacoes','horas','presencial','devolutiva','feedback_360','ciencia_lideres'],priorityIds:['objetivo','contexto_observacao','confidencialidade'],contextLabels:{lideres:'Lideranças participantes',nivel:'Nível das lideranças',situacoes:'Situações observadas',horas:'Horas por liderança',presencial:'Formato da observação',devolutiva:'Formato da devolutiva',feedback_360:'Integração com feedback 360',ciencia_lideres:'Ciência das lideranças'}};
  }
  if(serviceSlug==='treinamentos'){
    const profileAdvantages=['Conteúdo customizado a partir do briefing, do público e do contexto real da ação.','Condução direta por Patrícia Lima, conectando repertório executivo de RH a exemplos e situações aplicáveis ao público.','Duração, interação e dinâmica desenhadas para o formato contratado, sem prometer uma profundidade incompatível com o tempo disponível.'];
    const grouped=packageCode==='TREINAMENTO'||packageCode==='PROGRAMA',classCount=Number(answers.turmas||0),meetingCount=Number(answers.encontros||0),participantCount=answerText(answers,'participantes')||'o público definido',classes=classCount?`${classCount} ${classCount===1?'grupo/turma':'grupos/turmas'}`:'Quantidade de grupos acordada',meetings=meetingCount?`${meetingCount} ${meetingCount===1?'encontro':'encontros'}`:'Número de encontros acordado',location=answers.local_execucao?` em ${answers.local_execucao}`:'';
    const solutionCopy=packageCode==='PALESTRA'?'Uma palestra estratégica desenhada para o contexto da empresa, com duração de 60 ou 90 minutos, conteúdo objetivo e interação compatível com o tempo disponível.':packageCode==='WORKSHOP'?'Uma oficina aplicada, de 2 a 4 horas, para trabalhar uma competência prioritária com exercício, discussão e ferramenta prática.':packageCode==='PROGRAMA'?'Uma trilha estruturada de 4 a 10 encontros para desenvolvimento de lideranças, com prática entre etapas, evolução acompanhada e conexão com desafios reais de gestão.':'Um treinamento personalizado em 2 ou 3 encontros, com conteúdo aplicado, participação ativa e prática conectada aos desafios reais do público.';
    const audienceLine=grouped?`${classes}, com até ${participantCount} participantes por grupo/turma.`:`Público estimado de ${participantCount} participantes.`;
    const meetingsLine=grouped?`${meetings}, com duração de ${String(answerText(answers,'carga_horaria')||'duração definida').toLowerCase()} por encontro.`:`Encontro único, com duração de ${String(answerText(answers,'carga_horaria')||'duração definida').toLowerCase()}.`;
    return{solutionCopy,operating:[audienceLine,meetingsLine,`Formato ${String(answerText(answers,'formato')||'definido em proposta').toLowerCase()}${location}.`,`Participação do público: ${String(answerText(answers,'nivel_interacao')||'nível de interação definido no briefing').toLowerCase()}.`,'A empresa garante infraestrutura, acesso, pontualidade e comunicação com os participantes.',answers.formato==='online'?'Realização via Google Meet, com gravação e transcrição da sessão mediante ciência dos participantes.':'A realização presencial considera o endereço informado e a infraestrutura disponibilizada pela empresa.','O preço considera duração, nível de interação, formato, localidade, público, personalização, materiais e, quando aplicável, número de encontros e grupos.'],commercial:['A proposta é válida pelo prazo indicado neste documento.','O pagamento deve ser concluído conforme a condição acordada antes da realização.','Cancelamento até 15 dias antes do início permite reembolso de 50%; após esse prazo, não há reembolso.','Remarcações devem ser solicitadas com pelo menos 10 dias de antecedência; prazos menores podem gerar taxa.','Em realizações fora de Curitiba e Região Metropolitana, passagens, hospedagem, alimentação e deslocamentos locais são de responsabilidade da contratante e não integram o valor do serviço.','O conteúdo e os materiais CALI são protegidos por direitos autorais e não podem ser reproduzidos ou reutilizados fora da finalidade contratada.'],outOfScope:['Distribuição, publicação ou reutilização dos materiais e da gravação fora da finalidade contratada.','Infraestrutura, plataforma, sala, equipamentos ou tradução não descritos.','Atendimento clínico ou aconselhamento individual de participantes.','Mudança de tema, público ou formato após aprovação sem revisão de escopo.'],advantages:profileAdvantages,bonus:['Plano de aplicação pós-encontro','Uma página para o sponsor orientar a aplicação do conteúdo e acompanhar os primeiros compromissos do público.'],nextSteps:[['Aprovação','Confirmação do formato, data e investimento.'],['Contrato e pagamento','Formalização e reserva da agenda.'],['Reunião de briefing','Aprofundamento do contexto e do público.'],['Realização','Facilitação conforme o desenho aprovado.']],contextIds:['tipo_contratacao','campanha_calendario','recorrencia_esperada','tema','publico','participantes','formato','nivel_interacao','encontros','carga_horaria','data_desejada'],priorityIds:['objetivo','contexto','acessibilidade'],contextLabels:{tipo_contratacao:'Tipo de contratação',campanha_calendario:'Campanha ou data',recorrencia_esperada:'Recorrência esperada',tema:'Tema principal',publico:'Público participante',participantes:'Participantes estimados',formato:'Formato da realização',nivel_interacao:'Nível de interação',encontros:'Número de encontros',carga_horaria:'Duração por encontro',data_desejada:'Data ou período desejado'}};
  }
  if(serviceSlug==='marca-empregadora'){
    const recurring=packageCode==='RECORRENTE',profileAdvantages=['A estratégia conecta percepção interna, atração e experiência — não apenas comunicação externa.','EVP, personas, canais, roadmap e indicadores ficam organizados para orientar a execução.','O escopo conversa com Marketing ou agência sem duplicar o trabalho criativo dessas áreas.'];
    return{solutionCopy:recurring?'Uma sustentação consultiva para revisar prioridades, orientar a ativação e acompanhar indicadores, sem assumir a produção criativa ou a operação dos canais.':'Um projeto estratégico para diagnosticar a percepção atual, definir ou refinar o EVP e organizar um plano de ativação viável para RH, Marketing e liderança.',operating:[recurring?'Atuação recorrente com prioridades e calendário revistos em ciclos mensais.':'Projeto organizado nas fases de diagnóstico, estratégia e ativação.','RH, Marketing, Comunicação e liderança participam das validações previstas no escopo.','A empresa fornece pesquisas, guias de marca, acessos, dados e aprovações nos prazos combinados.','RH, Marketing, Comunicação ou parceiros executam as peças e campanhas a partir do direcionamento aprovado.','Os indicadores partem de uma linha de base e dependem da disponibilidade e qualidade dos dados.'],commercial:[...commonProjectCommercial,...(recurring?['A mensalidade cobre as frentes e a capacidade previstas; demandas extraordinárias são orçadas separadamente.']:[])],outOfScope:['Design, produção gráfica ou audiovisual, redação contínua de peças e identidade visual.','Compra de mídia, impulsionamento, gestão de campanhas pagas ou contratação de fornecedores.','Gestão operacional de redes sociais, site de carreiras, vagas ou calendário de publicações.','Rebranding corporativo integral ou redesign da marca institucional.','Garantia de volume de candidatos, redução de turnover ou reputação sem execução conjunta da empresa.'],advantages:concreteAdvantages(profileAdvantages),bonus:['Matriz editável de ativação e KPIs','Modelo para organizar iniciativa, responsável, canal, prazo e indicador de cada movimento da marca empregadora.'],nextSteps:projectNextSteps,contextIds:['modelo_contratacao','momento_empresa','contratacoes_mes','turnover','reviews','evp','personas','canais'],priorityIds:['objetivo','problemas','ativos'],contextLabels:{modelo_contratacao:'Modelo da contratação',momento_empresa:'Momento da empresa',contratacoes_mes:'Contratações por mês',turnover:'Turnover atual',reviews:'Percepção nas avaliações',evp:'Maturidade do EVP',personas:'Personas prioritárias',canais:'Canais de atração'}};
  }
  const profileAdvantages=['O desafio não é forçado em um pacote genérico: objetivo, entregas e limites são confirmados antes do início.','Checkpoints evitam que uma necessidade personalizada se transforme em escopo aberto.','Condução direta por Patrícia e conexão com as prioridades reais do negócio.'];
  return{solutionCopy:'Uma solução desenhada a partir do contexto real da empresa, combinando leitura estratégica, estruturação e desenvolvimento sem forçar a necessidade em um pacote pronto.',operating:['O formato, a duração e a cadência são definidos conforme a natureza e a complexidade da necessidade.','A empresa disponibiliza as pessoas, os dados, os acessos e as aprovações necessários ao trabalho.','Entregas, limites e responsabilidades são descritos expressamente na proposta e no contrato.','Mudanças relevantes de escopo, volume ou formato são avaliadas antes da execução.','Etapas presenciais, fornecedores, licenças e deslocamentos só estão incluídos quando descritos.'],commercial:commonProjectCommercial,outOfScope:['Folha de pagamento, ponto, benefícios, admissões, férias, desligamentos, eSocial ou outras rotinas de Departamento Pessoal.','Operação contínua de recrutamento, hunting em volume, abertura de vagas ou alocação de recrutadores.','Serviços jurídicos, contábeis, médicos, clínicos ou outras atividades técnicas reguladas.','Terceirização de rotinas administrativas ou execução transacional contínua do RH.'],advantages:concreteAdvantages(profileAdvantages),bonus:['Check-in executivo de 30 dias','Uma conversa breve para revisar a aplicação da entrega principal e orientar o próximo movimento.'],nextSteps:[['Conversa de confirmação','Validação do desafio, do resultado esperado e das premissas principais.'],['Desenho do escopo','Definição das entregas, do formato, do cronograma e do investimento.'],['Contrato','Formalização das condições e responsabilidades.'],['Kickoff','Organização dos insumos, das agendas e do primeiro movimento.']],contextIds:['momento_empresa','colaboradores','modelo_trabalho','temas_aproximados','publico_envolvido','formato_desejado','etapa_decisao','prazo_inicio'],priorityIds:['necessidade_descricao','resultado_esperado','impacto_negocio','tentativas_anteriores','restricoes'],contextLabels:{momento_empresa:'Momento da empresa',colaboradores:'Número de colaboradores',modelo_trabalho:'Modelo de trabalho',temas_aproximados:'Temas relacionados',publico_envolvido:'Públicos envolvidos',formato_desejado:'Formato desejado',etapa_decisao:'Etapa da decisão',prazo_inicio:'Início desejado'}};
}

export function profileCadence(profile:ProposalProfile){return profile.operating.filter(item=>!/(carga|\bhoras?\b|cumulativ|investimento)/i.test(item)).slice(0,4);}
export function buildDefaultNarrative(serviceSlug:string,company:string,answers:Answers,profile:ProposalProfile){
  if(serviceSlug==='assessoria-estrategica'){
    const moment=answerText(answers,'momento_empresa'),people=answerText(answers,'colaboradores'),rh=answerText(answers,'rh_interno'),senior=answerText(answers,'lideranca_rh'),challenge=answerText(answers,'principal_desafio');
    return{contextSummary:`${company||'A empresa'} descreveu seu momento atual como ${String(moment||'uma etapa que exige organização').toLowerCase()}${people?` e informou uma estrutura de aproximadamente ${people} colaboradores`:''}. ${rh?`Sobre a estrutura atual de RH, o briefing registra: ${rh}.`:''}${senior?` Em relação à liderança sênior de RH: ${senior}.`:''}${challenge?` O desafio central compartilhado foi: ${challenge}.`:''} Esta proposta transforma essas informações em uma sequência de trabalho compatível com a capacidade real de implantação.`,painPoints:[challenge,...(Array.isArray(answers.frentes)?answers.frentes.map(String):[])].filter(Boolean).slice(0,4),executiveReading:'A leitura inicial indica que o trabalho deve começar pelas prioridades que criam base para as demais necessidades avançarem com consistência.',whyNow:'A recomendação concentra energia no que precisa avançar agora, com critérios claros e uma condução compatível com a capacidade real de implantação da empresa.',cycleObjective:'Transformar a prioridade central em decisões, responsáveis e movimentos aplicáveis ao negócio.',expectedResults:['Prioridades organizadas e compreendidas pela liderança','Decisões apoiadas por critérios mais claros','Próximos movimentos registrados em roadmap']};
  }
  if(serviceSlug==='cali-build'){
    const moment=answerText(answers,'momento_empresa'),people=answerText(answers,'colaboradores'),structure=answerText(answers,'estrutura_rh_status'),team=answerText(answers,'pessoas_rh'),scope=answerText(answers,'escopo_build'),objective=answerText(answers,'objetivo_primeiro_ciclo');
    return{
      contextSummary:(company||'A empresa')+' descreveu seu momento atual como '+String(moment||'uma etapa de estruturação').toLowerCase()+(people?' e informou aproximadamente '+people+' colaboradores':'')+'. '+(structure?'A estrutura atual de RH foi descrita como: '+structure+'. ':'')+(team?'O time informado possui '+team+' pessoa(s) em RH. ':'')+(scope?'A necessidade de estruturação é: '+String(scope).toLowerCase()+'. ':'')+'O desenho considera a capacidade real de execução interna e organiza a implantação em ciclos supervisionados pela CALI.',
      painPoints:[objective,...(Array.isArray(answers.frentes)?answers.frentes.map((x:any)=>labels.frentes?.[String(x)]||String(x)):[])].filter(Boolean).slice(0,4),
      executiveReading:'A leitura inicial deve equilibrar a complexidade do negócio com a capacidade real de execução do RH interno. O primeiro ciclo precisa ser suficientemente claro para avançar, mas também viável para ser construído e sustentado pela equipe.',
      whyNow:'A estrutura precisa ganhar método antes que novas demandas aumentem dependências, retrabalho e decisões sem continuidade.',
      cycleObjective:objective||'Definir a arquitetura da frente prioritária, colocar a construção em movimento e chegar ao primeiro marco validado de implantação.',
      expectedResults:['Arquitetura e prioridades de implantação claramente definidas','Entregas construídas pelo RH interno com revisão técnica e critérios comuns','Roadmap de continuidade com responsáveis, marcos e sustentação definidos'],
    };
  }
  if(serviceSlug==='treinamentos'){
    const type=answerText(answers,'tipo_contratacao')||'ação de desenvolvimento';
    const campaign=answerText(answers,'campanha_calendario');
    const theme=String(answers.tema||'').trim();
    const audience=answerText(answers,'publico');
    const format=answerText(answers,'formato');
    const duration=answerText(answers,'carga_horaria');
    const interaction=answerText(answers,'nivel_interacao');
    const context=String(answers.contexto||'').trim();
    const objective=String(answers.objetivo||'').trim();
    const accessibility=String(answers.acessibilidade||'').trim();
    const notes=String(answers.observacoes||'').trim();
    const pieces=[
      `A solicitação é para ${String(type).toLowerCase()}${campaign?`, vinculada a ${campaign}`:''}.`,
      theme?`Tema informado: ${theme}.`:'',
      audience?`Público: ${audience}.`:'',
      format?`Formato: ${format}${answers.local_execucao?` em ${answers.local_execucao}`:''}.`:'',
      duration?`Duração prevista por encontro: ${duration}.`:'',
    ].filter(Boolean);
    const reading=interaction
      ? `O desenho será ajustado para ${String(interaction).toLowerCase()}, respeitando a duração contratada, o perfil do público e o objetivo informado no briefing.`
      : 'O desenho será ajustado ao público, à duração e ao objetivo informado no briefing, preservando clareza e aplicabilidade.';
    const expected=[
      theme?`Conteúdo customizado para o tema “${theme}” e para o contexto informado.`:'Conteúdo customizado a partir do contexto e do objetivo informados no briefing.',
      audience?`Linguagem e exemplos adequados ao público: ${audience}.`:'',
      interaction?`Participação do público em formato compatível com: ${String(interaction).toLowerCase()}.`:'',
    ].filter(Boolean);
    return{
      contextSummary:pieces.join(' '),
      painPoints:[context,accessibility,notes].filter(Boolean).slice(0,3),
      executiveReading:reading,
      whyNow:campaign?`A ação está vinculada a ${campaign} e será preparada para fazer sentido dentro desse contexto, sem recorrer a conteúdo genérico.`:'A proposta responde ao contexto e ao objetivo registrados no briefing, com um desenho proporcional ao formato solicitado.',
      cycleObjective:objective||'Entregar uma ação de desenvolvimento conectada ao contexto da empresa e ao público participante.',
      expectedResults:expected,
    };
  }
  const readings=profile.contextIds.slice(0,5).map(id=>answerText(answers,id)?`${String(profile.contextLabels[id]||id).toLowerCase()}: ${answerText(answers,id)}`:'').filter(Boolean);const priorities=profile.priorityIds.map(id=>answerText(answers,id)).filter(Boolean);
  return{contextSummary:`${company||'A empresa'} compartilhou um contexto que reúne ${readings.join('; ')||'necessidades que pedem organização, direção e uma sequência viável de implantação'}. Esta proposta parte do briefing recebido e considera as decisões que precisam ser sustentadas pela liderança.`,painPoints:priorities.slice(0,4),executiveReading:'A leitura inicial indica que o trabalho deve começar pelas prioridades que criam base para as demais necessidades avançarem com consistência.',whyNow:'A recomendação concentra energia no que precisa avançar agora, com critérios claros e uma condução compatível com a capacidade real de implantação da empresa.',cycleObjective:'Transformar a prioridade central em decisões, responsáveis e movimentos aplicáveis ao negócio.',expectedResults:['Prioridades organizadas e compreendidas pela liderança','Decisões apoiadas por critérios mais claros','Próximos movimentos registrados em roadmap']};
}

export function portalServiceAlerts(serviceSlug:string,a:Answers):ProposalAlert[]{const x:ProposalAlert[]=[];
  if(serviceSlug==='assessoria-estrategica'){const fronts=a.frentes||[];if(fronts.length>=5||a.frequencia==='semanal'||a.presencial==='mais')x.push({level:'high',text:'Complexidade e cadência indicam CALI FULL.'});if(a.rh_interno==='nao')x.push({level:'medium',text:'Empresa sem RH interno: esclarecer limites entre advisory e execução operacional.'});if((a.indicadores||[]).some((item:any)=>String(item).startsWith('Nenhum')))x.push({level:'medium',text:'Incluir implantação mínima de rotina de indicadores.'});if(a.modelo_interesse==='PARTNER'&&(fronts.length>=5||a.frequencia==='semanal'||['mensal','mais'].includes(a.presencial)))x.push({level:'high',text:'O lead escolheu PARTNER, mas complexidade, cadência ou presencialidade sugerem revisar o encaixe para FULL.'});}
  else if(serviceSlug==='cali-build'){const fronts=Array.isArray(a.frentes)?a.frentes:[],people=Number(a.pessoas_rh||0),size=Number(a.colaboradores||0),ratio=people>0?size/people:size;if(a.responsavel_implantacao==='nao')x.push({level:'high',text:'O CALI Build exige uma pessoa interna responsável pela execução. Sem esse papel, avaliar CALI Full ou redefinir o desenho antes da proposta.'});if(a.capacidade_execucao==='menos2')x.push({level:'high',text:'Capacidade interna muito baixa para implantação: revisar ritmo, escopo e viabilidade do Build.'});if(size>=300&&people>0&&ratio>150)x.push({level:'medium',text:'Relação colaboradores por profissional de RH elevada: considerar maior carga de acompanhamento e implantação por fases.'});if(a.escopo_build==='frente_especifica'&&fronts.length>1)x.push({level:'medium',text:'O briefing marcou uma frente específica, mas selecionou várias frentes. Confirmar qual é a prioridade real do primeiro ciclo.'});if(['eventual','recorrente'].includes(String(a.visita_interesse||'')))x.push({level:'attention',text:'Atuação presencial é adicional; deslocamento, hospedagem, alimentação e demais custos devem ser pagos antecipadamente pela contratante.'});}
  else if(serviceSlug==='mentoria-rh'){if(a.modalidade==='grupo'&&Number(a.participantes)>5)x.push({level:'high',text:'O programa em grupo é limitado a 5 participantes da mesma empresa.'});if(a.suporte==='proximo')x.push({level:'medium',text:'Prever carga adicional de suporte entre encontros.'});if(a.modalidade==='grupo'&&['avaliacao','nao_apresentada'].includes(a.status_iniciativa))x.push({level:'medium',text:'Iniciativa corporativa ainda não aprovada: a proposta deve apoiar a decisão e explicitar as premissas.'});if(a.frequencia==='semanal')x.push({level:'medium',text:'Cadência semanal: validar agenda e intensidade do ciclo.'});}
  else if(serviceSlug==='diagnostico-executivo'){if(Number(a.entrevistas)>10)x.push({level:'medium',text:'Mais de 10 entrevistas: revisar carga e cronograma.'});if(a.documentos==='desorganizada'||a.acesso_dados==='nao')x.push({level:'high',text:'Aplicar etapa e carga de organização documental antes da leitura.'});if(a.prazo_inicio==='imediato')x.push({level:'medium',text:'Confirmar disponibilidade mínima de quatro semanas.'});}
  else if(serviceSlug==='cultura-direcao'){if(Number(a.colaboradores)>200||Number(a.unidades)>3)x.push({level:'medium',text:'Revisar amostra, comunicação e logística por porte.'});if((a.contexto||[]).includes('ma'))x.push({level:'high',text:'Contexto de M&A exige trilha específica de integração cultural.'});if(a.patrocinio_lideranca==='baixo')x.push({level:'high',text:'Baixo patrocínio executivo: prever etapa de alinhamento antes da mobilização ampla.'});}
  else if(serviceSlug==='shadowing-lideranca'){if(a.presencial==='remoto')x.push({level:'medium',text:'O presencial é recomendado por ser a essência do Shadowing.'});if(Number(a.lideres)>1)x.push({level:'high',text:'O Shadowing é individual: organizar uma proposta ou ciclo próprio para cada liderança.'});if(a.ciencia_lideres==='nao')x.push({level:'high',text:'Planejar comunicação e consentimento antes da observação.'});}
  else if(serviceSlug==='treinamentos'){const participants=Number(a.participantes||0),hours=Number(a.carga_horaria||0);if(participants>150)x.push({level:'high',text:'Público acima de 150 pessoas: revisar desenho, infraestrutura e nível de interação.'});else if(participants>40&&a.tipo_contratacao==='workshop')x.push({level:'medium',text:'Workshop com mais de 40 pessoas pode exigir divisão em grupos, apoio de facilitação ou adaptação da dinâmica.'});if(a.nivel_interacao==='dinamica'&&hours>0&&hours<=1.5)x.push({level:'medium',text:'Atividade prática em uma janela curta pode exigir revisão de duração para preservar a qualidade da aplicação.'});if(a.tipo_contratacao==='programa_lideranca'&&Number(a.encontros||0)<4)x.push({level:'medium',text:'Programas de liderança são estruturados entre 4 e 10 encontros; revise a quantidade antes da proposta.'});if(['presencial','hibrido'].includes(a.formato)&&a.local_execucao&&!String(a.local_execucao).toLowerCase().includes('curitiba'))x.push({level:'medium',text:'Prever deslocamento e eventual hospedagem conforme a cidade da realização.'});if(a.data_desejada&&/próxima semana|semana que vem/i.test(a.data_desejada))x.push({level:'high',text:'Antecedência abaixo das quatro semanas recomendadas.'});}
  else if(serviceSlug==='marca-empregadora'){if(a.reviews==='negativas')x.push({level:'high',text:'Prever frente de reputação e resposta a passivos de percepção.'});if(a.modelo_contratacao==='recorrente'&&(a.ativos||[]).includes('evp'))x.push({level:'medium',text:'Separar fase inicial de definição do EVP da sustentação mensal.'});if(!(a.equipe_interna||[]).includes('marketing')&&!(a.equipe_interna||[]).includes('comunicacao'))x.push({level:'medium',text:'Sem Marketing ou Comunicação: definir capacidade interna de produção e aprovação.'});}
  else{if(a.prazo_inicio==='imediato')x.push({level:'medium',text:'Início imediato: validar agenda, disponibilidade dos decisores e insumos mínimos.'});if(a.formato_desejado==='presencial'&&!String(a.local_execucao||'').toLowerCase().includes('curitiba'))x.push({level:'medium',text:'Etapa presencial fora de Curitiba e Região Metropolitana: prever deslocamento e eventual hospedagem.'});if(a.etapa_decisao==='exploratoria')x.push({level:'medium',text:'Demanda ainda exploratória: a proposta deve explicitar premissas e possíveis caminhos antes de fechar o escopo.'});}
  return x;
}
