import { supabase } from './supabase';

type Role = 'admin' | 'client';
type Identity = { id?: string | null; full_name: string; avatar_url?: string | null; avatar_position_x?: number | null; avatar_position_y?: number | null; avatar_zoom?: number | null };
type Msg = { id:string; record_id:string; author_id?:string|null; author_role:'admin'|'client'|'system'; body:string; visibility:'client'|'internal'; created_at:string };
type FileToken = { name:string; path:string; mime:string; size:number };

let installed=false, busy=false, debounce=0, activeRecord='', activeCompany='';
let observer:MutationObserver|null=null;
let channel:ReturnType<NonNullable<typeof supabase>['channel']>|null=null;
let pending:FileToken[]=[];
const emojis=['🙂','😊','👍','🙏','✨','✅','💡','📌','📎','❤️','👏','🤝'];
const fileToken=/\[\[arquivo\|([^|]+)\|([^|]+)\|([^|]+)\|(\d+)\]\]/g;

function role():Role|null{if(location.pathname.startsWith('/admin/registros'))return'admin';if(location.pathname.startsWith('/cliente/registros'))return'client';return null;}
function initials(v:string){return v.split(/\s+/).filter(Boolean).slice(0,2).map(p=>p[0]?.toUpperCase()||'').join('')||'C';}
function when(v:string){const d=new Date(v);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(d).replace('.','');}
function safe(v:string){return v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9._-]+/g,'-').replace(/-+/g,'-').slice(0,90)||'arquivo';}
function setValue(el:HTMLTextAreaElement,v:string){const setter=Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value')?.set;setter?.call(el,v);el.dispatchEvent(new Event('input',{bubbles:true}));el.focus();}
function avatar(identity:Identity){const a=document.createElement('span');a.className='records-chat-avatar';if(identity.avatar_url){const img=document.createElement('img');img.src=identity.avatar_url;img.alt='';img.style.objectPosition=`${Number(identity.avatar_position_x??50)}% ${Number(identity.avatar_position_y??50)}%`;img.style.transform=`scale(${Number(identity.avatar_zoom??1)})`;a.append(img);}else a.textContent=initials(identity.full_name);return a;}
function parseBody(body:string){const files:FileToken[]=[];const clean=body.replace(fileToken,(_m,n,p,t,s)=>{try{files.push({name:decodeURIComponent(n),path:decodeURIComponent(p),mime:decodeURIComponent(t),size:Number(s||0)});}catch{files.push({name:n,path:p,mime:t,size:Number(s||0)});}return'';}).trim();return{clean,files};}
function linkify(parent:HTMLElement,text:string){text.split(/(https?:\/\/[^\s]+)/g).forEach(part=>{if(/^https?:\/\//i.test(part)){const a=document.createElement('a');a.href=part;a.target='_blank';a.rel='noopener noreferrer';a.textContent=part;parent.append(a);}else if(part)parent.append(document.createTextNode(part));});}
async function openFile(file:FileToken){if(!supabase)return;const{data,error}=await supabase.storage.from('cali-workspace-private').createSignedUrl(file.path,300);if(error||!data?.signedUrl){alert('Não foi possível abrir este anexo agora.');return;}window.open(data.signedUrl,'_blank','noopener,noreferrer');}

async function identities(r:Role,companyId:string){const map=new Map<string,Identity>();let admin:Identity={full_name:'Patrícia Lima'},client:Identity={full_name:'Cliente'};if(!supabase)return{map,admin,client};const{data:s}=await supabase.auth.getSession();const uid=s.session?.user?.id||'';if(r==='admin'){
  const self=uid?await supabase.from('profiles').select('id,full_name,avatar_url,avatar_position_x,avatar_position_y,avatar_zoom').eq('id',uid).maybeSingle():{data:null};
  const clients=await supabase.from('profiles').select('id,full_name,avatar_url,avatar_position_x,avatar_position_y,avatar_zoom').eq('company_id',companyId).eq('role','client').eq('active',true);
  if(self.data){admin=self.data as Identity;map.set(String((self.data as any).id),admin);}((clients.data||[])as Identity[]).forEach(x=>{if(x.id)map.set(String(x.id),x);});if(clients.data?.[0])client=clients.data[0] as Identity;
}else{
  const self=uid?await supabase.from('profiles').select('id,full_name,avatar_url,avatar_position_x,avatar_position_y,avatar_zoom').eq('id',uid).maybeSingle():{data:null};
  const contact=await supabase.rpc('get_client_account_contact');if(self.data){client=self.data as Identity;map.set(String((self.data as any).id),client);}const c=Array.isArray(contact.data)?contact.data[0]:contact.data;if(c)admin=c as Identity;
}return{map,admin,client};}
function who(m:Msg,ids:Awaited<ReturnType<typeof identities>>){if(m.author_id&&ids.map.has(m.author_id))return ids.map.get(m.author_id)!;if(m.author_role==='admin')return ids.admin;if(m.author_role==='client')return ids.client;return{full_name:'CALI Workspace'};}

async function renderMessages(recordId:string,companyId:string,r:Role){if(!supabase)return;const history=document.querySelector<HTMLElement>('.records-v13-drawer .conversation-history');if(!history)return;const[result,ids]=await Promise.all([supabase.from('account_record_messages').select('id,record_id,author_id,author_role,body,visibility,created_at').eq('record_id',recordId).is('deleted_at',null).order('created_at'),identities(r,companyId)]);if(result.error)return;const messages=(result.data||[])as Msg[];const signature=messages.map(m=>`${m.id}:${m.body.length}:${m.created_at}`).join('|');if(history.dataset.recordsSignature===signature&&history.querySelector('.records-chat-line,.records-chat-empty'))return;history.dataset.recordsSignature=signature;history.replaceChildren();if(!messages.length){const e=document.createElement('div');e.className='records-chat-empty';e.textContent='A conversa começa aqui.';history.append(e);return;}
  messages.forEach(m=>{const id=who(m,ids),mine=m.author_role===r,line=document.createElement('div');line.className=`conversation-line records-chat-line role-${m.author_role} ${mine?'mine':'other'} ${m.visibility==='internal'?'internal':''}`;const bubble=document.createElement('div');bubble.className='conversation-bubble records-chat-bubble';const head=document.createElement('div');head.className='records-chat-head';const name=document.createElement('strong');name.textContent=m.visibility==='internal'?`${id.full_name} · nota interna`:id.full_name;const time=document.createElement('time');time.textContent=when(m.created_at);head.append(name,time);bubble.append(head);const parsed=parseBody(m.body);if(parsed.clean){const p=document.createElement('p');linkify(p,parsed.clean);bubble.append(p);}if(parsed.files.length){const list=document.createElement('div');list.className='records-chat-attachments';parsed.files.forEach(f=>{const b=document.createElement('button');b.type='button';b.className='records-chat-attachment';const icon=document.createElement('span');icon.textContent='📎';const copy=document.createElement('span'),strong=document.createElement('strong'),small=document.createElement('small');strong.textContent=f.name;small.textContent=f.size?`${Math.max(1,Math.round(f.size/1024))} KB`:'arquivo';copy.append(strong,small);b.append(icon,copy);b.onclick=()=>void openFile(f);list.append(b);});bubble.append(list);}if(mine)line.append(bubble,avatar(id));else line.append(avatar(id),bubble);history.append(line);});history.scrollTop=history.scrollHeight;
}

function pendingTray(compose:HTMLElement){let tray=compose.querySelector<HTMLElement>('.records-chat-pending');if(!tray){tray=document.createElement('div');tray.className='records-chat-pending';compose.prepend(tray);}const sig=pending.map(x=>x.path).join('|');if(tray.dataset.sig===sig)return;tray.dataset.sig=sig;tray.replaceChildren();pending.forEach((f,i)=>{const chip=document.createElement('span');chip.className='records-chat-pending-chip';const text=document.createElement('span');text.textContent=`📎 ${f.name}`;const x=document.createElement('button');x.type='button';x.textContent='×';x.onclick=async()=>{pending.splice(i,1);if(supabase)await supabase.storage.from('cali-workspace-private').remove([f.path]);pendingTray(compose);};chip.append(text,x);tray!.append(chip);});tray.style.display=pending.length?'flex':'none';}
async function upload(file:File,recordId:string,companyId:string,compose:HTMLElement){if(!supabase)return;const allowed=new Set(['application/pdf','image/png','image/jpeg','image/webp','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','application/vnd.openxmlformats-officedocument.presentationml.presentation']);if(!allowed.has(file.type)){alert('Use PDF, imagem, Word, Excel ou PowerPoint.');return;}if(file.size>10*1024*1024){alert('Cada anexo pode ter até 10 MB.');return;}if(pending.length>=5){alert('Você pode enviar até 5 anexos por mensagem.');return;}const{data:s}=await supabase.auth.getSession();const uid=s.session?.user?.id;if(!uid)return;const path=`records/${companyId}/${recordId}/${uid}/${Date.now()}-${safe(file.name)}`;const{error}=await supabase.storage.from('cali-workspace-private').upload(path,file,{contentType:file.type,upsert:false});if(error){alert(`Não consegui anexar “${file.name}”.`);return;}pending.push({name:file.name,path,mime:file.type,size:file.size});pendingTray(compose);}
async function send(recordId:string,textarea:HTMLTextAreaElement,button:HTMLButtonElement,compose:HTMLElement){if(!supabase)return;const text=textarea.value.trim();if(!text&&!pending.length)return;const tokens=pending.map(f=>`[[arquivo|${encodeURIComponent(f.name)}|${encodeURIComponent(f.path)}|${encodeURIComponent(f.mime)}|${f.size}]]`).join('\n');button.disabled=true;try{const res=await supabase.rpc('post_account_record_message',{p_record_id:recordId,p_body:[text,tokens].filter(Boolean).join('\n'),p_internal:false});if(res.error)throw res.error;pending=[];setValue(textarea,'');pendingTray(compose);window.setTimeout(()=>void enhance(true),80);}catch(e){alert(e instanceof Error?e.message:'Não foi possível enviar a mensagem.');}finally{button.disabled=false;}}
function composer(recordId:string,companyId:string){const compose=document.querySelector<HTMLElement>('.records-v13-drawer .conversation-compose'),textarea=compose?.querySelector<HTMLTextAreaElement>('textarea'),sendBtn=compose?.querySelector<HTMLButtonElement>('button.primary');if(!compose||!textarea||!sendBtn)return;if(!compose.querySelector('.records-chat-tools')){const tools=document.createElement('div');tools.className='records-chat-tools';const attach=document.createElement('button');attach.type='button';attach.textContent='📎';attach.title='Anexar arquivo';const input=document.createElement('input');input.type='file';input.multiple=true;input.hidden=true;input.accept='.pdf,.png,.jpg,.jpeg,.webp,.docx,.xlsx,.pptx';attach.onclick=()=>input.click();input.onchange=async()=>{for(const f of Array.from(input.files||[]))await upload(f,recordId,companyId,compose);input.value='';};const link=document.createElement('button');link.type='button';link.textContent='🔗';link.title='Inserir link';link.onclick=()=>{const v=prompt('Cole o link que deseja compartilhar:');if(!v)return;const url=/^https?:\/\//i.test(v.trim())?v.trim():`https://${v.trim()}`;setValue(textarea,`${textarea.value}${textarea.value?' ':''}${url}`);};const emoji=document.createElement('button');emoji.type='button';emoji.textContent='☺';emoji.title='Inserir emoji';const picker=document.createElement('div');picker.className='records-chat-emoji-picker';picker.hidden=true;emojis.forEach(e=>{const b=document.createElement('button');b.type='button';b.textContent=e;b.onclick=()=>{setValue(textarea,`${textarea.value}${e}`);picker.hidden=true;};picker.append(b);});emoji.onclick=()=>picker.hidden=!picker.hidden;tools.append(attach,input,link,emoji,picker);compose.insertBefore(tools,textarea);pendingTray(compose);}if(!sendBtn.dataset.richRecordsBound){sendBtn.dataset.richRecordsBound='1';sendBtn.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();void send(recordId,textarea,sendBtn,compose);},true);textarea.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();void send(recordId,textarea,sendBtn,compose);}},true);}}
function subscribe(recordId:string){if(!supabase||(recordId===activeRecord&&channel))return;if(channel)supabase.removeChannel(channel);activeRecord=recordId;channel=supabase.channel(`records-live-v2-${recordId}-${Date.now()}`).on('postgres_changes',{event:'INSERT',schema:'cali_workspace',table:'account_record_messages',filter:`record_id=eq.${recordId}`},()=>window.setTimeout(()=>void enhance(true),80)).subscribe();}

async function decorateTable(){if(!supabase||role()!=='admin')return;const select=document.querySelector<HTMLSelectElement>('.records-v13-toolbar label:first-child select'),companyId=select?.value;if(!companyId)return;const{data:c}=await supabase.from('companies').select('display_name,logo_url').eq('id',companyId).maybeSingle();if(!c)return;document.querySelectorAll<HTMLTableRowElement>('.records-v13-table tbody tr').forEach(row=>{const cell=row.querySelector<HTMLTableCellElement>('td:nth-child(2)');if(!cell||cell.querySelector('.records-company-cell'))return;const wrap=document.createElement('span');wrap.className='records-company-cell';const mark=document.createElement('span');mark.className='records-company-logo';if(c.logo_url){const img=document.createElement('img');img.src=c.logo_url;img.alt='';mark.append(img);}else mark.textContent=initials(c.display_name||'C');const name=document.createElement('span');name.textContent=c.display_name||cell.textContent||'Cliente';wrap.append(mark,name);cell.replaceChildren(wrap);});}
function copy(){const h=document.querySelector<HTMLElement>('.records-v13-heading h1');if(h&&h.textContent?.trim()!=='Ocorrências e solicitações')h.textContent='Ocorrências e solicitações';}
async function enhance(force=false){if(busy||!supabase)return;const r=role();if(!r)return;copy();void decorateTable();const drawer=document.querySelector<HTMLElement>('.records-v13-drawer');if(!drawer)return;const protocol=drawer.querySelector<HTMLElement>('.section-kicker')?.textContent?.trim()||'';if(!protocol.startsWith('CALI-REG-'))return;busy=true;try{const{data:rec}=await supabase.from('account_records').select('id,company_id').eq('protocol',protocol).maybeSingle();if(!rec?.id||!rec.company_id)return;activeCompany=rec.company_id;subscribe(rec.id);await renderMessages(rec.id,rec.company_id,r);composer(rec.id,rec.company_id);drawer.querySelectorAll<HTMLButtonElement>('.records-v13-drawer-actions button').forEach(b=>{const t=b.textContent?.trim();if(t==='Assumir')b.textContent='Assumir atendimento';if(t==='Enriquecer memória')b.textContent='Salvar na memória da conta';});if(force)drawer.dataset.recordsRich='refreshed';}finally{busy=false;}}
function schedule(){clearTimeout(debounce);debounce=window.setTimeout(()=>void enhance(),75);}
export function installRecordsExperienceRuntimeV2(){if(installed)return;installed=true;const start=()=>{schedule();observer?.disconnect();observer=new MutationObserver(()=>schedule());observer.observe(document.body,{childList:true,subtree:true});};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();window.addEventListener('focus',schedule);window.addEventListener('popstate',schedule);}
