import { supabase } from './supabase';

type Track={id:string;status:string;sent_at?:string|null;client_open_count?:number|null;client_first_opened_at?:string|null;client_last_opened_at?:string|null;client_pdf_count?:number|null;acknowledged_at?:string|null;acknowledgement_protocol?:string|null};
const eventLabel:Record<string,string>={opened:'Relatório aberto',pdf_opened:'PDF aberto / baixado',acknowledged:'Ciência registrada',drive_saved:'Salvo no Drive'};
let observer:MutationObserver|null=null,timer=0,lastProtocol='';
function fmt(value?:string|null){if(!value)return'—';const date=new Date(value);return Number.isNaN(date.getTime())?'—':new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(date);}
function protocol(){const values=Array.from(document.querySelectorAll<HTMLElement>('.reports-v16-identification dd'));return values.map((item)=>item.textContent?.trim()||'').find((value)=>/^CALI-RPT-/i.test(value))||'';}
function remove(){document.querySelector('.report-client-track-v55')?.remove();document.querySelector('.report-client-history-backdrop-v55')?.remove();}
function debounce(){window.clearTimeout(timer);timer=window.setTimeout(()=>void render(),180);}
async function render(){if(window.location.pathname!=='/admin/relatorios'||!supabase){remove();lastProtocol='';return;}const nextProtocol=protocol();if(!nextProtocol){document.querySelector('.report-client-track-v55')?.remove();return;}lastProtocol=nextProtocol;const result=await supabase.from('reports').select('id,status,sent_at,client_open_count,client_first_opened_at,client_last_opened_at,client_pdf_count,acknowledged_at,acknowledgement_protocol').eq('protocol',nextProtocol).maybeSingle();if(result.error||!result.data||lastProtocol!==nextProtocol)return;const report=result.data as Track;const toolbar=document.querySelector('.reports-v16-toolbar');if(!toolbar)return;let card=document.querySelector<HTMLElement>('.report-client-track-v55');if(!['sent','published'].includes(report.status)&&!report.sent_at){card?.remove();return;}if(!card){card=document.createElement('section');card.className='report-client-track-v55';toolbar.insertAdjacentElement('afterend',card);}const opens=Number(report.client_open_count||0),pdfs=Number(report.client_pdf_count||0);const signature=JSON.stringify([report.id,report.sent_at,opens,report.client_first_opened_at,report.client_last_opened_at,pdfs,report.acknowledged_at,report.acknowledgement_protocol]);if(card.dataset.state===signature)return;card.dataset.state=signature;card.innerHTML=`<div><span>ACOMPANHAMENTO DO CLIENTE</span><strong>${report.acknowledged_at?'Ciência registrada':'Relatório disponibilizado'}</strong></div><div class="report-client-track-stats-v55"><span>Enviado ${fmt(report.sent_at)}</span><span>Aberto <b>${opens}x</b></span>${report.client_first_opened_at?`<span>1º acesso ${fmt(report.client_first_opened_at)}</span>`:''}${report.client_last_opened_at?`<span>Último ${fmt(report.client_last_opened_at)}</span>`:''}<span>PDF <b>${pdfs}x</b></span><span>${report.acknowledged_at?`Ciência ✓ ${fmt(report.acknowledged_at)}`:'Ciência pendente'}</span><button type="button" data-report-history-v55>Ver histórico</button></div>`;card.querySelector('[data-report-history-v55]')?.addEventListener('click',()=>void openHistory(report.id,report.acknowledgement_protocol));}
async function openHistory(reportId:string,ackProtocol?:string|null){if(!supabase)return;const result=await supabase.from('report_client_events').select('event_type,created_at,user_id,metadata').eq('report_id',reportId).order('created_at',{ascending:false});if(result.error)return;const events=(result.data||[]) as any[];const ids=Array.from(new Set(events.map((item)=>item.user_id).filter(Boolean)));const names=new Map<string,string>();if(ids.length){const profiles=await supabase.from('profiles').select('id,full_name').in('id',ids);for(const item of profiles.data||[])names.set(String((item as any).id),String((item as any).full_name||'Cliente'));}document.querySelector('.report-client-history-backdrop-v55')?.remove();const backdrop=document.createElement('div');backdrop.className='modal-backdrop full-screen-modal report-client-history-backdrop-v55';const modal=document.createElement('section');modal.className='modal-card report-client-history-modal-v55';modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.innerHTML=`<button class="modal-close" type="button" aria-label="Fechar">×</button><span class="section-kicker">RASTREABILIDADE</span><h2>Histórico do cliente</h2><p>Cada abertura e ação relevante desta versão fica preservada.</p>${ackProtocol?`<div class="inline-notice success">Protocolo de ciência: <strong>${ackProtocol}</strong></div>`:''}<div class="report-client-history-list-v55">${events.length?events.map((event)=>`<article><span>${fmt(event.created_at)}</span><strong>${eventLabel[event.event_type]||event.event_type}</strong><b>${names.get(String(event.user_id))||'Cliente'}</b></article>`).join(''):'<p>Nenhuma interação registrada ainda.</p>'}</div>`;backdrop.appendChild(modal);document.body.appendChild(backdrop);document.body.classList.add('workspace-modal-open');const close=()=>{backdrop.remove();document.body.classList.remove('workspace-modal-open');};modal.querySelector('.modal-close')?.addEventListener('click',close);backdrop.addEventListener('click',(event)=>{if(event.target===backdrop)close();});}
export function installReportClientTrackingRuntimeV55(){if(typeof window==='undefined'||observer)return;observer=new MutationObserver(debounce);observer.observe(document.documentElement,{subtree:true,childList:true,characterData:true});window.addEventListener('popstate',debounce);window.addEventListener('focus',debounce);window.setInterval(()=>void render(),5000);window.setTimeout(()=>void render(),500);}
