import { supabase } from './supabase';

type AgendaCompliance = {
  plan?: string | null;
  label?: string | null;
  sessionsPerMonth?: number;
  cadenceDays?: number;
  modePolicy?: string;
  onsitePerMonth?: number;
  fixedRequired?: boolean;
  requiredTotal?: number;
  occurredCount?: number;
  notOccurredCount?: number;
  pendingOutcomeCount?: number;
  scheduledCount?: number;
  extraCount?: number;
  remoteContractualCount?: number;
  inPersonContractualCount?: number;
  items?: Array<{ id?: string; protocol?: string; title?: string; startsAt?: string; mode?: string; sessionNumber?: number; scheduleClass?: string; outcome?: string; reasonCategory?: string | null; justified?: boolean; note?: string | null; billingApplies?: boolean }>;
  monthly?: Array<{ month?: string; required?: number; occurred?: number; notOccurred?: number; pendingOutcome?: number; scheduled?: number; contractualCount?: number }>;
  recommendedNextAt?: string | null;
  entitlement?: string;
  billable?: boolean;
  sessionNumber?: number | null;
  urgencyLevel?: string;
  urgencyFeeApplies?: boolean;
  requiresAcknowledgement?: boolean;
  notice?: string;
};

type SchedulingRequestV66 = {
  id: string;
  company_id: string;
  status: string;
  request_mode: string;
  meeting_entitlement?: string | null;
  contract_session_number?: number | null;
  included_sessions_snapshot?: number | null;
  cadence_days_snapshot?: number | null;
  urgency_level?: string | null;
  urgency_fee_applies?: boolean | null;
  billable_extra?: boolean | null;
  billing_acknowledged_at?: string | null;
  billing_notice?: string | null;
  service_plan_snapshot?: string | null;
};

type CompanyV66 = {
  id: string;
  display_name: string;
  service_plan?: string | null;
  meeting_sessions_included_per_month?: number | null;
  meeting_cadence_days?: number | null;
  meeting_mode_policy?: string | null;
  fixed_meeting_required?: boolean | null;
  onsite_visits_included_per_month?: number | null;
};

let installed = false;
let observer: MutationObserver | null = null;
let renderTimer: number | undefined;
let clientComplianceLoading = false;
let adminLoading = false;
let clientRequests = new Map<string, SchedulingRequestV66>();
let adminRequests = new Map<string, SchedulingRequestV66>();
let adminCompanies: CompanyV66[] = [];

const STYLE = `
/* CALI Workspace · Agenda contratual V66 */
#scheduling-v65-client-host .scheduling-v65-panel.scheduling-v66-contract-card{position:relative;border:1px solid #d9bd69!important;border-left:5px solid #5A1E2D!important;background:linear-gradient(135deg,#FFF4C9 0%,#F7E3A3 100%)!important;box-shadow:0 12px 30px rgba(89,63,25,.09)!important}
#scheduling-v65-client-host .scheduling-v66-contract-card .scheduling-v65-head{background:transparent!important;border-bottom:1px solid rgba(90,30,45,.12)}
#scheduling-v65-client-host .scheduling-v66-contract-card .scheduling-v65-kicker{color:#785216!important}
#scheduling-v65-client-host .scheduling-v66-contract-card .scheduling-v65-head h2{color:#38291f!important}
#scheduling-v65-client-host .scheduling-v66-contract-card .scheduling-v65-head p,#scheduling-v65-client-host .scheduling-v66-contract-card .scheduling-v65-empty,#scheduling-v65-client-host .scheduling-v66-contract-card .scheduling-v65-request p{color:#655342!important}
.scheduling-v66-contract-summary{display:grid;grid-template-columns:minmax(0,1.2fr) repeat(3,minmax(110px,.45fr));gap:12px;padding:15px 18px;border-bottom:1px solid rgba(90,30,45,.12)}
.scheduling-v66-contract-summary>div:first-child{padding-right:10px}.scheduling-v66-contract-summary small{display:block;margin-bottom:4px;font-size:12px!important;font-weight:850;letter-spacing:.05em;text-transform:uppercase;color:#8A6628}.scheduling-v66-contract-summary strong{display:block;font-size:15px;line-height:1.25;color:#38291f}.scheduling-v66-contract-summary p{margin:5px 0 0!important;font-size:13px!important;line-height:1.5!important;color:#655342!important}.scheduling-v66-stat{padding:10px 12px;border:1px solid rgba(90,30,45,.12);border-radius:12px;background:rgba(255,255,255,.42)}.scheduling-v66-stat b{display:block;font-size:20px;color:#5A1E2D}.scheduling-v66-stat span{font-size:12px;font-weight:750;color:#655342}
.scheduling-v66-alert{margin:0 18px 14px;padding:11px 13px;border-radius:11px;border:1px solid rgba(90,30,45,.15);background:rgba(255,255,255,.48);font-size:13px;line-height:1.5;color:#544438}.scheduling-v66-alert strong{color:#5A1E2D}.scheduling-v66-request-meta{display:flex;gap:7px;flex-wrap:wrap;margin:7px 0 2px}.scheduling-v66-request-meta .scheduling-v65-badge{font-size:12px!important;min-height:26px!important;padding:0 9px!important}.scheduling-v66-urgency-select{min-height:36px;border:1px solid var(--theme-line,#ded5cf);border-radius:10px;background:var(--theme-surface,#fff);color:var(--theme-text,#2b2b2b);font:700 13px/1.2 inherit;padding:0 9px}.scheduling-v66-contract-editor{margin-top:12px;padding:13px;border:1px solid var(--theme-line,#ded5cf);border-radius:12px;background:var(--theme-surface-soft,#faf7f5)}.scheduling-v66-contract-editor>strong{display:block;margin-bottom:5px;font-size:14px;color:var(--theme-text,#2b2b2b)}.scheduling-v66-contract-editor>p{margin:0 0 10px;font-size:13px;line-height:1.5;color:var(--theme-muted,#716660)}.scheduling-v66-contract-editor select{width:100%;min-height:40px;border:1px solid var(--theme-line,#ded5cf);border-radius:10px;background:var(--theme-surface,#fff);color:var(--theme-text,#2b2b2b);font:inherit;font-size:14px;padding:0 10px}
.scheduling-v66-event-status{margin-top:12px;padding:12px 13px;border:1px solid var(--theme-line,#e2d8d2);border-radius:12px;background:var(--theme-surface-soft,#faf7f5);font-size:13px;line-height:1.45;color:var(--theme-muted,#6f6460)}.scheduling-v66-event-status strong{color:var(--theme-text,#2b2b2b)}.scheduling-v66-event-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}
/* Corrige a microtipografia do fluxo V65 sem mexer na agenda compartilhada abaixo */
.scheduling-v65-panel .scheduling-v65-kicker{font-size:12px!important}.scheduling-v65-panel .scheduling-v65-head p,.scheduling-v65-panel .scheduling-v65-request p,.scheduling-v65-panel .scheduling-v65-empty,.scheduling-v65-panel .scheduling-v65-note,.scheduling-v65-panel .scheduling-v65-policy,.scheduling-v65-panel .scheduling-v65-ack{font-size:13px!important;line-height:1.5!important}.scheduling-v65-panel .scheduling-v65-button{font-size:13px!important}.scheduling-v65-panel .scheduling-v65-badge{font-size:11px!important}.scheduling-v65-modal .scheduling-v65-field>span{font-size:12px!important}.scheduling-v65-modal .scheduling-v65-field input,.scheduling-v65-modal .scheduling-v65-field select,.scheduling-v65-modal .scheduling-v65-field textarea,.scheduling-v65-modal .scheduling-v65-mode label{font-size:14px!important}.scheduling-v65-modal .scheduling-v65-policy,.scheduling-v65-modal .scheduling-v65-ack,.scheduling-v65-modal .scheduling-v65-error{font-size:13px!important}.scheduling-v65-modal .scheduling-v65-button{font-size:13px!important}
.reports-v66-agenda{padding:4mm 0!important;border-top:1px solid #DDD4CE!important}.reports-v66-agenda-head{display:flex!important;align-items:flex-end!important;justify-content:space-between!important;gap:6mm!important;margin-bottom:2.5mm!important}.reports-v66-agenda-head small{font:700 5.8pt/1.2 Inter,Arial,sans-serif!important;letter-spacing:.1em!important;text-transform:uppercase!important;color:#8A7150!important}.reports-v66-agenda-head h2{margin:.8mm 0 0!important;font:600 12pt/1.15 'Playfair Display',Georgia,serif!important;color:#332D2A!important}.reports-v66-agenda-head span{font:600 6.4pt/1.35 Inter,Arial,sans-serif!important;color:#6D625D!important;text-align:right!important}.reports-v66-agenda-grid{display:grid!important;grid-template-columns:repeat(4,1fr)!important;gap:2mm!important}.reports-v66-agenda-grid>div{padding:2mm!important;border:1px solid #E5DDD7!important;border-radius:2mm!important;background:#FBF8F5!important}.reports-v66-agenda-grid small{display:block!important;font:700 5.4pt/1.2 Inter,Arial,sans-serif!important;text-transform:uppercase!important;color:#94867F!important}.reports-v66-agenda-grid strong{display:block!important;margin-top:.8mm!important;font:650 9pt/1.1 Inter,Arial,sans-serif!important;color:#5A1E2D!important}.reports-v66-agenda-note{margin:2mm 0 0!important;font:400 6.2pt/1.45 Inter,Arial,sans-serif!important;color:#665C57!important}.reports-v66-agenda-note b{font-weight:700!important;color:#4C433F!important}
html[data-workspace-theme='night'] #scheduling-v65-client-host .scheduling-v66-contract-card{background:linear-gradient(135deg,#44361F 0%,#322719 100%)!important;border-color:#80662E!important;border-left-color:#D2A650!important}html[data-workspace-theme='night'] #scheduling-v65-client-host .scheduling-v66-contract-card .scheduling-v65-head h2,html[data-workspace-theme='night'] #scheduling-v65-client-host .scheduling-v66-contract-card .scheduling-v66-contract-summary strong{color:#F7EBCF!important}html[data-workspace-theme='night'] #scheduling-v65-client-host .scheduling-v66-contract-card .scheduling-v65-head p,html[data-workspace-theme='night'] #scheduling-v65-client-host .scheduling-v66-contract-card .scheduling-v65-empty,html[data-workspace-theme='night'] #scheduling-v65-client-host .scheduling-v66-contract-card .scheduling-v65-request p,html[data-workspace-theme='night'] #scheduling-v65-client-host .scheduling-v66-contract-card .scheduling-v66-contract-summary p{color:#E4D6B8!important}html[data-workspace-theme='night'] .scheduling-v66-stat,html[data-workspace-theme='night'] .scheduling-v66-alert{background:rgba(255,255,255,.06);border-color:rgba(216,177,92,.25);color:#E4D6B8}html[data-workspace-theme='night'] .scheduling-v66-stat span{color:#E4D6B8}
@media(max-width:900px){.scheduling-v66-contract-summary{grid-template-columns:1fr 1fr 1fr}.scheduling-v66-contract-summary>div:first-child{grid-column:1/-1}.scheduling-v66-contract-editor{margin-top:8px}}
@media(max-width:620px){.scheduling-v66-contract-summary{grid-template-columns:1fr}.scheduling-v66-contract-summary>div:first-child{grid-column:1}.scheduling-v66-stat b{font-size:18px}}
`;

function esc(value: unknown) { return String(value ?? '').replace(/[&<>'"]/g, (c) => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' }[c] || c)); }
function ensureStyle(){ if(document.getElementById('scheduling-policy-v66-style')) return; const el=document.createElement('style'); el.id='scheduling-policy-v66-style'; el.textContent=STYLE; document.head.appendChild(el); }
function toast(message:string,error=false){ const old=document.querySelector('.scheduling-v66-toast'); old?.remove(); const el=document.createElement('div'); el.className=`scheduling-v65-toast scheduling-v66-toast${error?' error':''}`; el.textContent=message; document.body.appendChild(el); window.setTimeout(()=>el.remove(),4200); }
async function rpc(name:string,args:Record<string,unknown>){ if(!supabase) throw new Error('Supabase indisponível.'); const {data,error}=await supabase.rpc(name,args); if(error) throw error; return data as any; }
function closeModal(){ document.querySelector('[data-v66-modal]')?.remove(); const v65=document.querySelector('.scheduling-v65-modal-backdrop'); v65?.remove(); document.body.classList.remove('workspace-modal-open'); }
function openModal(title:string,kicker:string,body:string){ closeModal(); const wrap=document.createElement('div'); wrap.className='scheduling-v65-modal-backdrop'; wrap.dataset.v66Modal='1'; wrap.innerHTML=`<section class="scheduling-v65-modal"><div class="scheduling-v65-modal-head"><div><span class="scheduling-v65-kicker">${esc(kicker)}</span><h3>${esc(title)}</h3></div><button type="button" data-v66-close aria-label="Fechar">×</button></div>${body}</section>`; document.body.appendChild(wrap); document.body.classList.add('workspace-modal-open'); }
function modalError(message:string){ const box=document.querySelector<HTMLElement>('[data-v66-modal] .scheduling-v65-error'); if(box){ box.textContent=message; box.classList.add('show'); } }
function makeSlot(date:string,time:string,duration:number){ const start=new Date(`${date}T${time}:00-03:00`); return {startsAt:start.toISOString(),endsAt:new Date(start.getTime()+duration*60000).toISOString()}; }
function formatDateTime(value?:string|null){ if(!value) return ''; const d=new Date(value); if(Number.isNaN(d.getTime())) return ''; return new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit',timeZone:'America/Sao_Paulo'}).format(d); }
function formatDay(value?:string|null){ if(!value)return ''; const d=new Date(value); return new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'2-digit',year:'numeric',timeZone:'America/Sao_Paulo'}).format(d); }
function monthRange(){ const now=new Date(); const start=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-01`; const endDate=new Date(now.getFullYear(),now.getMonth()+1,0); const end=`${endDate.getFullYear()}-${String(endDate.getMonth()+1).padStart(2,'0')}-${String(endDate.getDate()).padStart(2,'0')}`; return {start,end}; }
function reasonLabel(reason?:string|null){ return ({client:'Cliente',cali:'CALI',external:'Fator externo',health:'Saúde',travel_vacation:'Viagem / férias',other:'Outro'} as Record<string,string>)[String(reason||'')] || 'Não informado'; }
function planDescription(a:AgendaCompliance){ if(a.plan==='partner') return '1 encontro online por mês, em data fixa organizada previamente pela CALI. O encontro não é cumulativo.'; if(a.plan==='full') return '2 encontros por mês, em ritmo quinzenal: 1 presencial + 1 online ou 2 online. A visita presencial não utilizada não acumula.'; return `${Number(a.sessionsPerMonth||0)} encontro(s) previsto(s) por mês${Number(a.cadenceDays||0)?` · referência de ${Number(a.cadenceDays)} dias entre encontros`:''}.`; }

async function decorateClient(){
  if(!supabase || location.pathname!=='/cliente/cronograma' || clientComplianceLoading) return;
  const host=document.getElementById('scheduling-v65-client-host'); const panel=host?.querySelector<HTMLElement>('.scheduling-v65-panel'); if(!host||!panel) return;
  panel.classList.add('scheduling-v66-contract-card');
  clientComplianceLoading=true;
  try{
    const {start,end}=monthRange();
    const [{data:agenda,error:agendaError},{data:reqs,error:reqError}]=await Promise.all([
      supabase.rpc('my_agenda_compliance_v66',{p_period_start:start,p_period_end:end}),
      supabase.from('scheduling_requests').select('id,company_id,status,request_mode,meeting_entitlement,contract_session_number,included_sessions_snapshot,cadence_days_snapshot,urgency_level,urgency_fee_applies,billable_extra,billing_acknowledged_at,billing_notice,service_plan_snapshot').order('created_at',{ascending:false}).limit(30),
    ]);
    if(agendaError) throw agendaError; if(reqError) throw reqError;
    const a=(agenda||{}) as AgendaCompliance; clientRequests=new Map(((reqs||[]) as SchedulingRequestV66[]).map(r=>[r.id,r]));
    panel.querySelector('.scheduling-v66-contract-summary')?.remove(); panel.querySelector('.scheduling-v66-alert')?.remove();
    const head=panel.querySelector('.scheduling-v65-head');
    const required=Number(a.requiredTotal||a.sessionsPerMonth||0), occurred=Number(a.occurredCount||0), notOccurred=Number(a.notOccurredCount||0), scheduled=Number(a.scheduledCount||0), pending=Number(a.pendingOutcomeCount||0), extras=Number(a.extraCount||0);
    const summary=document.createElement('div'); summary.className='scheduling-v66-contract-summary'; summary.innerHTML=`<div><small>${esc(a.label||'Agenda contratual')}</small><strong>${esc(planDescription(a))}</strong><p>O cliente pode solicitar análise de horário, mas a reserva só acontece depois da validação da CALI e da confirmação final.</p></div><div class="scheduling-v66-stat"><small>Realizados</small><b>${occurred}/${required}</b><span>no período</span></div><div class="scheduling-v66-stat"><small>Já agendados</small><b>${scheduled}</b><span>futuros</span></div><div class="scheduling-v66-stat"><small>Adicionais</small><b>${extras}</b><span>fora do pacote</span></div>`;
    head?.insertAdjacentElement('afterend',summary);
    if(notOccurred||pending){ const alert=document.createElement('div'); alert.className='scheduling-v66-alert'; alert.innerHTML=`${notOccurred?`<strong>${notOccurred} encontro(s) não realizado(s).</strong> A justificativa fica registrada no histórico e no relatório do período. `:''}${pending?`<strong>${pending} encontro(s) passado(s) ainda sem registro de realização.</strong>`:''}`; summary.insertAdjacentElement('afterend',alert); }
    decorateClientRequestCards();
  }catch(error){ console.error('Agenda V66 cliente',error); }
  finally{clientComplianceLoading=false;}
}

function decorateClientRequestCards(){
  for(const [id,r] of clientRequests){ const card=document.querySelector<HTMLElement>(`[data-scheduling-request-card="${CSS.escape(id)}"]`); if(!card) continue; card.querySelector('.scheduling-v66-request-meta')?.remove(); const top=card.querySelector('.scheduling-v65-request-top'); if(!top) continue; const meta=document.createElement('div'); meta.className='scheduling-v66-request-meta'; const total=Number(r.included_sessions_snapshot||0); const contractual=r.meeting_entitlement==='contractual'; meta.innerHTML=`<span class="scheduling-v65-badge ${contractual?'ok':'billable'}">${contractual?`Contratual${r.contract_session_number?` · encontro ${r.contract_session_number}/${total}`:''}`:'Adicional · cobrável'}</span>${r.urgency_fee_applies?'<span class="scheduling-v65-badge billable">Urgência · taxa adicional</span>':''}${Number(r.cadence_days_snapshot||0)>0&&contractual?`<span class="scheduling-v65-badge">Ritmo · ${Number(r.cadence_days_snapshot)} dias</span>`:''}`; top.insertAdjacentElement('afterend',meta);
    if(r.status==='client_review'&&(r.billable_extra||r.urgency_fee_applies)&&!r.billing_acknowledged_at&&!card.querySelector('[data-v66-accept-ack]')){ const actions=card.querySelector('.scheduling-v65-actions'); const ack=document.createElement('label'); ack.className='scheduling-v65-ack'; ack.innerHTML='<input type="checkbox" data-v66-accept-ack/> <span>Li e estou ciente da condição adicional informada pela CALI para este encontro.</span>'; actions?.insertAdjacentElement('beforebegin',ack); }
  }
}

async function previewClientPolicy(){
  const form=document.querySelector<HTMLFormElement>('#scheduling-client-form'); if(!form||!supabase) return;
  let urgency=form.querySelector<HTMLSelectElement>('[name="urgency"]');
  if(!urgency){ const duration=form.querySelector<HTMLSelectElement>('[name="duration"]')?.closest('.scheduling-v65-field'); const label=document.createElement('label'); label.className='scheduling-v65-field'; label.innerHTML='<span>Grau de urgência</span><select name="urgency"><option value="regular">Sem urgência</option><option value="priority">Prioridade</option><option value="urgent">Urgente</option></select>'; duration?.insertAdjacentElement('afterend',label); urgency=label.querySelector('select')!; }
  const mode=String(new FormData(form).get('mode')||'remote'), date=String(new FormData(form).get('date1')||''), time=String(new FormData(form).get('time1')||'09:00'); const policy=form.querySelector<HTMLElement>('#scheduling-client-policy'); if(!policy) return;
  if(!date){ policy.className='scheduling-v65-policy'; policy.innerHTML='<strong>Como funciona</strong>Escolha a primeira data para o Workspace verificar automaticamente se o pedido está dentro da agenda contratual do mês ou se será um encontro adicional.'; return; }
  try{ const start=new Date(`${date}T${time||'09:00'}:00-03:00`).toISOString(); const {data,error}=await supabase.rpc('preview_my_scheduling_policy_v66',{p_mode:mode,p_start:start,p_urgency:urgency?.value||'regular'}); if(error)throw error; const p=(data||{}) as AgendaCompliance; policy.className=`scheduling-v65-policy ${p.requiresAcknowledgement?'billable':''}`; policy.innerHTML=`<strong>${p.entitlement==='contractual'?'Dentro da agenda contratual':'Condição adicional'}</strong>${esc(p.notice||'A solicitação seguirá para análise da CALI.')}${p.recommendedNextAt?`<div style="margin-top:7px"><b>Referência do próximo encontro:</b> por volta de ${esc(formatDay(p.recommendedNextAt))}.</div>`:''}${p.requiresAcknowledgement?'<label class="scheduling-v65-ack"><input type="checkbox" name="billingAck"/> <span>Li e estou ciente desta condição para enviar a solicitação.</span></label>':''}`; }
  catch(error:any){ policy.className='scheduling-v65-policy billable'; policy.innerHTML=`<strong>Revise a solicitação</strong>${esc(error?.message||'Não foi possível validar a regra da agenda.')}`; }
}

async function submitClientV2(form:HTMLFormElement,event:Event){
  event.preventDefault(); event.stopImmediatePropagation();
  const fd=new FormData(form), mode=String(fd.get('mode')||'remote'), duration=Number(fd.get('duration')||60), date1=String(fd.get('date1')||''),time1=String(fd.get('time1')||''),date2=String(fd.get('date2')||''),time2=String(fd.get('time2')||''),urgency=String(fd.get('urgency')||'regular');
  if(!date1||!time1||(mode==='in_person'&&(!date2||!time2))){ const box=form.querySelector<HTMLElement>('.scheduling-v65-error'); if(box){box.textContent=mode==='in_person'?'Informe duas opções de data e horário para a visita presencial.':'Informe ao menos uma opção de data e horário.';box.classList.add('show');} return; }
  const slots=[makeSlot(date1,time1,duration)]; if(date2&&time2)slots.push(makeSlot(date2,time2,duration)); const ack=Boolean(fd.get('billingAck')); const button=form.querySelector<HTMLButtonElement>('button[type="submit"]'); if(button)button.disabled=true;
  try{ await rpc('create_scheduling_request_v2',{p_mode:mode,p_title:String(fd.get('title')||''),p_purpose:String(fd.get('purpose')||''),p_location:String(fd.get('location')||''),p_requested_slots:slots,p_urgency:urgency,p_billing_acknowledged:ack}); closeModal(); toast('Solicitação enviada para análise da CALI.'); window.setTimeout(()=>location.reload(),650); }
  catch(error:any){ const box=form.querySelector<HTMLElement>('.scheduling-v65-error'); if(box){box.textContent=error?.message||'Não foi possível enviar a solicitação.';box.classList.add('show');} if(button)button.disabled=false; }
}

async function acceptClientV2(button:HTMLElement,event:Event){
  event.preventDefault(); event.stopImmediatePropagation(); const id=String(button.dataset.schedulingClientAccept||''), index=Number(button.dataset.slotIndex||0), card=button.closest<HTMLElement>('[data-scheduling-request-card]'); const ack=Boolean(card?.querySelector<HTMLInputElement>('[data-v66-accept-ack]')?.checked||card?.querySelector<HTMLInputElement>('[data-scheduling-accept-ack]')?.checked); button.setAttribute('disabled','true');
  try{ const result=await rpc('client_accept_scheduling_proposal_v2',{p_request_id:id,p_slot_index:index,p_billing_acknowledged:ack}); if(result?.event_id&&supabase){ const sync=await supabase.functions.invoke('workspace-sync-scheduled-event',{body:{eventId:result.event_id}}); if(sync.error||sync.data?.error) toast('Horário confirmado no Workspace. A sincronização com o Google ficou pendente para nova tentativa.',true); else toast('Horário confirmado. O compromisso entrou no Workspace e no Google Calendar.'); } window.setTimeout(()=>location.reload(),700); }
  catch(error:any){ toast(error?.message||'Não foi possível confirmar o horário.',true); button.removeAttribute('disabled'); }
}

async function decorateAdmin(){
  if(!supabase||location.pathname!=='/admin/calendario'||adminLoading)return; const host=document.getElementById('scheduling-v65-admin-host'); if(!host)return; adminLoading=true;
  try{ const [{data:companies,error:ce},{data:reqs,error:re}]=await Promise.all([supabase.from('companies').select('id,display_name,service_plan,meeting_sessions_included_per_month,meeting_cadence_days,meeting_mode_policy,fixed_meeting_required,onsite_visits_included_per_month').neq('status','archived').order('display_name'),supabase.from('scheduling_requests').select('id,company_id,status,request_mode,meeting_entitlement,contract_session_number,included_sessions_snapshot,cadence_days_snapshot,urgency_level,urgency_fee_applies,billable_extra,billing_acknowledged_at,billing_notice,service_plan_snapshot').order('created_at',{ascending:false}).limit(60)]); if(ce)throw ce;if(re)throw re; adminCompanies=(companies||[]) as CompanyV66[]; adminRequests=new Map(((reqs||[]) as SchedulingRequestV66[]).map(r=>[r.id,r])); const btn=host.querySelector<HTMLElement>('[data-scheduling-admin-contract]'); if(btn)btn.textContent='Configurar agenda do contrato'; for(const [id,r] of adminRequests){ const card=host.querySelector<HTMLElement>(`[data-admin-request="${CSS.escape(id)}"]`); if(!card)continue; card.querySelector('.scheduling-v66-request-meta')?.remove(); const top=card.querySelector('.scheduling-v65-request-top'); if(!top)continue; const meta=document.createElement('div');meta.className='scheduling-v66-request-meta'; const total=Number(r.included_sessions_snapshot||0);meta.innerHTML=`<span class="scheduling-v65-badge ${r.meeting_entitlement==='contractual'?'ok':'billable'}">${r.meeting_entitlement==='contractual'?`Contratual${r.contract_session_number?` · ${r.contract_session_number}/${total}`:''}`:'Adicional · cobrável'}</span><label><select class="scheduling-v66-urgency-select" data-v66-urgency="${esc(id)}"><option value="regular" ${r.urgency_level==='regular'?'selected':''}>Sem urgência</option><option value="priority" ${r.urgency_level==='priority'?'selected':''}>Prioridade · taxa</option><option value="urgent" ${r.urgency_level==='urgent'?'selected':''}>Urgente · taxa</option></select></label>${r.urgency_fee_applies?'<span class="scheduling-v65-badge billable">Taxa de urgência</span>':''}`;top.insertAdjacentElement('afterend',meta); } }
  catch(error){console.error('Agenda V66 admin',error);}finally{adminLoading=false;}
  void decorateCalendarEditor(); void decorateCalendarDetail();
}

function openContractConfigV66(){
  if(!adminCompanies.length)return; const options=adminCompanies.map(c=>`<option value="${esc(c.id)}">${esc(c.display_name)}</option>`).join(''); openModal('Agenda contratual do cliente','REGRA DO PACOTE',`<form class="scheduling-v65-form" id="v66-contract-form"><div class="scheduling-v65-grid"><label class="scheduling-v65-field full"><span>Cliente</span><select name="companyId" required>${options}</select></label><label class="scheduling-v65-field"><span>Pacote</span><select name="plan"><option value="partner">CALI Partner</option><option value="full">CALI Full</option><option value="custom">Personalizado</option></select></label><label class="scheduling-v65-field"><span>Encontros por mês</span><input type="number" name="sessions" min="0" max="12" value="1"/></label><label class="scheduling-v65-field"><span>Referência entre encontros</span><input type="number" name="cadence" min="0" max="60" value="30"/></label><label class="scheduling-v65-field"><span>Presenciais incluídos / mês</span><input type="number" name="onsite" min="0" max="12" value="0"/></label></div><div class="scheduling-v65-policy"><strong>Regras padrão</strong><b>CALI Partner:</b> 1 encontro mensal, online, previamente organizado pela CALI. <b>CALI Full:</b> 2 encontros em ritmo quinzenal; 1 presencial + 1 online ou 2 online. Nenhuma disponibilidade é cumulativa.</div><div class="scheduling-v65-error"></div><div class="scheduling-v65-modal-actions"><button type="button" class="scheduling-v65-button" data-v66-close>Cancelar</button><button type="submit" class="scheduling-v65-button primary">Salvar regra</button></div></form>`); syncContractForm();
}
function syncContractForm(){ const form=document.querySelector<HTMLFormElement>('#v66-contract-form');if(!form)return; const cid=(form.elements.namedItem('companyId') as HTMLSelectElement)?.value,c=adminCompanies.find(x=>x.id===cid);if(!c)return; const plan=String(c.service_plan||'custom').toLowerCase();(form.elements.namedItem('plan') as HTMLSelectElement).value=['partner','full'].includes(plan)?plan:'custom';(form.elements.namedItem('sessions') as HTMLInputElement).value=String(c.meeting_sessions_included_per_month||0);(form.elements.namedItem('cadence') as HTMLInputElement).value=String(c.meeting_cadence_days||0);(form.elements.namedItem('onsite') as HTMLInputElement).value=String(c.onsite_visits_included_per_month||0); }
function applyPlanDefaults(form:HTMLFormElement){const plan=String((form.elements.namedItem('plan') as HTMLSelectElement)?.value||'custom');if(plan==='partner'){(form.elements.namedItem('sessions') as HTMLInputElement).value='1';(form.elements.namedItem('cadence') as HTMLInputElement).value='30';(form.elements.namedItem('onsite') as HTMLInputElement).value='0';}if(plan==='full'){(form.elements.namedItem('sessions') as HTMLInputElement).value='2';(form.elements.namedItem('cadence') as HTMLInputElement).value='14';(form.elements.namedItem('onsite') as HTMLInputElement).value='1';}}
async function submitContractForm(form:HTMLFormElement,event:Event){event.preventDefault();event.stopImmediatePropagation();if(!supabase)return;const fd=new FormData(form),companyId=String(fd.get('companyId')||''),plan=String(fd.get('plan')||'custom'),sessions=Number(fd.get('sessions')||0),cadence=Number(fd.get('cadence')||0),onsite=Number(fd.get('onsite')||0);const payload:any={service_plan:plan==='custom'?null:plan,meeting_sessions_included_per_month:sessions,meeting_cadence_days:cadence,onsite_visits_included_per_month:onsite,fixed_meeting_required:sessions>0,meeting_mode_policy:plan==='partner'?'online_only':plan==='full'?'mixed_one_onsite':'custom'};const {error}=await supabase.from('companies').update(payload).eq('id',companyId);if(error){modalError(error.message);return;}closeModal();toast('Agenda contratual atualizada.');void decorateAdmin();}

function labelControl<T extends HTMLElement>(form:HTMLElement,labelText:string,selector:string){ const label=Array.from(form.querySelectorAll('label')).find(l=>String(l.textContent||'').trim().toLowerCase().startsWith(labelText.toLowerCase())); return label?.querySelector<T>(selector)||null; }
async function decorateCalendarEditor(){ const form=document.querySelector<HTMLFormElement>('.calendar-event-modal');if(!form||form.querySelector('[data-v66-calendar-class]'))return; const body=form.querySelector<HTMLElement>('.calendar-modal-body');if(!body)return; const block=document.createElement('div');block.className='scheduling-v66-contract-editor';block.dataset.v66CalendarClass='1';block.innerHTML='<strong>Agenda contratual</strong><p>Para Partner e Full, use “Encontro contratual” nos encontros fixos previamente agendados pela CALI. O Workspace controla a quantidade mensal e classifica excedentes como adicionais.</p><select data-v66-event-class><option value="contractual">Encontro contratual</option><option value="extra">Encontro adicional · cobrável</option><option value="other">Não conta na agenda contratual</option></select>';body.appendChild(block); const protocol=String(form.querySelector('.calendar-modal-protocol')?.textContent||'').match(/CALI-[A-Z]+-\d{4}-\d+/i)?.[0];if(protocol&&supabase){const {data}=await supabase.from('events').select('schedule_class').eq('protocol',protocol).maybeSingle();const select=block.querySelector<HTMLSelectElement>('select');if(select&&data?.schedule_class)select.value=String(data.schedule_class);}}
async function classifySavedCalendarEvent(form:HTMLFormElement){ if(!supabase)return; const classSelect=form.querySelector<HTMLSelectElement>('[data-v66-event-class]');if(!classSelect)return; const company=labelControl<HTMLSelectElement>(form,'Cliente','select'),type=labelControl<HTMLSelectElement>(form,'Tipo','select'),date=labelControl<HTMLInputElement>(form,'Data','input[type="date"]'),title=form.querySelector<HTMLInputElement>('.calendar-title-field input');if(!company?.value||type?.value!=='meeting'||!title?.value)return; const protocol=String(form.querySelector('.calendar-modal-protocol')?.textContent||'').match(/CALI-[A-Z]+-\d{4}-\d+/i)?.[0]||'';const companyId=company.value,day=date?.value||'',name=title.value.trim(),classification=classSelect.value;window.setTimeout(async()=>{let q=supabase!.from('events').select('id').eq('company_id',companyId).eq('title',name).eq('event_type','meeting').order('created_at',{ascending:false}).limit(1);if(protocol)q=q.eq('protocol',protocol);else if(day){q=q.gte('starts_at',`${day}T00:00:00-03:00`).lte('starts_at',`${day}T23:59:59-03:00`);}const {data}=await q.maybeSingle();if(!data?.id)return;try{await rpc('admin_classify_calendar_event_v66',{p_event_id:data.id,p_contractual:classification==='contractual',p_billable:classification==='extra'});}catch(error){console.error('Classificação da agenda contratual',error);}},1000);}

async function decorateCalendarDetail(){ const modal=document.querySelector<HTMLElement>('.calendar-detail-modal');if(!modal||modal.querySelector('[data-v66-event-status]')||!supabase)return;const protocol=String(modal.querySelector('.calendar-protocol-badge')?.textContent||'').match(/CALI-[A-Z]+-\d{4}-\d+/i)?.[0];if(!protocol)return;const {data:event}=await supabase.from('events').select('id,starts_at,event_type,schedule_class,contract_session_number,mode,billing_applies,billing_reason,source_type').eq('protocol',protocol).maybeSingle();if(!event||event.event_type!=='meeting')return;const {data:outcome}=await supabase.from('event_outcomes').select('outcome,reason_category,justified,note,marked_at').eq('event_id',event.id).maybeSingle();const body=modal.querySelector<HTMLElement>('.calendar-detail-body');if(!body)return;const box=document.createElement('div');box.className='scheduling-v66-event-status';box.dataset.v66EventStatus='1';const classLabel=event.schedule_class==='contractual'?`Contratual${event.contract_session_number?` · encontro ${event.contract_session_number}`:''}`:event.schedule_class==='extra'?'Adicional · cobrável':'Fora da agenda contratual';box.innerHTML=`<strong>Agenda contratual · ${esc(classLabel)}</strong><br>${event.mode==='in_person'?'Presencial':'Online'}${event.billing_applies?` · ${esc(event.billing_reason||'Condição adicional')}`:''}${outcome?`<br><b>Resultado:</b> ${outcome.outcome==='occurred'?'Realizado':`Não realizado · ${esc(reasonLabel(outcome.reason_category))}`}${outcome.note?` · ${esc(outcome.note)}`:''}`:''}`;if(!outcome&&new Date(event.starts_at).getTime()<Date.now()){const actions=document.createElement('div');actions.className='scheduling-v66-event-actions';actions.innerHTML=`<button type="button" class="scheduling-v65-button primary" data-v66-outcome-ok="${esc(event.id)}" data-source="${esc(event.source_type||'manual')}">Marcar realizado</button><button type="button" class="scheduling-v65-button danger" data-v66-outcome-no="${esc(event.id)}" data-source="${esc(event.source_type||'manual')}">Não ocorreu</button>`;box.appendChild(actions);}body.appendChild(box);}
function openOutcomeModal(eventId:string,source:string){openModal('Registrar não ocorrência','HISTÓRICO DA AGENDA',`<form class="scheduling-v65-form" id="v66-outcome-form" data-event-id="${esc(eventId)}" data-source="${esc(source)}"><div class="scheduling-v65-grid"><label class="scheduling-v65-field"><span>Motivo</span><select name="reason" required><option value="">Selecione</option><option value="client">Cliente</option><option value="cali">CALI</option><option value="external">Fator externo</option><option value="health">Saúde</option><option value="travel_vacation">Viagem / férias</option><option value="other">Outro</option></select></label><label class="scheduling-v65-field"><span>Houve justificativa?</span><select name="justified"><option value="true">Sim</option><option value="false">Não</option></select></label><label class="scheduling-v65-field full"><span>Justificativa / registro</span><textarea name="note" required placeholder="Registre objetivamente o que impediu a realização."></textarea></label></div><div class="scheduling-v65-policy"><strong>Registro mensal</strong>O resultado deste encontro passa a compor o histórico da agenda e o relatório do período. Encontros não realizados não acumulam para o mês seguinte.</div><div class="scheduling-v65-error"></div><div class="scheduling-v65-modal-actions"><button type="button" class="scheduling-v65-button" data-v66-close>Cancelar</button><button type="submit" class="scheduling-v65-button danger">Registrar</button></div></form>`);}

async function decorateReports(){ if(!supabase)return; const papers=document.querySelectorAll<HTMLElement>('.reports-v16-paper-one');for(const paper of papers){if(paper.querySelector('.reports-v66-agenda')||paper.dataset.v66AgendaLoading==='1')continue;const protocol=String(paper.querySelector('.reports-v19-meta strong')?.textContent||'').trim();if(!protocol||protocol==='—')continue;paper.dataset.v66AgendaLoading='1';try{const {data}=await supabase.from('reports').select('source_snapshot').eq('protocol',protocol).maybeSingle();const a=(data?.source_snapshot as any)?.agendaCompliance as AgendaCompliance|undefined;if(!a||(!Number(a.requiredTotal||0)&&!Number(a.extraCount||0)))continue;const notItems=(a.items||[]).filter(i=>i.outcome==='not_occurred');const pending=Number(a.pendingOutcomeCount||0);const section=document.createElement('section');section.className='reports-v66-agenda';section.innerHTML=`<div class="reports-v66-agenda-head"><div><small>AGENDA CONTRATUAL DO PERÍODO</small><h2>Encontros previstos e realização</h2></div><span>${esc(a.label||'CALI')} · não cumulativo</span></div><div class="reports-v66-agenda-grid"><div><small>Previstos</small><strong>${Number(a.requiredTotal||0)}</strong></div><div><small>Realizados</small><strong>${Number(a.occurredCount||0)}</strong></div><div><small>Não realizados</small><strong>${Number(a.notOccurredCount||0)}</strong></div><div><small>Adicionais</small><strong>${Number(a.extraCount||0)}</strong></div></div><p class="reports-v66-agenda-note"><b>Formato contratual:</b> ${Number(a.remoteContractualCount||0)} online · ${Number(a.inPersonContractualCount||0)} presencial.${notItems.length?` <b>Não ocorrência:</b> ${notItems.map(i=>`${formatDay(i.startsAt)} · ${reasonLabel(i.reasonCategory)}${i.note?` (${i.note})`:''}`).join('; ')}.`:''}${pending?` <b>Pendente:</b> ${pending} encontro(s) passado(s) ainda sem registro de realização.`:''}</p>`;const changes=paper.querySelector('.reports-v16-changes'),footer=paper.querySelector('.reports-v16-footer');if(changes)changes.insertAdjacentElement('beforebegin',section);else footer?.insertAdjacentElement('beforebegin',section);}catch(error){console.error('Agenda no relatório V66',error);}finally{delete paper.dataset.v66AgendaLoading;}}
}

function scheduleDecorate(){window.clearTimeout(renderTimer);renderTimer=window.setTimeout(()=>{void decorateClient();void decorateAdmin();void decorateReports();if(location.pathname==='/cliente/cronograma')void previewClientPolicy();},120);}

function handleWindowClick(event:MouseEvent){const target=event.target as HTMLElement|null;if(!target)return;if(target.closest('[data-v66-close]')){event.preventDefault();event.stopImmediatePropagation();closeModal();return;}const accept=target.closest<HTMLElement>('[data-scheduling-client-accept]');if(accept){void acceptClientV2(accept,event);return;}if(target.closest('[data-scheduling-admin-contract]')){event.preventDefault();event.stopImmediatePropagation();openContractConfigV66();return;}const ok=target.closest<HTMLElement>('[data-v66-outcome-ok]');if(ok){event.preventDefault();event.stopImmediatePropagation();const id=String(ok.dataset.v66OutcomeOk||''),source=String(ok.dataset.source||'');void (async()=>{try{if(source==='scheduling_request')await rpc('admin_mark_scheduling_event_outcome_v1',{p_event_id:id,p_outcome:'occurred',p_reason_category:null,p_justified:false,p_note:'',p_convert_to_virtual:false});else await rpc('admin_mark_calendar_event_outcome_v66',{p_event_id:id,p_outcome:'occurred',p_reason_category:null,p_justified:false,p_note:''});toast('Encontro registrado como realizado.');location.reload();}catch(error:any){toast(error?.message||'Não foi possível registrar o resultado.',true);}})();return;}const no=target.closest<HTMLElement>('[data-v66-outcome-no]');if(no){event.preventDefault();event.stopImmediatePropagation();openOutcomeModal(String(no.dataset.v66OutcomeNo||''),String(no.dataset.source||''));return;}}

function handleWindowSubmit(event:SubmitEvent){const form=event.target as HTMLFormElement|null;if(!form)return;if(form.id==='scheduling-client-form'){void submitClientV2(form,event);return;}if(form.id==='v66-contract-form'){void submitContractForm(form,event);return;}if(form.id==='v66-outcome-form'){event.preventDefault();event.stopImmediatePropagation();const fd=new FormData(form),id=String(form.dataset.eventId||''),source=String(form.dataset.source||''),reason=String(fd.get('reason')||''),justified=String(fd.get('justified')||'false')==='true',note=String(fd.get('note')||'');void(async()=>{try{if(source==='scheduling_request')await rpc('admin_mark_scheduling_event_outcome_v1',{p_event_id:id,p_outcome:'not_occurred',p_reason_category:reason,p_justified:justified,p_note:note,p_convert_to_virtual:false});else await rpc('admin_mark_calendar_event_outcome_v66',{p_event_id:id,p_outcome:'not_occurred',p_reason_category:reason,p_justified:justified,p_note:note});closeModal();toast('Não ocorrência registrada.');location.reload();}catch(error:any){modalError(error?.message||'Não foi possível registrar.');}})();return;}if(form.matches('.calendar-event-modal'))void classifySavedCalendarEvent(form);}
function handleWindowChange(event:Event){const target=event.target as HTMLInputElement|HTMLSelectElement|null;if(!target)return;if(target.closest('#scheduling-client-form')&&['mode','date1','time1','urgency'].includes(target.name)){window.setTimeout(()=>void previewClientPolicy(),20);}const urgency=target.closest<HTMLSelectElement>('[data-v66-urgency]');if(urgency){const id=String(urgency.dataset.v66Urgency||'');void(async()=>{try{await rpc('admin_set_scheduling_urgency_v66',{p_request_id:id,p_urgency:urgency.value});toast('Urgência da solicitação atualizada.');void decorateAdmin();}catch(error:any){toast(error?.message||'Não foi possível atualizar a urgência.',true);}})();return;}if(target.closest('#v66-contract-form')&&target.name==='companyId')syncContractForm();if(target.closest('#v66-contract-form')&&target.name==='plan')applyPlanDefaults(target.closest('form') as HTMLFormElement);}

export function installSchedulingPolicyRuntimeV66(){if(installed)return;installed=true;ensureStyle();window.addEventListener('click',handleWindowClick,true);window.addEventListener('submit',handleWindowSubmit,true);window.addEventListener('change',handleWindowChange,true);observer=new MutationObserver(scheduleDecorate);observer.observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('popstate',scheduleDecorate);window.setTimeout(scheduleDecorate,180);}

installSchedulingPolicyRuntimeV66();
