import { useState } from 'react';
import { createPortal } from 'react-dom';
import { ArrowLeft, ArrowRight, Check, Plus, Trash2, X } from 'lucide-react';
import { supabase } from '../../lib/supabase';
import type { Draft, Member, Vacancy } from './CompanyTeamPage';
type Row=Record<string,string>;
type Job=Pick<Vacancy,'vacancy_code'|'title'|'department'|'opened_on'|'status'|'closed_on'>;
const titles=['Desligamentos','Contratações','Mudanças','Vagas','Confirmar'];
const fields: {key:string;label:string;type?:string}[][]=[
  [{key:'code',label:'Pessoa'},{key:'date',label:'Data',type:'date'},{key:'initiative',label:'Iniciativa'},{key:'reason',label:'Motivo'},{key:'notice',label:'Aviso prévio'}],
  [{key:'code',label:'Código interno'},{key:'name',label:'Nome completo'},{key:'date',label:'Admissão',type:'date'},{key:'title',label:'Cargo'},{key:'department',label:'Departamento'}],
  [{key:'code',label:'Pessoa'},{key:'title',label:'Novo cargo'},{key:'department',label:'Novo departamento'},{key:'manager',label:'Novo gestor'}]
];
const monthEnd=(month:string)=>month+'-'+new Date(Number(month.slice(0,4)),Number(month.slice(5,7)),0).getDate();
export function TeamMonthWizard({companyId,month,members,vacancies,serialize,onClose,onSaved}:{companyId:string;month:string;members:Member[];vacancies:Vacancy[];serialize:(draft:Draft)=>Record<string,unknown>;onClose:()=>void;onSaved:()=>Promise<void>}){
 const [stage,setStage]=useState(0),[rows,setRows]=useState<Row[][]>([[],[],[]]),[jobs,setJobs]=useState<Job[]>(vacancies.filter(v=>v.status==='open'&&v.opened_on<=monthEnd(month)).map(v=>({vacancy_code:v.vacancy_code,title:v.title,department:v.department,opened_on:v.opened_on,status:v.status,closed_on:v.closed_on}))),[error,setError]=useState(''),[saving,setSaving]=useState(false);
 const max=[monthEnd(month),new Date().toISOString().slice(0,10)].sort()[0];
 const update=(i:number,key:string,value:string)=>setRows(all=>all.map((list,s)=>s===stage?list.map((r,j)=>j===i?{...r,[key]:value}:r):list));
 const updateJob=(i:number,key:keyof Job,value:string)=>setJobs(list=>list.map((v,j)=>j===i?{...v,[key]:value,...(key==='status'&&value==='open'?{closed_on:null}:{})}:v));
 function next(){setError('');if(stage<2&&rows[stage].some(r=>fields[stage].some(f=>!r[f.key])))return setError('Complete os dados ou remova a linha vazia.');if(stage===2&&rows[2].some(r=>!r.code||(!r.title&&!r.department&&!r.manager)))return setError('Informe a pessoa e pelo menos uma mudança.');if(stage===3&&jobs.some(j=>!j.title||!j.opened_on||(j.status!=='open'&&!j.closed_on)))return setError('Complete as vagas antes de avançar.');setStage(stage+1)}
 async function save(){if(!supabase||saving)return;setSaving(true);setError('');try{const byCode=new Map(members.map(m=>[m.employee_code,{...m}])),touched=new Set<string>();for(const r of rows[0]){const m=byCode.get(r.code);if(!m)throw Error('Pessoa não encontrada.');Object.assign(m,{status:'terminated',termination_date:r.date,termination_initiative:r.initiative,termination_reason:r.reason,notice_type:r.notice});touched.add(r.code)}for(const r of rows[2]){const m=byCode.get(r.code);if(!m)throw Error('Pessoa não encontrada.');if(r.title)m.job_title=r.title;if(r.department)m.department=r.department;if(r.manager)m.manager_code=r.manager;touched.add(r.code)}for(const r of rows[1]){if(byCode.has(r.code))throw Error('O código da contratação já existe.');byCode.set(r.code,{employee_code:r.code,full_name:r.name,admission_date:r.date,job_title:r.title,department:r.department,employment_type:'clt',status:'active'} as Member);touched.add(r.code)}const people=[...touched].map(code=>serialize({...byCode.get(code),salary:'',gender:'',gender_detail:'',has_children:'',optional_data_declared:false} as Draft));const result=await supabase.rpc('confirm_team_month_v2',{p_company_id:companyId,p_reference_month:month+'-01',p_people:people,p_vacancies:jobs,p_answers:{departures:rows[0].length,admissions:rows[1].length,changes:rows[2].length,vacancies:jobs.length}});if(result.error)throw result.error;await onSaved();onClose()}catch(e){setError(e instanceof Error?e.message:'Não foi possível confirmar o mês.')}finally{setSaving(false)}}
 return createPortal(<div className="team-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="team-modal team-review" role="dialog" aria-modal="true" aria-label="Atualização mensal"><header><div><span className="team-eyebrow">EQUIPE · {month}</span><h2>O que mudou neste mês?</h2></div><button className="team-close" onClick={onClose} aria-label="Fechar"><X/></button></header><div className="team-review-body"><div className="team-step-track">{titles.map((t,i)=><span key={t} className={i===stage?'active':''} title={t}>{i+1}</span>)}</div><h3>{titles[stage]}</h3>{stage<3&&<><p>{['Houve algum desligamento? Se não, avance.','Cadastre novas pessoas. Você também pode fazer isso durante o mês.','Registre promoções e trocas de área ou gestor.'][stage]}</p>{rows[stage].map((r,i)=><div className="team-review-row" key={i}>{fields[stage].map(f=>f.key==='code'&&stage!==1?<select key={f.key} aria-label={f.label} value={r.code||''} onChange={e=>update(i,'code',e.target.value)}><option value="">Selecione a pessoa</option>{members.filter(m=>m.status!=='terminated').map(m=><option key={m.id} value={m.employee_code}>{m.full_name}</option>)}</select>:f.key==='initiative'?<select key={f.key} aria-label={f.label} value={r.initiative||''} onChange={e=>update(i,'initiative',e.target.value)}><option value="">Iniciativa</option><option value="employee">Pedido da pessoa</option><option value="company">Empresa</option><option value="contract_end">Fim do contrato</option><option value="other">Outro</option></select>:f.key==='notice'?<select key={f.key} aria-label={f.label} value={r.notice||''} onChange={e=>update(i,'notice',e.target.value)}><option value="">Aviso prévio</option><option value="worked">Trabalhado</option><option value="indemnified">Indenizado</option><option value="waived">Dispensado</option><option value="not_applicable">Não se aplica</option></select>:<input key={f.key} aria-label={f.label} placeholder={f.label} type={f.type||'text'} max={f.type==='date'?max:undefined} value={r[f.key]||''} onChange={e=>update(i,f.key,e.target.value)}/>)}<button aria-label="Remover linha" onClick={()=>setRows(all=>all.map((list,s)=>s===stage?list.filter((_,j)=>j!==i):list))}><Trash2 size={17}/></button></div>)}<button className="team-add-line" onClick={()=>setRows(all=>all.map((list,s)=>s===stage?[...list,{}]:list))}><Plus size={16}/> Adicionar {['desligamento','contratação','mudança'][stage]}</button></>}
 {stage===3&&<><p>Uma vaga aberta segue para o mês seguinte até ser preenchida ou cancelada.</p>{jobs.map((v,i)=><div className="team-review-row" key={v.vacancy_code}><input aria-label="Nome da vaga" placeholder="Nome da vaga" value={v.title} onChange={e=>updateJob(i,'title',e.target.value)}/><input aria-label="Departamento" placeholder="Departamento" value={v.department||''} onChange={e=>updateJob(i,'department',e.target.value)}/><label>Aberta em<input type="date" max={max} value={v.opened_on} readOnly={vacancies.some(old=>old.vacancy_code===v.vacancy_code)} onChange={e=>updateJob(i,'opened_on',e.target.value)}/></label><select aria-label="Situação" value={v.status} onChange={e=>updateJob(i,'status',e.target.value)}><option value="open">Em andamento</option><option value="filled">Preenchida</option><option value="cancelled">Cancelada</option></select>{v.status!=='open'&&<label>Encerrada em<input type="date" min={v.opened_on} max={max} value={v.closed_on||''} onChange={e=>updateJob(i,'closed_on',e.target.value)}/></label>}{!vacancies.some(old=>old.vacancy_code===v.vacancy_code)&&<button aria-label="Remover vaga" onClick={()=>setJobs(jobs.filter((_,j)=>j!==i))}><Trash2 size={17}/></button>}</div>)}<button className="team-add-line" onClick={()=>setJobs([...jobs,{vacancy_code:crypto.randomUUID(),title:'',department:'',opened_on:'',status:'open',closed_on:null}])}><Plus size={16}/> Adicionar vaga</button></>}
 {stage===4&&<div className="team-review-summary"><p>Pessoas ausentes desta revisão continuam na equipe.</p>{[...rows.map(list=>list.length),jobs.length].map((n,i)=><div key={i}><strong>{n}</strong><span>{['desligamentos','contratações','mudanças','vagas acompanhadas'][i]}</span></div>)}</div>}</div><footer>{error&&<span className="team-inline-error" role="alert">{error}</span>}{stage>0&&<button className="team-btn secondary" onClick={()=>{setError('');setStage(stage-1)}}><ArrowLeft size={16}/> Voltar</button>}{stage<4?<button className="team-btn" onClick={next}>Continuar <ArrowRight size={16}/></button>:<button className="team-btn" disabled={saving} onClick={()=>void save()}><Check size={16}/> {saving?'Salvando…':'Confirmar mês'}</button>}</footer></section></div>,document.body)
}
