import { useEffect, useState, type FormEvent } from 'react';
import { createPortal } from 'react-dom';
import { CalendarClock, X } from 'lucide-react';
import { supabase } from '../lib/supabase';
import './agenda-change-inbox.css';

type Slot = {startsAt:string;endsAt:string};
type Request = {id:string;event_id:string;company_id:string;action:string;reason:string;slots:Slot[];status:string;original_starts_at:string;created_at:string;decision_note?:string|null};
const date=(value:string)=>new Intl.DateTimeFormat('pt-BR',{dateStyle:'long',timeStyle:'short',timeZone:'America/Sao_Paulo'}).format(new Date(value));

export function AgendaChangeInbox({onDecision}:{onDecision:()=>void}) {
  const [rows,setRows]=useState<Request[]>([]),[titles,setTitles]=useState<Record<string,string>>({}),[companyNames,setCompanies]=useState<Record<string,string>>({});
  const [active,setActive]=useState<Request|null>(null),[index,setIndex]=useState(0),[note,setNote]=useState(''),[approve,setApprove]=useState(true),[slot,setSlot]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState('');
  async function load(){if(!supabase)return;const {data}=await supabase.from('agenda_change_requests').select('id,event_id,company_id,action,reason,slots,status,original_starts_at,created_at,decision_note').order('created_at',{ascending:false}).limit(100);const result=(data||[]) as Request[];setRows(result);const ids=[...new Set(result.map(row=>row.event_id))], cids=[...new Set(result.map(row=>row.company_id))];if(ids.length){const {data:events}=await supabase.from('events').select('id,title').in('id',ids);setTitles(Object.fromEntries((events||[]).map(row=>[row.id,row.title])));}if(cids.length){const {data:companies}=await supabase.from('companies').select('id,display_name').in('id',cids);setCompanies(Object.fromEntries((companies||[]).map(row=>[row.id,row.display_name])));}}
  useEffect(()=>{void load();if(!supabase)return;const channel=supabase.channel('agenda-change-admin').on('postgres_changes',{event:'*',schema:'cali_workspace',table:'agenda_change_requests'},()=>void load()).subscribe();return()=>{void supabase?.removeChannel(channel)}},[]);
  async function decide(event:FormEvent){event.preventDefault();if(!supabase||!active)return;setBusy(true);setError('');const {data,failure}=await (async()=>{const r=await supabase.rpc('admin_decide_agenda_change_v1',{p_change_id:active.id,p_approve:approve,p_note:note.trim(),p_slot_index:slot});return {data:r.data,failure:r.error}})();if(failure)setError(failure.message);else{if(approve&&data?.event_id){const {error:syncError}=await supabase.functions.invoke('google-calendar-oauth',{body:{action:data.action==='cancel'?'cancel_event':'sync_event',eventId:data.event_id}});if(syncError)setError('Decisão salva no Workspace. A sincronização com o Google ficou pendente.');}setActive(null);setNote('');await load();onDecision();}setBusy(false);}
  const pending=rows.filter(row=>row.status==='pending');
  return <div className="agenda-change-inbox"><button type="button" className="agenda-change-trigger" disabled={!pending.length} title={pending.length ? `${pending.length} pedido(s) aguardando análise` : 'Nenhum pedido pendente'} onClick={()=>{setActive(pending[index%pending.length]);setNote('');setApprove(true);setSlot(0);setError('')}}><CalendarClock size={17}/> Alterações de reuniões {pending.length>0&&<b>{pending.length}</b>}</button>
  {pending.length>1&&<span className="agenda-change-navigation"><button type="button" onClick={()=>setIndex((index-1+pending.length)%pending.length)}>‹</button><small>{index%pending.length+1}/{pending.length}</small><button type="button" onClick={()=>setIndex((index+1)%pending.length)}>›</button></span>}
  {active&&createPortal(<div className="client-agenda-detail-backdrop agenda-change-admin-backdrop" onMouseDown={event=>{if(event.currentTarget===event.target&&!busy)setActive(null)}}><section className="agenda-change-admin-modal" role="dialog" aria-modal="true" aria-labelledby="agenda-admin-change-title"><header><div><small>PEDIDO DO CLIENTE</small><h2 id="agenda-admin-change-title">{active.action==='cancel'?'Cancelar reunião':'Reagendar reunião'}</h2></div><button type="button" onClick={()=>setActive(null)} aria-label="Fechar"><X size={18}/></button></header><form onSubmit={decide}><strong>{companyNames[active.company_id]} · {titles[active.event_id]}</strong><p>Original: {date(active.original_starts_at)}</p><p>Motivo do cliente: {active.reason}</p>{active.action==='reschedule'&&<div className="agenda-change-slot-options">{active.slots.map((option,i)=><label key={i}><input type="radio" name="option" checked={slot===i} onChange={()=>setSlot(i)}/>{date(option.startsAt)}</label>)}</div>}<div className="agenda-change-slot-options"><label><input type="radio" name="decision" checked={approve} onChange={()=>setApprove(true)}/>Confirmar pedido</label><label><input type="radio" name="decision" checked={!approve} onChange={()=>setApprove(false)}/>Não confirmar</label></div><label className="agenda-change-note">Resposta ao cliente<textarea minLength={5} required value={note} onChange={event=>setNote(event.target.value)} placeholder="Explique sua decisão e eventual condição de cobrança."/></label>{error&&<p role="alert">{error}</p>}<div className="agenda-change-actions"><button type="button" onClick={()=>setActive(null)}>Voltar</button><button type="submit" disabled={busy}>{busy?'Salvando…':'Enviar resposta'}</button></div></form></section></div>,document.body)}</div>;
}
