import React from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import App from './App';
import { AppErrorBoundary } from './components/AppErrorBoundary';
import { initializeWorkspaceTheme, startWorkspaceThemeClock } from './lib/workspaceTheme';
import { installMapaAuthBridge } from './lib/mapaAuthBridge';
import { installMapaReviewNavigation } from './lib/mapaReviewNavigation';
import { startIdentityMediaRuntime } from './lib/identityMediaRuntime';
import { installReportsPdfRuntime } from './lib/reportsPdfRuntime';
import { installReportsDedupRuntime } from './lib/reportsDedupRuntime';
import { installGoogleCalendarRuntime } from './lib/googleCalendarRuntime';
import { installCalendarSyncGuard } from './lib/calendarSyncGuard';
import { installNotificationNavigationRuntime } from './lib/notificationNavigationRuntime';
import { installRecordsExperienceRuntimeV2 } from './lib/recordsExperienceRuntimeV2';
import { installRecordsMessageControlsRuntime } from './lib/recordsMessageControlsRuntime';
import { installRecordsConversationScrollGuard } from './lib/recordsConversationScrollGuard';
import { installNotificationExperienceRuntime } from './lib/notificationExperienceRuntime';
import { installRecordsOperationsRuntimeV25 } from './lib/recordsOperationsRuntimeV25';
import { installRecordsClosureExperienceRuntimeV29 } from './lib/recordsClosureExperienceRuntimeV29';
import { installRecordsClosureFinalPolishV30 } from './lib/recordsClosureFinalPolishV30';
import { installDashboardSatisfactionRuntimeV29 } from './lib/dashboardSatisfactionRuntimeV29';
import { installDeliverableChatStandardRuntimeV35 } from './lib/deliverableChatStandardRuntimeV35';
import { installDeliverableChatFlickerGuardV36 } from './lib/deliverableChatFlickerGuardV36';
import { installProjectsPlanningIntelligenceRuntimeV36 } from './lib/projectsPlanningIntelligenceRuntimeV36';
import { installProjectsDeadlineAutofillRuntimeV37 } from './lib/projectsDeadlineAutofillRuntimeV37';
import { installProjectApprovalWorkflowRuntimeV38 } from './lib/projectApprovalWorkflowRuntimeV38';
import { installProjectApprovalRulesRuntimeV39 } from './lib/projectApprovalRulesRuntimeV39';
import { installCompanyWorkspaceIdentityRuntimeV39 } from './lib/companyWorkspaceIdentityRuntimeV39';
import { installProjectsClientPortfolioRuntimeV39 } from './lib/projectsClientPortfolioRuntimeV39';
import { installClientHomeCompanyIdentityRuntimeV40 } from './lib/clientHomeCompanyIdentityRuntimeV40';
import { installHoursCompanyLogoRuntimeV41 } from './lib/hoursCompanyLogoRuntimeV41';
import { installDocumentsIdentityRuntimeV42 } from './lib/documentsIdentityRuntimeV42';
import './styles.css';
import './modules.css';
import './ux-v2.css';
import './runtime.css';
import './page1.css';
import './page1-hotfix.css';
import './page1-pass2.css';
import './page1-rules.css';
import './workspace-invariants.css';
import './dashboard-scroll-fix.css';
import './brand-experience.css';
import './brand-experience-v2.css';
import './menu-brand-final.css';
import './theme-system.css';
import './loading-brand-standard.css';
import './page2-client-management.css';
import './page2-account-tabs.css';
import './page2-client-management-v3.css';
import './modal-standard-v2.css';
import './documents-v2.css';
import './page4-calendar.css';
import './page5-projects.css';
import './page5-projects-flow-v2.css';
import './modal-system-v3.css';
import './client-modal-drive-note.css';
import './workspace-typography-connect.css';
import './page5-projects-polish-v3.css';
import './projects-planning-intelligence-v36.css';
import './project-approval-workflow-v38.css';
import './project-approval-rules-v39.css';
import './project-client-portfolio-v39.css';
import './sidebar-brand-artwork.css';
import './sidebar-capacity-v2.css';
import './login-home-v2.css';
import './people-map-admin.css';
import './people-map-admin-v2.css';
import './people-map-review.css';
import './people-map-report-fidelity.css';
import './login-theme-isolation.css';
import './workspace-polish-2026-08-30.css';
import './sidebar-closed-profile-fix.css';
import './sidebar-open-night-profile-fix.css';
import './profile-avatar-polish.css';
import './identity-media.css';
import './documents-v3.css';
import './client-documents-v3.css';
import './documents-flow-v4.css';
import './portal-admin-migration.css';
import './portal-proposal-editor.css';
import './portal-proposal-preview.css';
import './portal-proposals-hotfix.css';
import './portal-proposals-flow-fix.css';
import './portal-proposals-drawer-fix-v2.css';
import './portal-proposal-legacy-host.css';
import './reports-admin-v2.css';
import './reports-v3.css';
import './reports-v4.css';
import './reports-v5.css';
import './reports-v6.css';
import './reports-v7.css';
import './reports-v8.css';
import './reports-v9.css';
import './reports-v10-pdf-fix.css';
import './reports-v11-dedup.css';
import './records-v12.css';
import './records-v13-responsive-fix.css';
import './hours-v12.css';
import './hours-v13.css';
import './hours-final-responsive.css';
import './hours-v14.css';
import './hours-client-portfolio-v40.css';
import './reports-v12.css';
import './reports-v13.css';
import './reports-v14.css';
import './reports-v15.css';
import './reports-v15-process-order.css';
import './client-reports-v12.css';
import './client-home-v2.css';
import './client-home-v3.css';
import './client-home-v4.css';
import './client-timeline-v2.css';
import './client-timeline-v3.css';
import './client-deliverables-v31.css';
import './client-deliverables-v32.css';
import './client-deliverables-v33.css';
import './deliverable-chat-standard-v34.css';
import './deliverable-chat-flicker-fix-v36.css';
import './app-error-boundary.css';
import './records-v14-overlay-fix.css';
import './records-v20-conversation-polish.css';
import './records-v21-chat-theme-fix.css';
import './records-v22-message-controls.css';
import './notification-experience-v2.css';
import './loading-illustrations-final.css';
import './records-v25-operations.css';
import './satisfaction-admin-v39.css';
import './documents-identity-v42.css';
import './chat-night-standard-v42.css';

initializeWorkspaceTheme();
startWorkspaceThemeClock();
installMapaAuthBridge();
installMapaReviewNavigation();
startIdentityMediaRuntime();
installReportsPdfRuntime();
installReportsDedupRuntime();
installGoogleCalendarRuntime();
installCalendarSyncGuard();
installNotificationNavigationRuntime();
installRecordsExperienceRuntimeV2();
installRecordsMessageControlsRuntime();
installRecordsConversationScrollGuard();
installNotificationExperienceRuntime();
installRecordsOperationsRuntimeV25();
installRecordsClosureExperienceRuntimeV29();
installRecordsClosureFinalPolishV30();
installDashboardSatisfactionRuntimeV29();
installDeliverableChatStandardRuntimeV35();
installDeliverableChatFlickerGuardV36();
installProjectsPlanningIntelligenceRuntimeV36();
installProjectsDeadlineAutofillRuntimeV37();
installProjectApprovalWorkflowRuntimeV38();
installProjectApprovalRulesRuntimeV39();
installCompanyWorkspaceIdentityRuntimeV39();
installProjectsClientPortfolioRuntimeV39();
installClientHomeCompanyIdentityRuntimeV40();
installHoursCompanyLogoRuntimeV41();
installDocumentsIdentityRuntimeV42();

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <AppErrorBoundary>
      <BrowserRouter><App /></BrowserRouter>
    </AppErrorBoundary>
  </React.StrictMode>,
);