-- LEGACY MIGRATION DISABLED ON PURPOSE.
--
-- The first prototype of CALI Workspace created generic workspace tables in the
-- public schema. The production decision is to share the current Supabase
-- project temporarily WITHOUT mixing Workspace tables with Mapa/Portal tables.
--
-- The active schema starts in 003_isolated_workspace.sql and lives entirely in
-- cali_workspace. Keep this file as a no-op so existing Git history remains
-- understandable and fresh database setups do not create the legacy public
-- tables.
