import { useEffect, useMemo, useState } from 'react';
import { FileText, Loader2, Printer, ShieldCheck } from 'lucide-react';
import { Shell } from '../../components/WorkspaceShell';
import { ExecutiveReportPaperV16 } from '../../components/reports/ExecutiveReportPaperV16';
import { supabase } from '../../lib/supabase';
import { resolveWorkspaceMedia } from '../../lib/workspaceMedia';
import { type ReportEditor, type ReportType } from '../../lib/reportComposition';
import { normalizeIntelligenceSnapshot, type IntelligenceSnapshot } from '../../lib/reportIntelligence';
import type { DeliveryPerformanceRow } from '../../lib/reportV14';

type Report={id:string;title:string;reportType:ReportType;periodStart:string;periodEnd:string;summary:string;movements:string[];decisions:string[];risks:string[];nextSteps:string[];snapshot:IntelligenceSnapshot|null;protocol:string;publishedAt?:string|null;sentAt?:string|null;version:number;status:'sent'|'published'};
type Company={name:string;logoUrl?:string|null};
function rowToReport(row:any):Report{return{id:row.id,title:row.title,reportType:(row.report_type||'monthly') as ReportType,periodStart:String(row.period_start||row.reference_month).slice(0,10),periodEnd:String(row.period_end||row.reference_month).slice(0,10),summary:row.executive_summary||'',movements:Array.isArray(row.movements)?row.movements.map(String):[],decisions:Array.isArray(row.decisions)?row.decisions.map(String):[],risks:Array.isArray(row.risks)?row.risks.map(String):[],nextSteps:Array.isArray(row.next_steps)?row.next_steps.map(String):[],snapshot:normalizeIntelligenceSnapshot(row.source_snapshot),protocol:row.protocol||'—',publishedAt:row.published_at,sentAt:row.sent_at,version:Number(row.version||1),status:row.status};}
function periodLabel(type:ReportType,start:string){const[year,month]=start.split('-').map(Number);return type==='monthly'?new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'}).format(new Date(year,month-1,1)):`${Math.floor((month-1)/3)+1}º trimestre de ${year}`;}
function editorOf(report:Report):ReportEditor{return{summary:report.summary,movements:report.movements.join('\n'),decisions:report.decisions.join('\n'),risks:report.risks.join('\n'),nextSteps:report.nextSteps.join('\n')};}
function deliveriesOf(report:Report){const raw=(report.snapshot as any)?.deliveryPerformanceV14;return Array.isArray(raw)?raw as DeliveryPerformanceRow[]:[];}

export function ClientReportsPageV4(){
  const[reports,setReports]=useState<Report[]>([]),[company,setCompany]=useState<Company|null>(null),[selectedId,setSelectedId]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
  useEffect(()=>{void load();},[]);
  async function load(){if(!supabase)return;setLoading(true);setError('');try{const user=await supabase.auth.getUser();if(user.error)throw user.error;const profile=await supabase.from('profiles').select('company_id').eq('id',user.data.user?.id||'').maybeSingle();if(profile.error)throw profile.error;const companyId=profile.data?.company_id;if(!companyId)throw new Error('Empresa vinculada ao acesso não encontrada.');const[companyResult,reportResult]=await Promise.all([supabase.from('companies').select('display_name,logo_url').eq('id',companyId).maybeSingle(),supabase.from('reports').select('id,title,report_type,period_start,period_end,reference_month,status,executive_summary,movements,decisions,risks,next_steps,source_snapshot,protocol,published_at,sent_at,version').eq('company_id',companyId).in('status',['sent','published']).order('period_start',{ascending:false}).order('version',{ascending:false})]);if(companyResult.error)throw companyResult.error;if(reportResult.error)throw reportResult.error;setCompany({name:companyResult.data?.display_name||'Empresa',logoUrl:await resolveWorkspaceMedia(companyResult.data?.logo_url)});const next=(reportResult.data||[]).map(rowToReport);setReports(next);if(next.length)setSelectedId(next[0].id);}catch(requestError){setError(requestError instanceof Error?requestError.message:'Não foi possível carregar os relatórios.');}finally{setLoading(false);}}
  const selected=useMemo(()=>reports.find((item)=>item.id===selectedId)||null,[reports,selectedId]);
  function openPrint(){if(selected)window.open(`/cliente/relatorios/impressao/${selected.id}?print=1`,'_blank','noopener,noreferrer');}
  return <Shell role="client"><section className="page client-reports-v16"><header className="client-reports-v16-heading"><div><span className="eyebrow">LEITURA EXECUTIVA</span><h1>Relatórios</h1><p>Aqui ficam somente versões revisadas e enviadas pela CALI. Cada fechamento preserva a fotografia aprovada daquele período.</p></div>{selected?<button className="secondary" type="button" onClick={openPrint}><Printer size={16}/>Baixar / imprimir PDF</button>:null}</header>
    {error?<div className="inline-notice">{error}</div>:null}{loading?<div className="panel data-loading"><Loader2 className="spin" size={20}/>Carregando relatórios…</div>:<div className="client-reports-v16-layout"><aside className="panel client-reports-v16-list"><span className="section-kicker">HISTÓRICO LIBERADO</span>{reports.map((report)=><button type="button" key={report.id} className={selectedId===report.id?'active':''} onClick={()=>setSelectedId(report.id)}><FileText size={18}/><div><strong>{periodLabel(report.reportType,report.periodStart)} · v{report.version}</strong><span>{report.reportType==='quarterly'?'Fechamento trimestral':'Fechamento mensal'}</span><small>{report.protocol}</small></div></button>)}{!reports.length?<div className="client-reports-v16-empty"><FileText size={25}/><p>Nenhum relatório foi liberado ainda.</p></div>:null}</aside><main className="client-reports-v16-document">{selected?.snapshot?<ExecutiveReportPaperV16 company={company||{name:'Empresa'}} snapshot={selected.snapshot} editor={editorOf(selected)} reportType={selected.reportType} periodName={periodLabel(selected.reportType,selected.periodStart)} protocol={selected.protocol} deliveries={deliveriesOf(selected)}/>:selected?<div className="panel client-reports-v16-legacy"><ShieldCheck size={24}/><div><strong>Relatório histórico disponível</strong><p>Esta versão foi publicada antes da base executiva atual. A síntese original permanece preservada.</p><h2>{selected.title}</h2><p>{selected.summary}</p></div></div>:null}</main></div>}
  </section></Shell>;
}
