import { FormEvent, useEffect, useMemo, useState } from 'react';
import { CheckCircle2, Clock3, Loader2, Pause, Play, Plus, Square, TimerReset, X } from 'lucide-react';
import { Shell } from '../../components/WorkspaceShell';
import { supabase } from '../../lib/supabase';

type Company = { id:string; name:string; monthlyHours:number };
type Project = { id:string; companyId:string; name:string };
type Deliverable = { id:string; companyId:string; projectId?:string|null; title:string };
type Entry = { id:string; companyId:string; projectId?:string|null; deliverableId?:string|null; workDate:string; minutes:number; description:string; category?:string|null; clientVisible:boolean; createdAt:string };
type TimerRow = { id:string; companyId:string; projectId?:string|null; deliverableId?:string|null; startedAt:string; status:string; category?:string|null; description?:string|null; clientVisible:boolean; userId:string };

const categories = ['Entregáveis','Subtarefas','Reuniões e alinhamentos','Análise e consultoria','Documentação','Comunicação e follow-up','Treinamentos / encontros','Outros'];
function monthBounds(){const now=new Date();const start=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-01`;const next=new Date(now.getFullYear(),now.getMonth()+1,1);return{start,next:`${next.getFullYear()}-${String(next.getMonth()+1).padStart(2,'0')}-01`};}
function formatMinutes(minutes:number){const h=Math.floor(minutes/60);const m=Math.round(minutes%60);return m?`${h}h ${String(m).padStart(2,'0')}m`:`${h}h`;}
function timerLabel(seconds:number){const h=Math.floor(seconds/3600),m=Math.floor((seconds%3600)/60),s=seconds%60;return[h,m,s].map((v)=>String(v).padStart(2,'0')).join(':');}
function dateLabel(value:string){const date=new Date(`${value.slice(0,10)}T12:00:00`);return new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short'}).format(date).replace('.','');}

export function AdminHoursPageV2(){
  const [companies,setCompanies]=useState<Company[]>([]);const [projects,setProjects]=useState<Project[]>([]);const [deliverables,setDeliverables]=useState<Deliverable[]>([]);const [entries,setEntries]=useState<Entry[]>([]);const [activeTimer,setActiveTimer]=useState<TimerRow|null>(null);const [elapsed,setElapsed]=useState(0);
  const [companyId,setCompanyId]=useState('');const [projectId,setProjectId]=useState('');const [deliverableId,setDeliverableId]=useState('');const [category,setCategory]=useState(categories[0]);const [description,setDescription]=useState('');const [clientVisible,setClientVisible]=useState(false);
  const [manualOpen,setManualOpen]=useState(false);const [manualDate,setManualDate]=useState(()=>new Date().toISOString().slice(0,10));const [manualHours,setManualHours]=useState('1');const [saving,setSaving]=useState(false);const [loading,setLoading]=useState(true);const [notice,setNotice]=useState('');const [error,setError]=useState('');

  useEffect(()=>{void load();},[]);
  useEffect(()=>{if(!activeTimer)return;const tick=()=>setElapsed(Math.max(0,Math.floor((Date.now()-new Date(activeTimer.startedAt).getTime())/1000)));tick();const id=window.setInterval(tick,1000);return()=>window.clearInterval(id);},[activeTimer]);
  useEffect(()=>{document.body.classList.toggle('workspace-modal-open',manualOpen);return()=>document.body.classList.remove('workspace-modal-open');},[manualOpen]);

  async function load(){if(!supabase)return;setLoading(true);setError('');try{const {start,next}=monthBounds();const [companyResult,projectResult,deliverableResult,entryResult,timerResult,userResult]=await Promise.all([
    supabase.from('companies').select('id,display_name,monthly_hours_contracted').neq('status','closed').order('display_name'),
    supabase.from('projects').select('id,company_id,name').neq('status','cancelled').order('name'),
    supabase.from('deliverables').select('id,company_id,project_id,title').not('status','in','(approved,cancelled)').order('title'),
    supabase.from('hour_entries').select('id,company_id,project_id,deliverable_id,work_date,minutes,description,category,client_visible,created_at').gte('work_date',start).lt('work_date',next).order('work_date',{ascending:false}).order('created_at',{ascending:false}),
    supabase.from('work_timers').select('id,company_id,project_id,deliverable_id,user_id,started_at,status,category,description,client_visible').eq('status','active').order('started_at',{ascending:false}).limit(1),
    supabase.auth.getUser(),
  ]);if(companyResult.error)throw companyResult.error;if(projectResult.error)throw projectResult.error;if(deliverableResult.error)throw deliverableResult.error;if(entryResult.error)throw entryResult.error;if(timerResult.error)throw timerResult.error;if(userResult.error)throw userResult.error;
    const nextCompanies=(companyResult.data||[]).map((r:any)=>({id:r.id,name:r.display_name,monthlyHours:Number(r.monthly_hours_contracted||0)}));setCompanies(nextCompanies);setProjects((projectResult.data||[]).map((r:any)=>({id:r.id,companyId:r.company_id,name:r.name})));setDeliverables((deliverableResult.data||[]).map((r:any)=>({id:r.id,companyId:r.company_id,projectId:r.project_id,title:r.title})));setEntries((entryResult.data||[]).map((r:any)=>({id:r.id,companyId:r.company_id,projectId:r.project_id,deliverableId:r.deliverable_id,workDate:r.work_date,minutes:Number(r.minutes||0),description:r.description,category:r.category,clientVisible:Boolean(r.client_visible),createdAt:r.created_at})));
    const timer=(timerResult.data||[])[0];setActiveTimer(timer?{id:timer.id,companyId:timer.company_id,projectId:timer.project_id,deliverableId:timer.deliverable_id,userId:timer.user_id,startedAt:timer.started_at,status:timer.status,category:timer.category,description:timer.description,clientVisible:Boolean(timer.client_visible)}:null);if(!companyId&&nextCompanies.length)setCompanyId(nextCompanies[0].id);
  }catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar as horas.');}finally{setLoading(false);}}

  const selectedCompany=companies.find((item)=>item.id===companyId)||null;const companyProjects=projects.filter((item)=>item.companyId===companyId);const companyDeliverables=deliverables.filter((item)=>item.companyId===companyId&&(!projectId||item.projectId===projectId));
  const totals=useMemo(()=>companies.map((company)=>{const minutes=entries.filter((entry)=>entry.companyId===company.id).reduce((sum,item)=>sum+item.minutes,0);const contracted=company.monthlyHours*60;return{...company,minutes,pct:contracted?Math.round(minutes/contracted*100):0};}),[companies,entries]);
  const categoryTotals=useMemo(()=>{const map=new Map<string,number>();entries.filter((entry)=>!companyId||entry.companyId===companyId).forEach((entry)=>map.set(entry.category||'Outros',(map.get(entry.category||'Outros')||0)+entry.minutes));return Array.from(map.entries()).map(([label,minutes])=>({label,minutes})).sort((a,b)=>b.minutes-a.minutes);},[entries,companyId]);

  async function startTimer(){if(!supabase||!companyId||!description.trim())return;setSaving(true);setError('');try{const user=await supabase.auth.getUser();if(user.error)throw user.error;const result=await supabase.from('work_timers').insert({company_id:companyId,project_id:projectId||null,deliverable_id:deliverableId||null,user_id:user.data.user?.id,started_at:new Date().toISOString(),status:'active',category,description:description.trim(),client_visible:clientVisible}).select('id,company_id,project_id,deliverable_id,user_id,started_at,status,category,description,client_visible').single();if(result.error)throw result.error;setActiveTimer({id:result.data.id,companyId:result.data.company_id,projectId:result.data.project_id,deliverableId:result.data.deliverable_id,userId:result.data.user_id,startedAt:result.data.started_at,status:result.data.status,category:result.data.category,description:result.data.description,clientVisible:Boolean(result.data.client_visible)});setElapsed(0);setNotice('Timer iniciado.');}catch(e){setError(e instanceof Error?e.message:'Não foi possível iniciar o timer.');}finally{setSaving(false);}}
  async function stopTimer(){if(!supabase||!activeTimer)return;setSaving(true);setError('');try{const stoppedAt=new Date();const minutes=Math.max(1,Math.round((stoppedAt.getTime()-new Date(activeTimer.startedAt).getTime())/60000));const entryResult=await supabase.from('hour_entries').insert({company_id:activeTimer.companyId,project_id:activeTimer.projectId||null,deliverable_id:activeTimer.deliverableId||null,work_date:stoppedAt.toISOString().slice(0,10),minutes,description:activeTimer.description||'Atuação registrada por timer',category:activeTimer.category||'Outros',client_visible:activeTimer.clientVisible,created_by:activeTimer.userId});if(entryResult.error)throw entryResult.error;const timerResult=await supabase.from('work_timers').update({status:'stopped',stopped_at:stoppedAt.toISOString(),minutes}).eq('id',activeTimer.id);if(timerResult.error)throw timerResult.error;setNotice(`${formatMinutes(minutes)} registrados em ${activeTimer.category||'Outros'}.`);setActiveTimer(null);setElapsed(0);setDescription('');await load();}catch(e){setError(e instanceof Error?e.message:'Não foi possível encerrar o timer.');}finally{setSaving(false);}}
  async function saveManual(event:FormEvent){event.preventDefault();if(!supabase||!companyId||!description.trim())return;const hours=Number(manualHours.replace(',','.'));if(!Number.isFinite(hours)||hours<=0)return;setSaving(true);setError('');try{const user=await supabase.auth.getUser();if(user.error)throw user.error;const result=await supabase.from('hour_entries').insert({company_id:companyId,project_id:projectId||null,deliverable_id:deliverableId||null,work_date:manualDate,minutes:Math.max(1,Math.round(hours*60)),description:description.trim(),category,client_visible:clientVisible,created_by:user.data.user?.id});if(result.error)throw result.error;setManualOpen(false);setNotice('Lançamento manual registrado.');setDescription('');await load();}catch(e){setError(e instanceof Error?e.message:'Não foi possível registrar a hora.');}finally{setSaving(false);}}

  return <Shell role="admin"><section className="page hours-v12"><header className="hours-v12-heading"><div><span className="eyebrow">TEMPO DE EXECUÇÃO</span><h1>Horas</h1><p>Horas reais, vinculadas ao cliente e classificadas pela natureza do trabalho. As categorias alimentam diretamente os relatórios e a leitura de aderência do pacote.</p></div><button className="secondary" type="button" onClick={()=>setManualOpen(true)}><Plus size={16}/>Lançar hora manual</button></header>
    {notice&&<div className="inline-notice success"><CheckCircle2 size={18}/>{notice}</div>}{error&&<div className="inline-notice">{error}</div>}
    <section className={`hours-v12-timer ${activeTimer?'running':''}`}><div className="hours-v12-timer-icon"><TimerReset size={25}/></div>{activeTimer?<><div className="hours-v12-active-copy"><span>EM ANDAMENTO</span><strong>{companies.find((item)=>item.id===activeTimer.companyId)?.name||'Cliente'} · {activeTimer.category}</strong><small>{activeTimer.description}</small></div><strong className="hours-v12-clock">{timerLabel(elapsed)}</strong><button className="primary danger-action" disabled={saving} type="button" onClick={()=>void stopTimer()}><Square size={16}/>Encerrar</button></>:<><div className="hours-v12-timer-fields"><select value={companyId} onChange={(e)=>{setCompanyId(e.target.value);setProjectId('');setDeliverableId('');}}>{companies.map((company)=><option key={company.id} value={company.id}>{company.name}</option>)}</select><select value={projectId} onChange={(e)=>{setProjectId(e.target.value);setDeliverableId('');}}><option value="">Sem projeto específico</option>{companyProjects.map((project)=><option key={project.id} value={project.id}>{project.name}</option>)}</select><select value={deliverableId} onChange={(e)=>setDeliverableId(e.target.value)}><option value="">Sem entregável específico</option>{companyDeliverables.map((item)=><option key={item.id} value={item.id}>{item.title}</option>)}</select><select value={category} onChange={(e)=>setCategory(e.target.value)}>{categories.map((item)=><option key={item}>{item}</option>)}</select><input value={description} onChange={(e)=>setDescription(e.target.value)} placeholder="O que está sendo feito?"/></div><button className="primary" disabled={saving||!companyId||!description.trim()} type="button" onClick={()=>void startTimer()}><Play size={16}/>Iniciar</button></>}</section>
    {loading?<div className="panel data-loading"><Loader2 className="spin" size={20}/>Lendo apontamentos…</div>:<>
      <section className="hours-v12-capacity">{totals.map((item)=><article key={item.id}><span>{item.name}</span><strong>{item.monthlyHours?`${item.pct}%`:'—'}</strong><small>{formatMinutes(item.minutes)}{item.monthlyHours?` de ${item.monthlyHours}h`:''}</small><div><i style={{width:`${Math.min(100,item.pct)}%`}}/></div></article>)}</section>
      <div className="hours-v12-layout"><section className="panel hours-v12-entries"><div className="panel-title"><div><span className="section-kicker">EXTRATO REAL</span><h2>Registros do mês</h2></div></div><div className="hours-v12-entry-list">{entries.slice(0,30).map((entry)=><article key={entry.id}><time>{dateLabel(entry.workDate)}</time><div><strong>{companies.find((item)=>item.id===entry.companyId)?.name||'Cliente'} · {entry.category||'Outros'}</strong><span>{entry.description}</span></div><b>{formatMinutes(entry.minutes)}</b></article>)}{!entries.length&&<p className="hours-v12-empty">Nenhuma hora registrada neste mês.</p>}</div></section><aside className="panel hours-v12-categories"><span className="section-kicker">COMPOSIÇÃO</span><h2>{selectedCompany?.name||'Cliente'}</h2>{categoryTotals.map((item)=><div key={item.label}><span>{item.label}</span><strong>{formatMinutes(item.minutes)}</strong><i style={{width:`${Math.min(100,categoryTotals[0]?.minutes?item.minutes/categoryTotals[0].minutes*100:0)}%`}}/></div>)}{!categoryTotals.length&&<p>Sem categorias registradas.</p>}</aside></div>
    </>}
    {manualOpen&&<div className="modal-backdrop workspace-modal-backdrop"><form className="modal-card hours-v12-manual" onSubmit={saveManual}><button className="modal-close" type="button" onClick={()=>setManualOpen(false)}><X size={20}/></button><header><span className="section-kicker">LANÇAMENTO MANUAL</span><h2>Registrar horas</h2><p>Use a mesma categoria que deve aparecer na composição do relatório.</p></header><div className="hours-v12-manual-grid"><label className="stacked-label">Cliente<select value={companyId} onChange={(e)=>{setCompanyId(e.target.value);setProjectId('');setDeliverableId('');}}>{companies.map((company)=><option key={company.id} value={company.id}>{company.name}</option>)}</select></label><label className="stacked-label">Data<input type="date" value={manualDate} onChange={(e)=>setManualDate(e.target.value)}/></label><label className="stacked-label">Horas<input type="number" min="0.25" step="0.25" value={manualHours} onChange={(e)=>setManualHours(e.target.value)}/></label><label className="stacked-label">Categoria<select value={category} onChange={(e)=>setCategory(e.target.value)}>{categories.map((item)=><option key={item}>{item}</option>)}</select></label><label className="stacked-label">Projeto<select value={projectId} onChange={(e)=>{setProjectId(e.target.value);setDeliverableId('');}}><option value="">Sem projeto específico</option>{companyProjects.map((project)=><option key={project.id} value={project.id}>{project.name}</option>)}</select></label><label className="stacked-label">Entregável<select value={deliverableId} onChange={(e)=>setDeliverableId(e.target.value)}><option value="">Sem entregável específico</option>{companyDeliverables.map((item)=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label className="stacked-label wide">Descrição<textarea rows={3} value={description} onChange={(e)=>setDescription(e.target.value)} placeholder="Contexto da atuação"/></label><label className="hours-v12-visible wide"><input type="checkbox" checked={clientVisible} onChange={(e)=>setClientVisible(e.target.checked)}/><span>Este apontamento pode ser exibido ao cliente</span></label></div><footer><button className="secondary" type="button" onClick={()=>setManualOpen(false)}>Cancelar</button><button className="primary" type="submit" disabled={saving||!description.trim()}>{saving?<Loader2 className="spin" size={15}/>:<Clock3 size={15}/>}Registrar</button></footer></form></div>}
  </section></Shell>;
}
