import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Loader2, Mail, Printer, Send, X } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import { Shell } from '../../components/WorkspaceShell';
import { loadPortalProposal, portalServiceLabel, sendPortalProposal, type PortalProposal, type PortalSubmission } from '../../lib/portalAdminApi';
import { PACKAGE_META } from '../../lib/portalProposalConfig';

type FullProposal=PortalProposal&{submission:PortalSubmission};
const CALI_LOGO='https://raw.githubusercontent.com/patricia258/cali-portal/main/assets/logo-cali-bordo.png';
function list(value:any):string[]{return Array.isArray(value)?value.map(String).filter(Boolean):[];}
function currency(value:number){return Number(value||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});}
function date(value?:string|null){if(!value)return '—';return new Intl.DateTimeFormat('pt-BR').format(new Date(value));}
function fileSafe(value:string){return value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9 _.-]+/g,'').replace(/\s+/g,' ').trim();}
function filename(p:FullProposal){return fileSafe(`Proposta CALI RH - ${portalServiceLabel(p.service_slug)} - ${p.submission.company_name||p.submission.contact_name} - ${p.submission.protocol}.pdf`);}
function fileBase64(file:File){return new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]||'');r.onerror=()=>reject(new Error('Não foi possível ler o PDF.'));r.readAsDataURL(file);});}
function scopeGroups(items:any[]){const groups:Array<{number:number;text:string;subitems:string[]}>=[];for(const item of items.map(String)){const isSub=/^\s*[-–—]\s*/.test(item),text=item.replace(/^\s*[-–—]\s*/,'');if(isSub&&groups.length)groups.at(-1)!.subitems.push(text);else groups.push({number:groups.length+1,text,subitems:[]});}return groups;}
function paymentRows(proposal:FullProposal){const calc=proposal.calculator_data||{},payment=calc.payment||{},rows:Array<[string,string]>=[];if(payment.method==='monthly')rows.push(['Forma','Mensal recorrente'],['Vencimento',payment.monthlyDue||'1º dia útil de cada mês']);else if(payment.method==='split'){const a=Number(payment.entryPct||50),b=Number(payment.finalPct||50);rows.push([`Entrada · ${a}%`,currency(proposal.final_unit*a/100)],[`Finalização · ${b}%`,currency(proposal.final_unit*b/100)]);}else if(payment.method==='pix')rows.push(['Forma','PIX à vista'],['Desconto aplicado',`${Number(payment.pixDiscount||proposal.discount_pct||0).toLocaleString('pt-BR',{maximumFractionDigits:2})}%`]);else if(payment.method==='card')rows.push(['Parcelamento',`Até ${Number(payment.cardInstallments||1)}x no cartão`],['Taxas',payment.cardFees==='included'?'Incluídas no valor final':'Acrescidas conforme a operadora']);else rows.push(['Forma',payment.customLabel||(calc.monthly?'Mensal recorrente':'Conforme cronograma acordado')]);return rows;}

function ProposalPage({proposal,index,total,children,className=''}:{proposal:FullProposal;index:number;total:number;children:React.ReactNode;className?:string}){const validity=new Date(proposal.updated_at||proposal.created_at);validity.setDate(validity.getDate()+Number(proposal.validity_days||15));return <article className={`portal-proposal-page ${className}`}><header><img src={CALI_LOGO} alt="CALI — HR for Business"/><div><strong>{proposal.submission.protocol}</strong><span>{date(proposal.updated_at||proposal.created_at)} · válida até {date(validity.toISOString())}</span></div></header><main>{children}</main><footer><span>Patrícia Lima · CALI RH · patricia@calirh.com</span><span>{String(index).padStart(2,'0')} / {String(total).padStart(2,'0')}</span></footer></article>}

export function AdminProposalPreviewPage(){const{proposalId=''}=useParams();const navigate=useNavigate();const[proposal,setProposal]=useState<FullProposal|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[sendOpen,setSendOpen]=useState(false),[sending,setSending]=useState(false),[company,setCompany]=useState(''),[recipient,setRecipient]=useState(''),[email,setEmail]=useState(''),[note,setNote]=useState(''),[file,setFile]=useState<File|null>(null),[sentMessage,setSentMessage]=useState('');
  useEffect(()=>{void(async()=>{setLoading(true);try{const data=await loadPortalProposal(proposalId);if(!data)throw new Error('Proposta não encontrada.');setProposal(data);setCompany(data.submission.company_name||'');setRecipient(data.submission.contact_name||'');setEmail(data.submission.contact_email||'');}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar a proposta.');}finally{setLoading(false);}})();},[proposalId]);
  const calc=proposal?.calculator_data||{},packageInfo=proposal?(PACKAGE_META[proposal.service_slug]||[]).find(item=>item.code===proposal.package_code):null,cycles=list(calc.cycles),roadmap=list(calc.roadmapItems),out=list(calc.outOfScope),scope=proposal?scopeGroups(proposal.scope_items):[],payment=proposal?paymentRows(proposal):[],bonus=calc.bonus||null,pain=list(calc.painPoints),results=list(calc.expectedResults),advantages=list(calc.advantages),cadence=list(calc.cadence),caliResponsibilities=list(calc.caliResponsibilities),clientResponsibilities=list(calc.clientResponsibilities),map=calc.mapaPeople;
  const hasCycles=cycles.length>0,total=5,monthly=Boolean(calc.monthly||proposal?.service_slug==='assessoria-estrategica'||(proposal?.service_slug==='marca-empregadora'&&proposal?.package_code==='RECORRENTE'));
  function print(){if(!proposal)return;const old=document.title;document.title=filename(proposal).replace(/\.pdf$/i,'');window.print();window.setTimeout(()=>{document.title=old;},700);}
  async function send(){if(!proposal||!file)return;if(file.size>8*1024*1024){setError('O PDF ultrapassa 8 MB.');return;}if(recipient.trim().length<2||!email.includes('@')){setError('Confirme nome e e-mail do decisor.');return;}setSending(true);setError('');setSentMessage('');try{const result=await sendPortalProposal({proposal_id:proposal.id,pdf_base64:await fileBase64(file),pdf_name:file.name,note,company_name:company.trim(),recipient_name:recipient.trim(),recipient_email:email.trim()});setSentMessage(`Proposta enviada para ${result.to||email} ✓`);setProposal(current=>current?{...current,status:'enviada',sent_at:new Date().toISOString()}:current);}catch(e){setError(e instanceof Error?e.message:'Falha no envio.');}finally{setSending(false);}}
  if(loading)return <Shell role="admin"><section className="page"><div className="panel portal-admin-loading"><Loader2 className="spin"/>Carregando proposta…</div></section></Shell>;
  if(!proposal)return <Shell role="admin"><section className="page"><div className="inline-notice danger">{error||'Proposta não encontrada.'}</div></section></Shell>;
  const firstName=proposal.submission.contact_name.trim().split(/\s+/)[0]||'Olá',reference=Number(proposal.subtotal||proposal.final_unit||0),discount=Math.max(0,reference-Number(proposal.final_unit||0)),hours=Number(calc.monthlyHours||packageInfo?.suggestedHours||0),minimumMonths=Number(proposal.contract_months||packageInfo?.minimumMonths||1);
  return <Shell role="admin"><section className="page portal-proposal-preview"><header className="portal-proposal-preview-toolbar"><button className="secondary" onClick={()=>navigate(`/admin/propostas/${proposal.submission_id}/editar`)}><ArrowLeft size={16}/>Editar proposta</button><div><strong>Prévia da proposta · v{proposal.version}</strong><span>Confira todas as páginas antes de salvar e enviar.</span></div><div><button className="secondary" onClick={print}><Printer size={16}/>Salvar PDF</button><button className="primary" onClick={()=>setSendOpen(true)}><Mail size={16}/>Enviar por e-mail</button></div></header>{error&&<div className="inline-notice danger">{error}</div>}<div className="portal-proposal-document">
    <ProposalPage proposal={proposal} index={1} total={total} className="context"><div className="proposal-kicker">Proposta preparada para</div><h1>Olá, <em>{firstName}</em>.<br/>Sua proposta chegou.</h1><div className="proposal-client"><span>Empresa</span><strong>{proposal.submission.company_name||'Não informada'}</strong></div><section><small>01 · O ponto de partida</small><h2>O que entendemos</h2><p className="lead">{calc.contextSummary||'Contexto em revisão.'}</p></section>{pain.length>0&&<section><h3>Dores iniciais</h3><ul>{pain.map((item:string)=><li key={item}>{item}</li>)}</ul></section>}{map?.include&&Number(map.score)>0&&<aside className="map-result"><span>Resultado do Mapa de People</span><strong>{Number(map.score).toLocaleString('pt-BR',{minimumFractionDigits:1,maximumFractionDigits:1})}<small>/10</small></strong><b>{map.quadrant}</b></aside>}<aside className="strategic-reading"><span>Leitura estratégica</span><p>{calc.executiveReading}</p></aside></ProposalPage>
    <ProposalPage proposal={proposal} index={2} total={total} className="solution"><div className="proposal-kicker">Solução recomendada</div><h1>{packageInfo?.label||proposal.package_code}</h1><p className="service-label">{portalServiceLabel(proposal.service_slug)}</p><p className="lead">{proposal.public_notes||packageInfo?.description}</p><div className="solution-grid"><section><span>Por que agora</span><p>{calc.whyNow}</p></section><section><span>Objetivo do ciclo</span><p>{calc.cycleObjective}</p></section></div>{results.length>0&&<section><h2>O que este trabalho deve colocar em movimento</h2><ul>{results.map((item:string)=><li key={item}>{item}</li>)}</ul></section>}{advantages.length>0&&<section><h2>Por que a CALI neste contexto</h2><div className="advantage-grid">{advantages.slice(0,4).map((item:string,i:number)=><div key={item}><span>{String(i+1).padStart(2,'0')}</span><p>{item}</p></div>)}</div></section>}</ProposalPage>
    <ProposalPage proposal={proposal} index={3} total={total} className="delivery"><div className="proposal-kicker">Escopo contratado</div><h1>Escopo incluído</h1><p className="page-intro">As entregas abaixo seguem exatamente a ordem definida para esta proposta.</p><ol className="scope-list">{scope.map(item=><li key={item.number}><span>{String(item.number).padStart(2,'0')}</span><div><strong>{item.text}</strong>{item.subitems.length>0&&<ul>{item.subitems.map(sub=><li key={sub}>{sub}</li>)}</ul>}</div></li>)}</ol>{cadence.length>0&&<section><h2>Cadência</h2><ul>{cadence.map((item:string)=><li key={item}>{item}</li>)}</ul></section>}<section><h2>Responsabilidades</h2><div className="responsibility-grid"><div><span>A CALI conduz</span><ul>{caliResponsibilities.map((item:string)=><li key={item}>{item}</li>)}</ul></div><div><span>O cliente fornece</span><ul>{clientResponsibilities.map((item:string)=><li key={item}>{item}</li>)}</ul></div></div></section></ProposalPage>
    <ProposalPage proposal={proposal} index={4} total={total} className="roadmap"><div className="proposal-kicker">{hasCycles?'Sequência de implantação':'Organização do trabalho'}</div><h1>{hasCycles?'Ciclos e fases de implantação':'Roadmap e limites'}</h1>{hasCycles&&<div className="cycle-list">{(calc.cycles||[]).slice(0,6).map((cycle:any,i:number)=><section key={`${cycle.title}-${i}`}><span>{String(i+1).padStart(2,'0')}</span><div><h2>{cycle.title}</h2>{cycle.duration&&<small>{cycle.duration}</small>}{cycle.focus&&<strong>{cycle.focus}</strong>}{cycle.objective&&<p>{cycle.objective}</p>}</div></section>)}</div>}<aside className="roadmap-note"><strong>Roadmap posterior</strong><p>As demais prioridades do briefing são organizadas por impacto, dependência e sequência de implantação. Necessidades não incluídas neste ciclo permanecem registradas para etapas posteriores.</p>{roadmap.length>0&&<ul>{roadmap.map((item:string)=><li key={item}>{item}</li>)}</ul>}</aside>{out.length>0&&<section><h2>Fora do escopo</h2><ul>{out.map((item:string)=><li key={item}>{item}</li>)}</ul></section>}</ProposalPage>
    <ProposalPage proposal={proposal} index={5} total={total} className="commercial"><div className="proposal-kicker">Condições comerciais</div><h1>Investimento e próximos passos</h1><section className="investment"><div><span>{monthly?'Mensalidade de referência':'Investimento de referência'}</span><strong>{currency(reference)}</strong></div>{discount>0&&<div className="discount"><span>{calc.discountType||'Condição comercial'}{calc.discountDescription?` · ${calc.discountDescription}`:''}</span><strong>− {currency(discount)}</strong></div>}<div className="final"><span>{monthly?'Mensalidade final':'Investimento final'}</span><strong>{currency(proposal.final_unit)}</strong></div></section><div className="commercial-facts">{hours>0&&<div><span>Capacidade</span><strong>Até {hours} horas por mês</strong></div>}<div><span>{monthly?'Prazo mínimo':'Duração prevista'}</span><strong>{minimumMonths} {minimumMonths===1?'mês':'meses'}</strong></div><div><span>Natureza</span><strong>{monthly?'Atuação recorrente e fracionada':'Projeto com início e fim'}</strong></div></div><section><h2>Forma de pagamento</h2><div className="payment-grid">{payment.map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>{proposal.payment_terms&&<p>{proposal.payment_terms}</p>}</section>{bonus?.title&&<aside className="bonus"><span>Bônus selecionado</span><div><strong>{bonus.title}</strong><p>{bonus.description}</p></div></aside>}<section><h2>Próximos passos</h2><div className="next-steps">{[['Aprovação','Confirmação do investimento, formato e escopo.'],['Contrato','Formalização das condições e responsabilidades.'],['Kickoff','Alinhamento final e organização dos insumos.'],['Início','Execução conforme o cronograma acordado.']].slice(0,3).map((step,i)=><div key={step[0]}><span>{String(i+1).padStart(2,'0')}</span><strong>{step[0]}</strong><p>{step[1]}</p></div>)}</div></section><div className="proposal-signature"><strong>Patrícia Lima</strong><span>People Advisory Executive · CALI RH</span></div></ProposalPage>
  </div>
  {sendOpen&&<><button className="portal-send-backdrop" onClick={()=>setSendOpen(false)} aria-label="Fechar"/><aside className="portal-send-drawer"><header><div><span className="eyebrow">ENVIO APROVADO</span><h2>Enviar proposta</h2><p>{portalServiceLabel(proposal.service_slug)} · {proposal.submission.protocol}</p></div><button className="icon-button" onClick={()=>setSendOpen(false)}><X/></button></header><div className="portal-send-scroll"><section><h3>1. Salve o PDF</h3><p>Use “Salvar PDF”. O nome sugerido é <strong>{filename(proposal)}</strong>.</p></section><section><h3>2. Confirme o destinatário</h3><label>Empresa<input value={company} onChange={e=>setCompany(e.target.value)}/></label><label>Nome do decisor<input value={recipient} onChange={e=>setRecipient(e.target.value)}/></label><label>E-mail de envio<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><div className="subject-preview"><span>Assunto do e-mail</span><strong>CALI RH - Olá, {recipient||'Nome do decisor'}, Sua proposta chegou! 🧲 {portalServiceLabel(proposal.service_slug)} · {proposal.submission.protocol}.</strong></div></section><section><h3>3. Anexe e envie</h3><label>Proposta final em PDF<input type="file" accept="application/pdf,.pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/><small>Máximo 8 MB.</small></label><label>Mensagem pessoal adicional<textarea rows={5} value={note} onChange={e=>setNote(e.target.value)} placeholder="Ex.: Foi muito bom conhecer o momento da equipe na nossa conversa."/></label>{sentMessage&&<div className="inline-notice success">{sentMessage}</div>}</section></div><footer><button className="primary" disabled={!file||sending} onClick={()=>void send()}><Send size={16}/>{sending?'Enviando…':'Confirmar e enviar'}</button></footer></aside></>}
  </section></Shell>;
}
